- internal/node_install.bzl
makes it work on Bazel on Windows
see https://github.com/bazelbuild/bazel/commit/c2c938ae2e75b5b881f06b18cce86dc87bae6fe6
> change yarn script to an sh_binary

- .circleci/config.yml
- internal/node_loader.js
> address code review comments

- internal/node_loader.js
Look for foo.js in the runfiles manifest when asked for foo
> Workaround #25

- internal/jasmine_node_test.bzl
> Support testing targets in different workspaces.

- internal/node.bzl
See the discussion on the same code [here](https://github.com/bazelbuild/rules_nodejs/commit/cdac9e2320f789400ff681788a76e7a966838569).
@alexeagle FYI, I moved this into a separate commit as I start working on the other stuff.  If you have something more complete in flight I'm happy to rebase on that once it lands.
> Split off a potential fix.

- internal/check_bazel_version_test.py
> Update to Python 3

- internal/collect_es6_sources.bzl
- internal/common/BUILD.bazel
- internal/e2e/rollup/BUILD.bazel
- internal/e2e/rollup/foo.js
- internal/e2e/rollup/fum/BUILD.bazel
- internal/e2e/rollup/fum/index.js
- internal/e2e/rollup/rollup.spec.js
- internal/js_library.bzl
- internal/rollup/rollup.config.js
- internal/rollup/rollup_bundle.bzl
Includes @alexeagle commit from #89
> Handle module mappings in rollup_bundle rule

- internal/e2e/rollup/BUILD.bazel
- internal/e2e/rollup/bundle-min-debug_golden.js
- internal/e2e/rollup/bundle-min_golden.js
- internal/e2e/rollup/foo.js
- internal/e2e/rollup/rollup.spec.js
- internal/rollup/rollup_bundle.bzl
- internal/rollup/uglify.config.json
Requested by @mhevery - I hope he knows what he's doing...
> set uglify option sequences:false in debug mode

- internal/node_install.bzl
- internal/node_labels.bzl
- internal/npm_install.bzl
> Use bazel managed node when running npm

- internal/rollup/rollup.config.js
- internal/rollup/rollup_bundle.bzl
> Fix rollup_bundle module resolution for user workspace files

- internal/e2e/rollup/rollup.spec.js
- internal/node.bzl
- internal/node_launcher.sh
/cc @mhevery who I promised this to today
> When golden test fails, print the command to update golden files

- internal/yarn_install.bzl
> Use local yarn cache

- internal/e2e/rollup/rollup.spec.js
- internal/rollup/yarn.lock
Also refresh a yarn.lock file that's out of date.
> Fix UPDATE_GOLDEN workflow after keys were quoted.

- internal/e2e/rollup/rollup.spec.js
- internal/rollup/rollup.config.js
- internal/test/package.json
- internal/test/yarn.lock
> Fixes e2e rollup golden test on windows

- examples/packages/BUILD.bazel
- examples/packages/WORKSPACE
- examples/packages/test_npm_determinism.spec.js
- examples/packages/test_yarn_determinism.spec.js
> Test npm_install and yarn_install determinism

- .circleci/config.yml
Also hides npm & yarn. Verifies that #7 is fixed.
> Hide node in circleci to verify that system node is not needed

- internal/npm_package/npm_package.bzl
don't rely on the ctx to give us the nested packages, it might be output within the same rule
> fix npm_package reusability

- internal/e2e/rollup/fum/BUILD.bazel
- internal/rollup/rollup.config.js
- internal/rollup/rollup.config.spec.js
- internal/rollup/rollup_bundle.bzl
> Fix rollup

- examples/packages/package.json
- examples/packages/postinstall.js
- examples/packages/setup_workspace.bzl
- internal/npm_install/npm_install.bzl
> Adds data attribute to npm_install and yarn_install

- .circleci/config.yml
- WORKSPACE
- examples/rollup/rollup.bzl
- internal/jasmine_node_test/jasmine_node_test.bzl
- internal/node/node.bzl
- internal/node/node_launcher.sh
- internal/node/node_repositories.bzl
- internal/npm_package/npm_package.bzl
- internal/npm_package/test/BUILD.bazel
- internal/npm_package/test/npm_package.spec.js
- internal/rollup/rollup_bundle.bzl
- package.json
This function can used by any bash script that needs to resolve runfiles including many scripts in rules_typescript.
> Use @bazel_tools//tools/bash/runfiles for runfiles resolve

- WORKSPACE
> Use supported versions of repository rules/

- internal/node/node_loader.js
Since we now load the runfiles.bash helper, the RUNFILES_MANIFEST_FILE gets set on all platforms.
We still want to use the fast method of reading from symlinks on MacOS and Linux.
Use the RUNFILES_MANIFEST_ONLY variable like Bazel does, see
https://github.com/bazelbuild/bazel/blob/9f380c578d0cb9b846be5b906e99cd5e29e28446/src/tools/runfiles/java/com/google/devtools/build/runfiles/Runfiles.java#L108
> Fix module loading

- README.md
- examples/packages/WORKSPACE
- examples/program/WORKSPACE
- package.json
ref: https://github.com/bazelbuild/rules_nodejs/commit/ce8148b7de3a3d7621e47d26dc30e21fd0849a14
> fix(examples): add bazel_skylib to examples workspaces

- README.md
- on-version.js
- package.bzl
- package.json
- yarn.lock
Cleaned up package.json comments as well since duplicate `//` entries will be automatically removed by `npm version` during release steps.
> Add script to bump version

- package.bzl
> Update bazel_toolchains pin.

- package.bzl
See https://github.com/bazelbuild/rules_nodejs/issues/349
> Update skydoc to fix rules_nodejs issue 349

- package.bzl
Needed as part of bazelbuild/bazel#6283.
> Update rules_go to 0.16.0

- internal/node/node_loader.js
Add a few TODOs from #354 that didn't make it in
> Add TODOs for when --nolegacy_external_runfiles is default

- README.md
Also marking the default version.
> Update list of supported node/yarn versions.

- internal/e2e/fine_grained_deps/BUILD.bazel
- internal/e2e/fine_grained_deps/common.spec.js
- internal/e2e/fine_grained_deps/package-lock.json
- internal/e2e/fine_grained_deps/package.json
- internal/e2e/fine_grained_deps/yarn.lock
- internal/npm_install/generate_build_file.js
Fixes https://github.com/bazelbuild/rules_nodejs/issues/408
> Make BUILD file check in fine grained deps case insensitive

- internal/e2e/fine_grained_deps/common.spec.js
- internal/e2e/fine_grained_deps/package-lock.json
- internal/e2e/fine_grained_deps/package.json
- internal/e2e/fine_grained_deps/yarn.lock
- internal/npm_install/npm_install.bzl
- internal/npm_install/process_package_json.js
Based on #405 so that should land first
> Add exclude_packages

- internal/rollup/rollup_bundle.bzl
- package.bzl
- No implicit flattening of depsets
- Separate tools from inputs in an action
- Update some dependencies
Fixes #431
> Cleanups for compatibility with future Bazel releases

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- DEVELOPING.md
- README.md
This PR introduces:
1. Issue templates for bug reports and feature requests
1. Pull request template
1. Code of conduct, which reuses the content from angular/angular
1. Guidelines for contributing to the project
1. A development document which explains how to get started with fixing
issues/implementing new rules. There's more work here, this is just the
initial draft
1. Update of the readme to introduce project scope
> docs: add community documentation

- internal/rollup/rollup.config.js
Pointed out in https://github.com/bazelbuild/rules_nodejs/issues/442
> Fix comment on paths in rollup.config.js

- internal/e2e/check.js
- internal/e2e/rollup/BUILD.bazel
- internal/e2e/rollup/bundle-cjs_golden.js_
- internal/e2e/rollup/rollup.spec.js
- internal/rollup/rollup_bundle.bzl
Fixes #374
Closes #375
/cc @mattem
> Introduce CJS output from rollup_bundle

- internal/npm_package/npm_package.bzl
Currently the `npm_package` acceps an arbitary list of targets that will be built as `deps`. Some of these dependencies are within the Bazel package that defines the `npm_package` and should be also copied into the `npm_package`.
Transitive dependencies (or explicit deps) which are outside of the current package are currently passed to the `packager` and accidentally written to the same location (this causes exceptions) and since these output actions aren't having any effect either, we should not even pass these files to the `packager` in order to improve performance and fix exceptions like:
```
ERROR: /home/circleci/ng/src/lib/schematics/BUILD.bazel:34:1: SkylarkAction src/lib/schematics/npm_package failed (Exit 1)
Error: EEXIST: file already exists, mkdir …
```
> fix(npm_package): do not write external dep files to same location

- DEVELOPING.md
Invalid design doc URL.
Fixed design doc URL.
> Update design doc URL

- internal/node/node_loader.js
Module roots resolution is the last one attempted, but also one of the cheapest.
Attempt module roots resolution before others.
On the particular case of `yarn bazel test //packages/core/test/render3` in https://github.com/angular/angular I observed a 25% smaller test time.
Similar improvements can be expected in other workspaces where there are also many modules built from source.
See https://github.com/angular/angular/issues/27425 for more information.
> Attempt module roots resolution before others

- .bazelci/presubmit.yml
- docs/BUILD.bazel
It depends on protobuf which is brittle
> exclude //docs from the //... pattern expansion

- internal/npm_install/generate_build_file.js
Fixes https://github.com/bazelbuild/rules_nodejs/issues/522
> Fix npm install unlink throw

- third_party/github.com/gjtorikian/isBinaryFile/BUILD.bazel
> Fix missing BUILD file in release

- README.md
> Update README.md; fix typo

- internal/e2e/rollup/foo.js
- internal/rollup/package.json
- internal/rollup/yarn.lock
We now tree-shake @PURE-annotated code.
thanks @filipesilva
> Update rollup_bundle dependencies

- WORKSPACE
- package.bzl
Updating the pin to bazel-toolchains to enable use of new features related to BuildKite CI execution for platform rbe_ubuntu16_04. Change should have no functional impact. Change will make it easier for this repo to update to newer Bazel versions in the future.
fyi @alexeagle
> Update bazel toolchains pin and add toolchain config target

- packages/typescript/package.json
- packages/typescript/yarn.lock
These should only be in @bazel/karma package
> Remove @bazel/typescript deps on jasmine/karma

- internal/common/devmode_js_sources.bzl
- internal/common/node_module_info.bzl
- internal/common/sources_aspect.bzl
The comments were copied from `module_mappings.bzl` but they are unrelated
to the file in context.
> fix(docs): Remove unrelated module mappings comments

- packages/typescript/WORKSPACE
- packages/typescript/package.json
- packages/typescript/yarn.lock
> Update to latest rules_typescript

- e2e/karma_typescript/WORKSPACE
> fix(e2e/karma): workspace name should be e2e_karma_typescript

- packages/karma/package.json
At the moment jasmine-core and semver are listed both as dependencies and dev dependencies.
> build: remove duplicate dependencies

- WORKSPACE
- internal/e2e/fine_grained_deps/npm/package-lock.json
- internal/e2e/fine_grained_deps/npm/package.json
- internal/e2e/fine_grained_deps/yarn/package.json
- internal/e2e/fine_grained_deps/yarn/yarn.lock
This is part of pre-factoring for switching to user node_modules in yarn_install & npm_install (#655)
> Put @fine_grained_deps_yarn and @fine_grained_deps_npm package.json files in separate folders

- internal/rollup/package.json
- internal/rollup/rollup.config.js
- internal/rollup/yarn.lock
- package.json
- yarn.lock
> Update to rollup-plugin-node-resolve 4.2.0 and use new mainFields option

- e2e/bazel_bin/.bazelignore
- e2e/define_var/.bazelignore
- e2e/jasmine/.bazelignore
- e2e/karma/.bazelignore
- e2e/karma_stack_trace/.bazelignore
- e2e/karma_typescript/.bazelignore
- e2e/tsconfig_extends/.bazelignore
- e2e/typescript_2.7/.bazelignore
- e2e/typescript_2.8/.bazelignore
- e2e/typescript_2.9/.bazelignore
- e2e/typescript_3.0/.bazelignore
- e2e/typescript_3.1/.bazelignore
- examples/bazel_managed_deps/.bazelignore
- examples/parcel/.bazelignore
- examples/vendored_node/.bazelignore
- examples/web_testing/.bazelignore
- examples/webapp/.bazelignore
- packages/jasmine/.bazelignore
- packages/karma/.bazelignore
- packages/labs/.bazelignore
- packages/typescript/.bazelignore
> Add .bazelignore to nested workspaces

- internal/node/generate_build_file.js
- internal/npm_install/generate_build_file.js
- internal/npm_package/packager.js
- internal/web_package/assembler.js
> Cleanup mkdirp and unnecessary code in web_package/assembler.js

- internal/rollup/rollup.config.js
- internal/rollup/rollup.config.spec.js
- internal/rollup/rollup_bundle.bzl
Makes rollup code a little more readable
> Cleanup rollup bundle variable name

- packages/karma/karma.conf.js
> fix(karma): turn on Karma debug logging in DEBUG mode

- internal/npm_install/generate_build_file.js
> Fix duplicate deps in yarn_install & npm_install generated scope targets

- packages/karma/BUILD.bazel
- packages/karma/karma.conf.js
- packages/karma/package.json
- packages/karma/plugins.js
- packages/karma/yarn.lock
> fix(karma): Load karma-* dependencies from @bazel/karma

- packages/karma/package.json
- packages/karma/yarn.lock
This would make it consistent with the version of karma-jasmine
used in projects generated by the CLI.
https://github.com/angular/angular-cli/blob/master/packages/schematics/angular/workspace/files/package.json.template#L39
> feat(karma): bump karma-jasmine to v2

- packages/bazel-darwin_x64/LICENSE
- packages/bazel-darwin_x64/package.json
- packages/bazel-linux_x64/LICENSE
- packages/bazel-linux_x64/package.json
- packages/bazel-win32_x64/LICENSE
- packages/bazel-win32_x64/package.json
- packages/bazel/LICENSE
- packages/bazel/package.json
- packages/buildifier-darwin_x64/LICENSE
- packages/buildifier-linux_x64/LICENSE
- packages/buildifier/LICENSE
- packages/buildifier/package.json
This makes us work with https://www.npmjs.com/package/license-checker
> Add LICENSE files

- package.bzl
> Simplify versions in package.bzl for renovate

- examples/parcel/parcel.bzl
- internal/npm_package/npm_package.bzl
- internal/rollup/rollup_bundle.bzl
- packages/labs/webpack/src/webpack_bundle.bzl
> Add missing progress_message to actions

- package.bzl
Step 1 to reenable rbe_autoconfig on BuildKite CI. This is just updating a pin to bazel-toolchains should have no visible impact.
> update pin to bazel toolchains repo

- internal/rollup/BUILD.bazel
- internal/rollup/package.json
- internal/rollup/rollup.config.js
- internal/rollup/yarn.lock
- package.json
- yarn.lock
Issue Number: #626
`rollup-plugin-json` is added by default to the rollup config
> feat(rollup): add rollup-plugin-json

- internal/common/expand_into_runfiles.bzl
Issue Number: #461 
expand_path_into_runfiles handles the space separated string returned from `expand_location` when using `$(locations)`
We currently apply this patch via the WORKSPACE, we'd like to open source some of our internal rules that depend on rules_nodejs which make use of `$(locations)` in the templated args.
Can add tests if someone can point me to an example of testing these types of changes.
> Handle $(locations) in expand_path_into_runfiles

- packages/jasmine/package.json
- packages/jasmine/yarn.lock
fixes https://github.com/bazelbuild/rules_nodejs/issues/748
> update dependency to v8-coverage@1.0.9

- examples/program/BUILD.bazel
- package.json
- yarn.lock
> Update to bazel 0.25.1

- packages/buildozer-darwin_x64/LICENSE
- packages/buildozer-darwin_x64/package.json
- packages/buildozer-linux_x64/LICENSE
- packages/buildozer-linux_x64/package.json
- packages/buildozer-win32_x64/LICENSE
- packages/buildozer-win32_x64/package.json
- packages/buildozer/LICENSE
- packages/buildozer/buildozer.js
- packages/buildozer/package.json
- scripts/mirror_buildtools.sh
> Add buildozer package mirroring

- packages/typescript/package.json
- scripts/packages.sh
Must have been a inflight conflict between two PRs that broke master. This fixes it.
> Fix typescript package dependency on jasmine package

- .bazelci/presubmit.yml
- .bazelignore
- .bazelrc
- .gitignore
- BUILD.bazel
- WORKSPACE
- common.bazelrc
- e2e/ts_devserver/protractor.conf.js
- e2e/ts_library/foobar/tsconfig-foo.json
- examples/app/protractor.conf.js
- examples/protocol_buffers/protractor.conf.js
- examples/protocol_buffers/tsconfig.json
- package.bzl
- package.json
- packages/create/BUILD.bazel
- packages/create/README.md
- packages/create/index.js
- packages/create/package.json
- packages/create/test.js
- scripts/on-release.js
- scripts/publish_release.sh
- yarn.lock
This gives us an even simpler novice user on-ramp to create a Bazel/npm project
> Introduce @bazel/create package

- package.json
> feat: move to husky hook

- README.md
- common.bazelrc
> Include managed_directories in README

- scripts/setup_examples_angular.sh
In examples/angular integration test
> build: switch back to angular-bazel-example master

- .bazelci/presubmit.yml
- .circleci/config.yml
- common.bazelrc
- package.json
- packages/typescript/.bazelrc
- packages/typescript/BUILD.bazel
- packages/typescript/index.bzl
- packages/typescript/yarn.lock
- yarn.lock
Replaces https://github.com/bazelbuild/rules_nodejs/pull/861
> Update to Bazel 0.27.0rc5

- README.md
> docs(readme): add evertz to organization list

- README.md
> Add dataform to adopters section

- .bazelrc
- WORKSPACE
- internal/npm_install/npm_umd_bundle.bzl
- scripts/vendor_browserify.sh
- third_party/github.com/bazelbuild/bazel-toolchains/bazelrc/.bazelrc.notoolchain
- third_party/github.com/bazelbuild/bazel-toolchains/bazelrc/bazel-0.28.0.bazelrc
- third_party/github.com/browserify/browserify/main.js
Previously I marked the action local:1 but this masked a real failure in downstream project
> fix(builtin): process/browser should resolve from browserify

- README.md
> Add Webdox to the adopters list

- .bazelrc
- scripts/publish_release.sh
> chore: use bazel query to list release artifacts

- package.json
- yarn.lock
> chore: update to latest @bazel deps

- .bazelrc
> chore: add flaky_test_attempts

- .bazelrc
- WORKSPACE
- package.bzl
> Enable --incompatible_disable_legacy_proto_provider.

- packages/typescript/src/internal/ts_config.bzl
- packages/typescript/test/tsconfig_extends/BUILD.bazel
- packages/typescript/test/tsconfig_extends/tsconfig-base.json
- packages/typescript/test/tsconfig_extends/tsconfig-root.json
Fixes underlying issue of build failures in https://github.com/angular/angular/pull/31943
> Fix tsconfig deps sandbox bug

- WORKSPACE
- commitlint.config.js
- examples/BUILD.bazel
- examples/worker/.bazelrc
- examples/worker/BUILD.bazel
- examples/worker/README.md
- examples/worker/WORKSPACE
- examples/worker/foo.js
- examples/worker/package.json
- examples/worker/tool.js
- examples/worker/uses_workers.bzl
- packages/index.bzl
- packages/worker/BUILD.bazel
- packages/worker/README.md
- packages/worker/package.json
Requested by @nex3 in https://github.com/bazelbuild/rules_sass/pull/93
> feat(worker): new worker package

- packages/typescript/docs/install.md
Motivated by https://github.com/bazelbuild/rules_typescript/issues/314#issuecomment-520619564
/cc @JaredNeil
> docs(typescript): document how to increase heap

- rules_webtesting.patch
> refactor: remove commit message from rules_webtesting.patch

- common.bazelrc
> fix(builtin): --nolegacy_external_runfiles on build

- defs.bzl
- examples/app/protractor.on-prepare.js
- examples/protocol_buffers/protractor.on-prepare.js
- index.for_docs.bzl
- internal/common/windows_utils.bzl
- internal/history-server/history_server.bzl
- internal/http-server/http_server.bzl
- internal/node/node.bzl
- internal/npm_install/test/bazel_bin_test.sh
- packages/protractor/test/protractor-2/on-prepare.js
- packages/protractor/test/protractor-utils/index_test.ts
- packages/typescript/test/some_module/module_load_test.sh
> refactor: remove macros for nodejs_binary and nodejs_test

- docs/BUILD.bazel
- internal/node/node.bzl
> chore: cleanup docs formatting

- examples/angular/src/index.html
> Add links for video and slides from alex's talk at ng-conf

- CHANGELOG.md
- package.json
Links in the changelog currently point to Alex's fork which doesn't have the issues making them 404.
> Fix repository references in CHANGELOG.

- docs/index.md
> docs: index.bzl -> defs.bzl

- DEVELOPING.md
Follow up to https://github.com/bazelbuild/rules_nodejs/pull/1206
> docs: add update_nested_lock_files.sh step to release steps

- docs/TypeScript.md
- packages/typescript/docs/install.md
> fix(docs): fix typo in TypeScript.md

- scripts/clean_nested_workspaces.sh
Slightly wrong in the last fix
> fix: clean_nested_workspaces.sh

- packages/rollup/src/rollup_bundle.bzl
- packages/rollup/test/integration/foo/BUILD.bazel
- packages/rollup/test/integration/foo/index.ts
- packages/rollup/test/integration/golden.amd.js_
- packages/rollup/test/integration/golden.cjs.js_
- packages/rollup/test/integration/golden.esm.js_
- packages/rollup/test/integration/golden.iife.js_
- packages/rollup/test/integration/golden.system.js_
- packages/rollup/test/integration/golden.umd.js_
- packages/rollup/test/integration/rollup.config.js
> fix(rollup): rollup bundle transitive deps

- packages/terser/src/index.js
- packages/terser/src/terser_minified.bzl
- packages/terser/test/BUILD.bazel
- packages/terser/test/directory-args.spec.js
- packages/terser/test/directory_input/BUILD.bazel
- packages/terser/test/directory_input/spec.js
- packages/terser/test/exec/spec.js
- packages/terser/test/inline_sourcemap/spec.js
Issue Number: #1182
minified files do not link back to their source maps
minified files no link back to the source maps
> feat(terser): add source map links

- docs/_includes/drawer.html
> Slack channel is #javascript

- docs/_includes/drawer.html
> docs: add new rollup_bundle and terser_minified rules to docs nav

- e2e/webpack/package.json
- e2e/webpack/yarn.lock
- packages/labs/src/package.json
- packages/rollup/src/package.json
- packages/terser/src/package.json
Also some cleanup of some of the other peerDep definitions
> fix: webpack should be a peerDep of @bazel/labs

- renovate.json
This should get renovate making PRs for package.json deps. See https://docs.renovatebot.com/presets-config/ for more details on the presets.
> chore: update renovate to extend from new config:js-app

- package.bzl
> chore: cleanup unneeded io_bazel dep

- packages/rollup/src/index.from_src.bzl
> refactor(rollup): rollup index.from_src can just be a re-export of index as no overrides are needed

- docs/install.md
- internal/node/node_repositories.bzl
Also declare our intent to support latest LTS node
Fixes #1071
> chore: document newly added node/yarn versions

- docs/install.md
The example does not work.
The example works 🎉
N/A
> docs: fix multiple npm sets example

- packages/protractor/src/protractor_web_test.bzl
I ran into this when updating angular to nodejs rules 0.41.0 (https://github.com/angular/angular/pull/33996) in `modules/playground/e2e_test/sourcemap`:
```
filegroup(
name = "protractor_web_test_data_workaroud",
srcs = ["//modules/playground/src/sourcemap:index.ts"],
)
example_test(
name = "sourcemap",
srcs = glob(["**/*.ts"]),
data = [
"//modules/playground/src/sourcemap",
":protractor_web_test_data_workaroud",
],
server = "//modules/playground/src/sourcemap:devserver",
)
```
(where `example_test` is a macro and data is passed to `protractor_web_test`:
```
def example_test(name, srcs, server, data = [], **kwargs):
ts_library(
name = "%s_lib" % name,
testonly = True,
srcs = srcs,
tsconfig = "//modules/playground:tsconfig-e2e.json",
deps = [
"//modules/e2e_util", …
```
> fix: allow files in protractor data attribute

- .bazelrc
Fixes https://github.com/bazelbuild/rules_nodejs/issues/1394
Issue Number: https://github.com/bazelbuild/rules_nodejs/issues/1394
`bazel version` now succeeds.
> .bazelrc: Remove obsolete flag

- .bazelrc
Those opt-in incompatible changes have already been enabled in Bazel 1.0, those flags will be removed in future Bazel version.
> Remove incompatible flags

- examples/jest/WORKSPACE
These files were removed in #1385.
> chore: remove reference to patches for jest

- internal/npm_package/npm_package.bzl
> Remove local execution requirement for npm_package's create_package

- docs/Built-ins.md
- docs/TypeScript.md
- internal/npm_install/npm_umd_bundle.bzl
- internal/providers/node_runtime_deps_info.bzl
- packages/jasmine/src/index.bzl
- packages/jasmine/src/index.from_src.bzl
- packages/karma/src/index.bzl
- packages/karma/src/index.from_src.bzl
- packages/labs/src/index.bzl
- packages/protractor/src/index.bzl
- packages/protractor/src/index.from_src.bzl
- packages/rollup/src/index.from_src.bzl
- packages/terser/src/index.from_src.bzl
- packages/typescript/src/index.bzl
- packages/typescript/src/index.from_src.bzl
- toolchains/node/BUILD.tpl
- toolchains/node/node_toolchain.bzl
- toolchains/node/node_toolchain_configure.bzl
> Docs cleanup

- .bazelci/presubmit.yml
- docs/index.md
- internal/pkg_npm/packager.js
- internal/pkg_npm/pkg_npm.bzl
> fix(builtin): make .pack and .publish targets work again

- examples/BUILD.bazel
- examples/nestjs/package.json
- examples/nestjs/src/BUILD.bazel
- examples/nestjs/src/app.controller.ts
- examples/nestjs/src/main.spec.ts
- examples/nestjs/src/main.ts
- examples/nestjs/yarn.lock
Adds a test which boots up the Nestjs application and ensures that and api endpoint can be hit
> Examples nestjs test

- README.md
Adds our Organization to the list :)
> Update README.md to add our organization

- README.md
> chore: add protoc-gen-ts to open-source repositories list.

- internal/node/node_patches.js
- packages/node-patches/src/subprocess.ts
If `grep` is not in the path the launcher scripts don't fail, they just spam the console.
Substring checks are done with bash operators instead of shelling out to grep.
> Replace grep with bash's regex operator

- examples/BUILD.bazel
- examples/angular_bazel_architect/package.json
- examples/angular_bazel_architect/yarn.lock
> build: fix in-flight conflict with angular_bazel_architect example

- examples/angular/src/index.html
This PR updates the example link that pointed the visitors to [the old example](https://github.com/angular/angular-bazel-example) which has now moved [here](https://github.com/bazelbuild/rules_nodejs/tree/master/examples/angular)
The current [ABC Site](https://bazel.angular.io/) has an Example Link in the header that takes the visitors to the [Old Example](https://github.com/angular/angular-bazel-example) which has been archived.
Issue Number: https://github.com/angular/angular/issues/35261
The example link will now point the visitors to [the new example](https://github.com/bazelbuild/rules_nodejs/tree/master/examples/angular)
> docs(examples): update header example link

- .bazelrc
> chore: remove compat flags for rules_go and bazel 0.27

- internal/common/expand_variables.bzl
> fix: expand_variables helper should handle external labels

- examples/angular_bazel_architect/BUILD.bazel
> feat(examples): add serve to angular architect

- packages/jasmine/src/package.json
Updates jasmine to v3.5.0 for `@bazel/jasmine`.
> feat(@bazel/jasmine): update dependencies to jasmine v3.5.0

- internal/npm_install/npm_install.bzl
- [] Tests for the changes have been added (for bug fixes / features)
- [] Docs have been added / updated (for bug fixes / features)
Issue: #1678
- [] Yes
> fix: yarn cache path should be a string

- internal/node/node_repositories.bzl
- internal/npm_install/npm_install.bzl
Issue Number: #1641 
The build will work both from C and other drives
I've searched through the code and added the /D option to all places where cd is used through CMD.
https://ss64.com/nt/cd.html
> fix(npm_install) Add /D to all cmd CD calls, this makes CD change drive as well as directory

- docs/index.md
> fix: invalid link in index

- .github/BUILD.bazel
- .github/CODEOWNERS
- packages/labs/BUILD.bazel
- scripts/update_codeowners.sh
> chore: add mrmeku as labs owner (for protobuf)

- internal/node/node.bzl
> fix(builtin): entry point of a .tsx file is .js

- docs/index.md
This teaches you to use generated npm_package_bin rules rather than getting into details about writing custom rules with nodejs_binary
Fixes #1727
> docs: update docs entry point with better quickstart content

- internal/common/module_mappings.bzl
Pre-factored out of https://github.com/bazelbuild/rules_nodejs/pull/1715
> refactor: removed unused code in internal/common/module_mappings.bzl

- .github/BUILD.bazel
- .github/CODEOWNERS
- packages/labs/BUILD.bazel
- packages/rollup/BUILD.bazel
> chore: add jbedard as a @bazel/rollup codeowner

- docs/install.md
> fix(docs): syntax error in example code

- internal/node/node_repositories.bzl
> fix(docs): `yarn_urls` should be `string_list`, not `string`

- internal/node/node_repositories.bzl
Add new version of yarn
Support yarn 1.22.4 in `node_repositories`
Not sure what to do with below
> When adding a new version. please update /docs/install.md
> chore: add yarn 1.22.4 to node_repositories

- examples/BUILD.bazel
- examples/parcel/parcel.bzl
- internal/linker/index.js
- internal/linker/link_node_modules.ts
- internal/node/node_patches.js
- internal/npm_install/generate_build_file.ts
- internal/npm_install/index.js
- internal/npm_install/test/golden/@gregmagolan/test-a/bin/BUILD.bazel.golden
- internal/npm_install/test/golden/jasmine/bin/BUILD.bazel.golden
- internal/providers/node_runtime_deps_info.bzl
- packages/karma/src/karma.conf.js
- packages/karma/src/karma_web_test.bzl
- packages/karma/test/karma_typescript/user_files.spec.js
- packages/node-patches/src/subprocess.ts
- packages/terser/src/index.js
- packages/terser/src/terser_minified.bzl
> Hook up linker to all generated /bin:foo targets

- docs/TypeScript.md
- packages/typescript/install.md
> docs: rename typo 'vanillia' to 'vanilla'

- packages/typescript/install.md
> docs: fix example of using nodejs_binary for tsc_wrapped with self-managed deps

- docs/Protractor.md
- packages/karma/karma_web_test.bzl
- packages/protractor/protractor_web_test.bzl
Did you mean 'wrapper'?
I only fixed a typo error.
> (docs): fixed small error

- .bazelignore
- .github/BUILD.bazel
- .github/CODEOWNERS
- WORKSPACE
- commitlint.config.js
- packages/angular/BUILD.bazel
- packages/angular/README.md
- packages/angular/package-lock.json
- packages/angular/package.json
- packages/angular/src/builders/builders.json
- packages/angular/src/builders/index.ts
- packages/angular/src/builders/schema.d.ts
- packages/angular/src/builders/schema.json
- packages/angular/tsconfig.json
- packages/angular/types.d.ts
This replaces the one being removed in https://github.com/angular/angular/pull/37190
/cc @alan-agius4 @kyliau
> feat(angular): introduce an Angular CLI builder

- packages/protractor/protractor_web_test.bzl
The Label constructor converts a string to a label in the containing workspace, rather than the caller
So we don't need users to tell us what the @npm workspace is named
I learned from https://groups.google.com/d/msg/bazel-discuss/qNuyIu-akq8/6NvlxADxBAAJ which also demonstrates how confusing it is, since Dmitry had it backwards
> chore: cleanup protractor macro

- packages/typescript/internal/ts_project.bzl
> feat(typescript): include label in the ts_project progress message

- e2e/bazel_managed_deps/package.json
- e2e/bazel_managed_deps/yarn.lock
- e2e/jasmine/package.json
- e2e/jasmine/yarn.lock
- e2e/typescript/package.json
- e2e/typescript/yarn.lock
- examples/kotlin/package.json
- examples/nestjs/package.json
- examples/nestjs/yarn.lock
- examples/parcel/package-lock.json
- examples/vendored_node/package.json
- examples/vendored_node_and_yarn/package.json
- examples/vendored_node_and_yarn/yarn.lock
- packages/jasmine/package.json
addresses https://github.com/bazelbuild/rules_nodejs/issues/1702
> feat(jasmine): make deps peerDeps

- README.md
> chore(docs): add testimonial from Allocadia

- internal/pkg_npm/test/directory/BUILD.bazel
- internal/pkg_npm/test/directory/generate.bzl
- internal/pkg_npm/test/directory/main.js
- internal/pkg_npm/test/directory/package.json
Issue Number: #1989
This purely adds tests to demo that #1989 was false alarm
> test(typescript): add directory test for pkg_npm, fix #1989

- packages/typescript/internal/ts_project.bzl
- packages/typescript/test/ts_project/output_group/BUILD.bazel
- packages/typescript/test/ts_project/output_group/index.golden.d.ts
- packages/typescript/test/ts_project/output_group/index.ts
- packages/typescript/test/ts_project/output_group/tsconfig.json
> feat(typescript): add OutputGroupInfo to ts_project with type definitions

- internal/common/check_bazel_version.bzl
> chore: stop reporting custom bazel build version

- .github/stale.yml
Keep our issues tidy without controversy !
> chore: add config for https://github.com/apps/stale

- examples/create-react-app/BUILD.bazel
> fix(examples): fix test file pattern of create react app example

- packages/labs/package.bzl
> fix(lab): remove duplicate grpc_web import attempts

- packages/rollup/index.js
This was one of the main reasons for updating the minimum rollup version to [2.3.0](https://github.com/rollup/rollup/blob/master/CHANGELOG.md#230).
I hope there's more rollup APIs we can use to avoid duplicating the rollup CLI stuff within the worker but this is a good start.
> refactor(rollup): use rollup loadConfigFile API

- packages/typescript/internal/ts_project.bzl
- packages/typescript/test/ts_project/json/BUILD.bazel
- packages/typescript/test/ts_project/json/baz.svg
> fix(typescript): only expect .js outs for .tsx? srcs

- docs/BUILD.bazel
- docs/Built-ins.html
- docs/Cypress.html
- docs/Jasmine.html
- docs/Karma.html
- docs/Protractor.html
- docs/Rollup.html
- docs/Terser.html
- docs/TypeScript.html
- docs/_includes/footer-content.html
- docs/_includes/header.html
- docs/_includes/sidenav.html
- docs/_layouts/search.html
- docs/changing-rules.html
- docs/debugging.html
- docs/dependencies.html
- docs/examples.html
- docs/index.html
- docs/install.html
- docs/repositories.html
- docs/search.html
- docs/search.md
- docs/stamping.html
- tools/stardoc/jekyll.bzl
Adds simple search functionality to the docsite using gcse. 
Updated here: https://mattem.github.io/rules_nodejs/
closes #1282
> docs: add search to docsite using gcse

- docs/stamping.md
- internal/npm_version_check.js
- internal/pkg_npm/packager.js
- internal/pkg_npm/pkg_npm.bzl
- packages/rollup/install.md
- packages/rollup/rollup_bundle.bzl
- packages/rollup/test/integration/rollup.config.js
- packages/rollup/test/version_stamp/rollup.config.js
> feat(builtin): accept any stamp vars in pkg_npm

- e2e/coverage/BUILD.bazel
- e2e/coverage/fail.spec.js
- internal/node/launcher.sh
> Fix exit code of tests when coverage is enabled

- README.md
cherry-pick of 16f0c0ef7a9ce3f2ff7c39d25f02f39fc7fd2338 that was merged to master
> docs: add spica to adopter organization list

- examples/angular_bazel_architect/BUILD.bazel
- examples/angular_bazel_architect/package.json
It can get ahead of the Chrome version on our CI machine
> ci: tell Angular CLI not to update webdriver

- packages/karma/index.ts
When the Karma plugin is used in a testing environment that enforces
[Trusted Types](https://web.dev/trusted-types/), its loadFile functionality currently fails due to a
Trusted Types violation when assigning to script.textContent. This makes
it impossible to use the plugin with integration tests that ensure an
application is compatible with Trusted Types.
This is fixed by creating a Trusted Types policy specifically for the
Karma plugin, and use it to promote any loaded scripts to a TrustedScript
before assigning to script.textContent. This is done in a way that is
backwards compatible:
- The policy is `null` in browsers that don't yet support Trusted Types,
in which case the original script string is used as before.
- When Trusted Types are supported in the browser but not enforced by …
> feat(karma): use Trusted Types policy when loading scripts for Karma

- internal/js_library/js_library.bzl
If providing DeclarationInfo we should also give this way for filegroup/bazel CLI to select them
> fix(builtin): js_library supports --output_groups=types

- packages/typescript/internal/ts_project.bzl
Tested by building //packages/angular:npm_package and don't get an extra .d.ts file in the package.
Also tested the negative case by making an invalid option and check that it's still reported.
Fixes #2078
> fix(typescript): don't include _valid_options marker file in outs

- examples/nestjs/src/BUILD.bazel
> fix(exmaples/nestjs): add module_name field in ts_library

- internal/node/node_versions.bzl
- scripts/update-nodejs-versions.js
Ran the update-nodejs-versions script and committed the changes.
> Update nodejs versions

- docs/install.md
Current link returns 404, it seems that the url was somehow changed to .html from .md.
> fix a link

- internal/pkg_web/pkg_web.bzl
pkg_web#move_files helper is now a private API
> refactor: make pkg_web#move_files private

- packages/concatjs/_README.md
> docs: mention __umd targets in concatjs readme

- packages/typescript/internal/ts_project.bzl
> docs(typescript): link some user-contributed doc

- docs/changing-rules.md
This will help people find the relevant documentation for the
patches attribute.
N/A
> docs: add link to http_archive attributes docs

- internal/coverage/lcov_merger-js.js
- internal/coverage/lcov_merger.ts
Fixes https://github.com/bazelbuild/rules_nodejs/issues/2376
> fix(builtin): fix coverage source file paths

- internal/coverage/lcov_merger-js.js
- internal/coverage/lcov_merger.ts
- package.json
- packages/jasmine/package.json
- packages/jasmine/test/BUILD.bazel
- packages/jasmine/test/coverage_source_uncovered.ts
- yarn.lock
fixes https://github.com/bazelbuild/rules_nodejs/issues/2377
> feat(builtin): add coverage all: true support

- internal/node/node_versions.bzl
> fix: update node versions map

- README.md
> Add Domino Data Lab as rules_nodejs adopter

- examples/angular/WORKSPACE
- examples/nestjs/WORKSPACE
renovate-bot did most of the work here.
> chore: bump rules_docker to v0.16.0

- examples/BUILD.bazel
- packages/esbuild/esbuild.bzl
- packages/esbuild/test/css/BUILD.bazel
Also fixes some formatting issues
> build: disable examples_protobufjs on windows

- DEVELOPING.md
- docs/install.md
The changes in DEVELOPING.md address some of the confusion I had when I first started using these rules
> documentation updates

- packages/esbuild/esbuild.bzl
The stated default is wrong atm...
> fix(esbuild): correct rule argument documentation stating default target

- packages/concatjs/_README.md
> docs: explain how to produce named UMD from TS

- internal/pkg_web/pkg_web.bzl
Adds additional note that the array digested is relative to the root of the repo
> docs: update additional_root_path docs

- examples/esbuild/WORKSPACE
- packages/esbuild/_README.md
- packages/esbuild/esbuild_repo.bzl
Bumps the esbuild version used for tests 🤖
> chore(esbuild): bump esbuild versions used

- internal/pkg_npm/pkg_npm.bzl
- internal/pkg_npm/test/pkg_npm.spec.js
Issue Number: #2647 
An attribute has been added that allows generating ESM files.
> feat(builtin): allow bundling ESM output with the pkg_npm rule

- internal/node/launcher.sh
- internal/node/test/chdir/BUILD.bazel
- internal/node/test/chdir/cp.js
> fix(builtin): write stdout/stderr to correct path under chdir

- internal/npm_install/npm_install.bzl
In general you cannot rely on mkdir and cp being in path here and this
below up for us on CI. Given that this is a repository rule you also
cannot rely on something like rules_posix to resolve them otherwise so
this PR hacks around this in a rather crude but working way.
rules_nodejs fails on Windows if msys mkdir or cp are not in path.
No dependency on msys.
> Fix copy_file on Windows

- WORKSPACE
- npm_deps.bzl
> refactor: move yarn_install & npm_install calls to npm_deps.bzl

- packages/terser/index.js
Bug fix.
Pre-factor to https://github.com/bazelbuild/rules_nodejs/pull/2698 which has a side-effect of changing symlinks and resulting in `terser` resolving inside `packages/terser/...runfiles/.../node_modules/terser/...` where there are two `/terser/` segments.
> fix(terser): make terser resolve more robust by not assuming a single /terser/ segment in the path

- e2e/concatjs_devserver/package.json
- e2e/concatjs_devserver/yarn.lock
- e2e/fine_grained_symlinks/WORKSPACE
- e2e/fine_grained_symlinks/package.json
- e2e/fine_grained_symlinks/yarn.lock
Resolves dependency warnings from `y18n`
Closes #2641
> chore: update dependencies to resolve y18n security warning

- WORKSPACE
- internal/pkg_npm/test/BUILD.bazel
- tools/fine_grained_deps_npm/package-lock.json
- tools/fine_grained_deps_npm/package.json
Use a newer version of NodeJS, lets see what happens
> chore: update nodejs version used

- docs/esbuild.md
- internal/common/expand_variables.bzl
- packages/esbuild/esbuild.bzl
- packages/esbuild/helpers.bzl
- packages/esbuild/launcher.js
- packages/esbuild/test/define/BUILD.bazel
- packages/esbuild/test/define/bundle_test.js
- packages/esbuild/test/define/esbuild.config.mjs
- packages/esbuild/test/define/main.ts
Needs https://github.com/bazelbuild/rules_nodejs/pull/2840
closes #2812
> feat(esbuild): support stamping via config file

- docs/Built-ins.md
- internal/node/node_repositories.bzl
> chore: update defaults to latest node/yarn versions

- docs/Built-ins.md
- internal/npm_install/npm_install.bzl
> docs: improve documentation for symlink_node_modules

- packages/worker/src/worker.ts
Issue Number: https://github.com/bazelbuild/rules_nodejs/issues/2953
Check if the input digest is present.
> fix(worker): check if the input digest present

- examples/angular/README.md
Currently the `README.md` in `examples/angular` has some issues:
* Codeblocks included regular text
* Some commands are not wrapped in codeblocks
* Level 1 headings are used where not needed
Apply some markdown best practices:
* Narrowed codeblocks to commands
* set missing `bash` codetype to blocks
* Set one sentence per line
* Set bold text where level 1 headings were used
* some small (cosmetic) improvements
[Preview](https://github.com/mgred/rules_nodejs/tree/fix-angular-example-readme/examples/angular#readme)
> docs(examples): fix formatting issues in angular/README.md

- BUILD.bazel
- internal/generated_file_test/BUILD.bazel
- internal/linker/BUILD.bazel
Issue Number: https://github.com/bazelbuild/rules_nodejs/issues/3030
This fixes broken behavior in the release tarball where users are no longer able to generate docs using stardoc.
> fix(builtin): fixed missing dist targets

- examples/angular/README.md
> Fix incorrect link to managed dependencies

- examples/angular/README.md
This is the same as https://github.com/bazelbuild/rules_nodejs/pull/3072 but merging to the `stable` branch now.
Link is invalid
Link is valid
> Fix link to managed dependencies

- scripts/update-nodejs-versions.js
The hope here is that the cron job that updates node versions would now pick up node `17.*`.
> chore: increase max node version to 17.*

- docs/Cypress.md
- packages/cypress/index.bzl
> docs: fix typo in cypress load statement

- nodejs/extensions.bzl
- nodejs/repositories.bzl
Replaces the patch file needed to land https://github.com/bazelbuild/bazel-central-registry/pull/39
> feat: add bzlmod extension

- docs/Built-ins.md
- docs/Cypress.md
- internal/node/node.bzl
- internal/node/test/BUILD.bazel
node and toolchains were used
only toolchain is needed
> fix(): remove node and use toolchain

- .github/CODEOWNERS
- BUILD.bazel
We haven't heard from him in a couple years
> chore: remove soldair from codeowners

- .bazelrc
- .circleci/bazel.rc
- internal/bazel_integration_test/bazel_integration_test.bzl
Smaller footprint version of https://github.com/bazelbuild/rules_nodejs/pull/3202
> chore: add --incompatible_exclusive_test_sandboxed to common and --keep_going for CircleCI

- internal/node/node.bzl
- internal/providers/node_runtime_deps_info.bzl
With `exports_directories_only` all 3rd party deps are now linked npm deps. 
This fixes an issue where npm deps that are dynamically linked (not in the deps of a binary target) from non-root package_path in yarn_install and npm_install do not have their package_path added to `BAZEL_NODE_MODULES_ROOTS`. `BAZEL_NODE_MODULES_ROOTS` is used to generated the list of patch roots for symlink escape protection. TL;DR is this fix ensures that all linked node_modules folders are guarded from symlink escapes.
> fix: guard node_modules roots for dynamic multi-linked npm deps

- internal/node/node.bzl
- packages/cypress/internal/cypress_web_test.bzl
> fix(cypress): use depsets for runfiles and data

- docs/dependencies.md
It appears that the yarn binary is available at `@yarn//:yarn`.
> Update doc for executing the Bazel fetched yarn

- examples/jest/BUILD.bazel
- examples/jest/jest.config.js
- examples/jest/jest.ts.config.js
- examples/jest/package.json
- examples/jest/ts/test/BUILD.bazel
- examples/jest/yarn.lock
Add junit reporter for jest example as bazel standard test runner
Add an example of outputting bazel xml test reports from jest test runner 
No example of how to output XML reports
An example is present on how to output jest junit reports
> feat(examples): example jest add junit reporter

- docs/TypeScript.md
Adjust the link to the official typescript tsconfig.json documentation.
The existing link doesn't work anymore.
> chore(docs): update tsconfig link for ts_project documentation

- README.md
- New adopter org added to the adopters section in README
> Add FasterCI to adopters

- .fasterci/config.yaml
stable branch will be built on [FasterCI](https://fasterci.com) when updated
This PR contains a build configuration. To enable the fasterci build this repo should install the [fasterci github app](https://github.com/apps/faster-ci/installations/new)
> FasterCI build

- e2e/nodejs_image/BUILD.bazel
- e2e/nodejs_image/WORKSPACE
- e2e/nodejs_image/foolib/index.js
- e2e/nodejs_image/main.js
- e2e/nodejs_image/nodejs_image.yaml
- e2e/nodejs_image/package.json
- e2e/nodejs_image/yarn.lock
Based on https://github.com/slamdev/bazel-showcase-node-native-deps/commit/7d5efcbf15fde232cf69999f90f7179f5d407e54 - thanks @slamdev
> test: demonstrate a native package in docker

- .fasterci/config.yaml
> run fasterci on pull requests

- packages/typescript/internal/worker/index.js
- packages/typescript/internal/worker/worker_adapter.ts
> Backport ts worker fix

- nodejs/private/ts_project_options_validator.js
- packages/typescript/internal/ts_project_options_validator.ts
The path to the program was absolute, and isn't useful.
Fixes #3461
> fix: deterministic output from ts_options_validator

- README.md
> Add Code Intelligence to list of adopters

- README.md
Bazel files seems removed. 
https://github.com/ngrx/platform/pull/3406 
> fix: delete ngrx from README. Currently not used

- nodejs/extensions.bzl
- nodejs/repositories.bzl
Addresses https://github.com/aspect-build/rules_js/issues/864.
> fix: allow root repositories to override node toolchain version under bzlmod

- docs/Core.md
> chore: fix failing docs test

- docs/install.md
> Fix `node_repositories` load path in docs/install.md (index.bzl no longer exists)

- .bazelrc
Follow up https://github.com/bazelbuild/rules_nodejs/pull/3696
> Fix issue link

- .bazelci/presubmit.yml
- .bcr/presubmit.yml
- e2e/nodejs_host/BUILD.bazel
- e2e/smoke/BUILD.bazel
- nodejs/repositories.bzl
Adds a few test cases that were missing too
> chore: cleanup test targets

- nodejs/repositories.bzl
Note: The term "known" (as opposed to supported) is deliberate to avoid giving the impression that the version is "supported" by rules_nodejs any more than having the SHA on file.
Closes #3765
Issue Number: #3765
> feat: expose latest known node version

- .bazelrc
- .bcr/metadata.template.json
- .github/workflows/release_prep.sh
- .github/workflows/update-nodejs-versions.yml
- MODULE.bazel
- README.md
- docs/changing-rules.md
- docs/index.md
- e2e/nodejs_host/MODULE.bazel
- package.json
- packages/runfiles/package.json
Link points to a page that does not exist, i.e. https://bazelbuild.github.io/rules_nodejs/ which gives a 404 error.
Link points to the page hosting the documentation, i.e. https://bazel-contrib.github.io/rules_nodejs/
> fix link to documentation in README.md

- .bazelrc
Fixes https://github.com/bazel-contrib/rules_nodejs/issues/3779
> Explicitly enable workspace

- .github/workflows/publish.yaml
- .github/workflows/release.yml
Followed instructions from https://github.com/bazel-contrib/publish-to-bcr
and used rules_lint as a guide.
> chore(release): setup new publish-to-bcr

- docs/Core.md
- e2e/headers/BUILD.bazel
- nodejs/private/current_node_cc_headers.bzl
- nodejs/repositories.bzl
- package.json
Goal is to match github actions `ubuntu-latest` https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
> feat: change nodejs default to 20
