- internal/node.bzl
`set` is deprecated and will no longer be supported.
> Rename set to depset

- .circleci/config.yml
- defs.bzl
- internal/BUILD.bazel
- internal/check_bazel_version.bzl
- internal/check_bazel_version_test.py
- internal/node_install.bzl
Downstream repos (eg. typescript, Angular) may have their own minimal version constraint,
so expose a function they can use.
> Add a check for minimum bazel version.

- internal/node_loader.js
If we're on linux or macos, symlinks work, so we don't need to use the runfiles manifest.  Therefore, if the runfiles directory exists, we can ignore the runfiles manifest.
> Only use the runfiles manifest on windows.

- internal/node_loader.js
`resolveRunfiles([ 'karma', '', 'node_modules', 'karma/bin/karma' ])` was looking for `'karma//node_modules/karma/bin/karma'`, which is not a valid path.
See also alexeagle/rules_karma#3.  This doesn't fix that, but it makes progress.
> Remove empty path segments before looking up runfile in manifest

- .circleci/config.yml
- WORKSPACE
- examples/program/BUILD.bazel
- internal/node.bzl
We should be able to test jasmine targets under a different (possibly nested) workspace.
Also remove awkward subtraction patterns, by declaring the examples/program as a workspace
in the root WORKSPACE file.
Note the WORKSPACE files now have a cyclical dependency, but this is fine.
> Add test for previous commit.

- internal/jasmine_node_test.bzl
'+=' for lists now mutates the lhs list instead of creating a new one and assigning to lhs (https://docs.bazel.build/versions/master/skylark/backward-compatibility.html#mutating).
This is a fix for https://ci.bazel.io/blue/organizations/jenkins/Global%2Frules_nodejs/detail/rules_nodejs/56/pipeline/
> Fix += for lists in jasmine_node_test

- internal/node.bzl
- internal/node_loader.js
This reverts commit 6b9979b5c1b7f213acdfcf29fa258f76be1ec055.
The idea here is misguided, it depends on how the package manager
lays out the node_modules.
Just because @bazel/typescript depends on typescript doesn't mean
we can find node_modules/@bazel/typescript/node_modules/typescript/...
(relative to node_modules/@bazel/typescript/WORKSPACE)
because the user might also depend on typescript at the same
version, and there will only be
node_modules/typescript
(not under the @build_bazel_rules_typescript workspace)
> Revert "Add documentation clarifying which node_modules are used"

- internal/node.bzl
This makes it work with ibazel again
> the nodejs_* macros should forward tags onto the sh_* target

- internal/node_loader.js
Try looking in the directory containing the label first, before the one in the working directory.
Needed for tsickle tests to use a different TypeScript version in one test, and probably generally useful.
> Change node module load order

- internal/node_loader.js
This reverts commit ebbad65504cd0a0007987b6adce3b77a8a898ee8.
It is no longer needed for the original purpose (tsickle testing)
and it broke something else downstream in the karma rules.
Before rolling this forward again, I need to have a CI for
downstream projects, and also understand the module resolution
more deeply.
> Revert "Change node module load order"

- internal/check_bazel_version.bzl
- internal/check_bazel_version_test.py
> Handle version that looks like "x.x.xrcx" in check_bazel_version.bzl

- internal/jasmine_runner.js
This fixes stack traces to have `.ts` references.
Since we are in rules_nodejs here, we don't ship to npm, so we can't include npm dependencies. Anyway if the user writes pure JavaScript they don't need this installed.
> Jasmine test: source-map-support if present

- internal/jasmine_node_test.bzl
- internal/jasmine_runner.js
Previously we only gave an error when there were no files at all.
Also due to a typo, if we ever did hit that case we'd just crash.
fixes #64
> jasmine_node_test: empty srcs; fix no-spec case

- internal/rollup/rollup.config.js
path.join catches instances of ./ and ../ in the importee and resolves
them correctly. Previously, importers could potentially grow too large
over time due to repetitive sequences of ./ and ../<package>, resulting
in ENAMETOOLONG errors.
Example error fixed with this change: 
```ENAMETOOLONG: name too long, open '[workspace_root]/node_modules/@firebase/firestore/dist/esm/./src/platform_browser/../platform/../util/./../platform/../util/./../platform/../util/./../platform/../util/./../platform/../util/./../platform/../util/./../platform/../util/./../platform/../util/./../platform/../util/./../platform/../util/./../platform/../util/./../platform/../util/./../platform/../util/./../platform/../util/./../platform/../util/./../platform/../util/./../platform/../util/./../platform/../util/./../plat …
```
> Fix rollup_bundle issue with resolved paths growing too large

- internal/collect_es6_sources.bzl
- internal/e2e/rollup/BUILD.bazel
- internal/e2e/rollup/foo.js
- internal/e2e/rollup/package.json
- internal/e2e/rollup/rollup.spec.js
- internal/e2e/rollup/yarn.lock
- internal/jasmine_runner.js
- internal/js_library.bzl
- internal/rollup/BUILD.bazel
- internal/rollup/package.json
- internal/rollup/rollup.config.js
- internal/rollup/rollup.config.spec.js
- internal/rollup/rollup_bundle.bzl
- internal/rollup/uglify.config.json
For es6, we currently have this clumsy thing:
https://github.com/bazelbuild/rules_nodejs/blob/master/internal/collect_es6_sources.bzl#L52
that flattens the re-rooted directories from all the libraries in the transitive closure.
The more performant thing is just to update the module resolution to understand a `rootDirs` option, just like TypeScript does.
It turns out Angular's optimizer doesn't work with ES6, so I need to create another flavor, es5_esm. This refactoring allows Angular to re-use the rollup rule, but pass in that output instead, and leave it in the original roots.
> Allow sources to be in multiple root dirs

- internal/node.bzl
Unless the nodejs_binary has `templated_args=["--node_options=--nopreserve-symlinks"]` to disable it
Fixes #109
> Turn on node option --preserve-symlinks

- internal/npm_install/npm_install.bzl
- internal/yarn_install.bzl
Found these while switching the Angular repo over to this pattern.
> Add more exclusions for generated :node_modules glob

- internal/rollup/rollup.config.js
- internal/rollup/rollup.config.spec.js
- the tests were not running because of an fit, and some were broken at head :(
- I changed re-rooting to look like execroot, so it uses external/wksp
- handle the case of a relative import across roots
> fix rollup module resolution

- .bazelci/presubmit.yml
Our Buildkite CI has working Windows agents now, so do you want to give this a try?
Do you need anything installed on the Windows machines (e.g. nodejs)?
(FYI @buchgr)
> Add Windows to .bazelci/presubmit.yml.

- README.md
- internal/npm_package/npm_package.bzl
- internal/npm_package/packager.js
This is needed to produce the `@angular/bazel` package.
Also add missing docs to the README
> Add replacements feature to npm_package

- README.md
- internal/e2e/rollup/versions.txt
- internal/npm_package/npm_package.bzl
- internal/npm_package/packager.js
This is needed to produce the `@angular/bazel` package.
Also add missing stamping docs to the README
> Add version stamping to npm_package

- internal/npm_package/npm_package.bzl
- internal/npm_package/packager.js
- internal/npm_package/test/BUILD.bazel
- internal/npm_package/test/dependent_file
- internal/npm_package/test/npm_package.spec.js
- internal/npm_package/test/some_file
this allows ng_package rule to be a macro composing some special packaging with a regular npm_package, reducing duplication
> Add ability for npm_package to include other npm_package's

- internal/e2e/node/jasmine_node_test.spec.js
- internal/jasmine_node_test/jasmine_runner.js
By default V8 only captures 10 stack frames. This makes debugging hard
and most developers don’t know how to get more stack frames to show up.
Since this is for running tests, the penalty of slower stack capture 
is more than offset by better debugging experience.
> Capture all stack frames in tests

- README.md
- internal/e2e/rollup/BUILD.bazel
- internal/e2e/rollup/versions.txt
- internal/npm_package/npm_package.bzl
- internal/rollup/rollup_bundle.bzl
- tools/bazel.rc
Fixes #156
See discussion in https://github.com/bazelbuild/bazel/issues/4842
and this fix is based on https://github.com/bazelbuild/bazel/issues/1054#issuecomment-219151351
> Use ctx.version_file in place of a genrule with stamp=True

- internal/rollup/rollup.config.js
- internal/rollup/rollup.config.spec.js
- internal/rollup/rollup_bundle.bzl
The following patch fixes an issue where bazel is undefined during build. This is due to rootDir not being escaped which is allowing node to interpolate the string path as variables.
#180
> Fix(rollup): escape rootDir path (fixes #180)

- internal/node/node.bzl
This fixes `//internal/npm_package/test:test` when preserve-symlinks is turned on
> Ensure "files" from data attribute of nodejs_binary rule make it into runfiles

- internal/rollup/package.json
- internal/rollup/rollup.config.js
- internal/rollup/yarn.lock
- internal/test/package.json
- internal/test/yarn.lock
Not sure how I missed this but it is needed along with the resolve check in rollup.
> Allow built-in modules to resolve in rollup

- internal/e2e/rollup/bundle-umd_golden.js_
- internal/rollup/package.json
- internal/rollup/yarn.lock
This PR fixes compatibility with `ts_proto_library` which uses `protobufjs` under the covers. `protobufjs` is affected by this rollup issue: https://github.com/rollup/rollup/issues/1859 . That issue is fixed in upstream releases so I upgraded all rollup packages to their latest release.
> fix(rollup_bundle): Upgrade rollup packages for compatibility

- internal/node/node.bzl
The nodejs_test macro uses a sh_test wrapper around an internal `%s_bin` target.
However this target is not tagged as "manual" and thus will get matched by
target wildcard, e.g.: `bazel test //...` would run the same test twice
(and probably fail on windows, since that's the documented rationale for having the sh_test
wrapper in the first place).
> Mark _bin test target in test macro as manual

- internal/common/module_mappings.bzl
- internal/e2e/node/BUILD.bazel
- internal/e2e/node/lib1/BUILD.bazel
- internal/e2e/node/lib1/src/index.js
- internal/e2e/node/lib1/src/some.js
- internal/e2e/node/module_resolution.spec.js
This allows libraries to have a nested structure where the index file is in a subdirectory of the package where the js_library/ts_library rule is declared.
Fixes #220
> Handle .d.ts module roots in nodejs loader

- defs.bzl
- internal/node/node.bzl
Some updates to rollup needed for authoring protractor rule
Set `nodejs_binary` in `nodejs_binary_macro` to private visibility and add optional `testonly` attribute so that exported `nodejs_binary` can be used as a test dependency.
Add `patterns` attribute to `node_modules_filegroup`.
> Nodejs macro private visibility & testonly option

- .circleci/config.yml
- internal/jasmine_node_test/jasmine_node_test.bzl
- internal/node/node.bzl
- internal/node/node_launcher.sh
- internal/node/node_repositories.bzl
Bazel 0.14.0 & 0.14.1 show random out of memory crashes on CircleCI. Downgrading to bazel 0.13.0 and removing the 0.14.0 requirement recently introduced because of `@bazel_tools//tools/bash/runfiles`.
> Downgrade to bazel 0.13.0

- internal/npm_install/npm_install.bzl
According to this issue: https://github.com/bazelbuild/rules_nodejs/issues/155 .bin directory is not available in node_modules target. 
This behaviour was introduced with https://github.com/bazelbuild/rules_nodejs/pull/130
> Add node_modules/.bin/* to yarn_install and npm_install

- internal/node/node_repositories.bzl
If you use bazel-managed deps, this value is unused, and should just be omitted
> Make the package_json attribute to node_repositories optional.

- internal/node/node_launcher.sh
When using nodejs_image of rules_docker there is a problem that `SIGTERM` and `SIGINT` do not get forward to the node process by bash. So when interactively running the container it is not possible to Ctrl+C out and further it would not be possible to implement any custom `SIGTERM` behaviour if needed.
As far as my bash knowledge goes this should be backwards-compatible.
> Forward termination signals to node process.

- internal/node/node.bzl
- internal/node/node_loader.js
This avoids printing a warning for binaries that don't need source maps.
Fixes #263
> nodejs_binary attribute that disables source-map-support

- examples/packages/setup_workspace.bzl
- internal/node/node_repositories.bzl
- internal/npm_install/npm_install.bzl
We are slowly starting to adopt bazel internally for our nodejs code and right now we still make use of both devDependencies and dependencies as not everything is fully converted to bazel. So creating a docker `nodejs_image` for prod is much larger than needed as it includes all deps. This PR allows us to workaround the issue for now.
Instead of having a `prod_only` flag I would also be happy to have a more generic `additional_args` or `args` attribute to add any custom flags to the call.  Happy to add whichever would be preferred.
> Allow to install prod dependencies only with yarn.

- README.md
- internal/node/node_repositories.bzl
Node 10.3.0 is needed to enable usage of `npm ci`, which only uses the `package-lock.json` to install dependencies and does not resolve differences.
Adding this version enables consistency through projects that use Bazel and move to node 10.3.0.
Using `npm ci` should result in much faster dependency installation as outlined below (up to 2x-3x speedup):
* https://docs.npmjs.com/cli/ci
* https://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable
* https://medium.com/better-things-digital/npm-ci-a-command-you-should-know-d8d67847884c
> Add node 10.3.0 as an available version for node_repositories

- .circleci/config.yml
- BUILD.bazel
- README.md
- internal/common/node_module_info.bzl
- internal/e2e/rollup_fine_grained_deps/BUILD.bazel
- internal/e2e/rollup_fine_grained_deps/has-deps.js
- internal/e2e/rollup_fine_grained_deps/no-deps.js
- internal/e2e/rollup_fine_grained_deps/rollup.spec.js
- internal/node/node.bzl
- internal/node/node_loader.js
- internal/node/test/BUILD.bazel
- internal/node/test/has-deps.js
- internal/node/test/no-deps.js
- internal/npm_install/generate_build_file.js
- internal/npm_install/test/BUILD.bazel.golden
- internal/rollup/rollup.config.js
- internal/rollup/rollup.config.spec.js
- internal/rollup/rollup_bundle.bzl
& change rollup_bundle default to `//:node_modules_none`. rollup_bundle also updated to handle fine grained npm deps.
> Make node_modules attribute to rules_nodejs optional

- internal/node/node_repositories.bzl
angular/angular requires 10.9.0 or newer
> Add node 10.9.0 & 10.10.0 and yarn 1.9.2 & 1.9.4

- internal/common/sources_aspect.bzl
This is needed for ts_web_test_suite downstream since it uses sources aspect and with npm fine grained deps sources from `@npm//:foo` deps get included in karma. Same thing would apply to all other rules that use the `sources_aspect`. Behavior of using `@npm//:foo` in deps should be the same as when using the legacy `node_modules`.
> Don't include sources from npm fine grained deps in result of sources_aspect

- internal/jasmine_node_test/jasmine_runner.js
Since fine grained deps don't exclude `**/test/**` you can get files such as `node_modules/jasmine/test/test.js` included as specs unintentionally.
This is the same logic that ts_web_test_suite uses: https://github.com/bazelbuild/rules_typescript/blob/master/internal/karma/karma.conf.js#L120
> Filter out files that match test.js and spec.js but are in node_modules

- internal/node/node_loader.js
Since readDir is recursive, paths of depth >1 could still contain the Windows path separator.
> Fix path separator for tree artifacts

- internal/rollup/rollup.config.js
- internal/rollup/rollup.config.spec.js
Path mappings are described with POSIX paths so we should normalize imports when comparing them.
> Fix rollup path mapping with slashes

- .bazelci/presubmit.yml
- examples/define_var/BUILD.bazel
- examples/define_var/define.spec.js
- examples/rollup/BUILD.bazel
- examples/rollup/rollup.spec.js
Test added in #300 fails locally when running `bazel test ...` and its not obvious why without some better comments.
> Add some comments to document how test should be run

- internal/common/expand_into_runfiles.bzl
Otherwise they will become 'workspace/../path', which is the same as just 'path'.
Although both are valid, these paths are meant to be looked up in the runfiles so they should be normalized already instead of leavinf it for the consuming tool.
This is especially important in windows where the runfiles manifest contains strings of normalized paths.
> Don't add workspace to expanded ../ paths

- package.bzl
As a consequence, Bazel on Windows can now build
//docs/...
See https://github.com/bazelbuild/skydoc/issues/58
> Update skydoc repo to fix skydoc #58

- .bazelci/presubmit.yml
- package.bzl
Followup to https://github.com/bazelbuild/rules_nodejs/pull/336
> Update Skydoc to work on Windows

- internal/e2e/fine_grained_deps/package-lock.json
- internal/e2e/fine_grained_deps/package.json
- internal/e2e/fine_grained_deps/yarn.lock
- internal/npm_install/generate_build_file.js
Currently if a dependency has only optional dependencies, the `generate_build_file.js` script fails at analysis time because only for NPM, the `optionalDependencies` are generated into `dependencies` as well.
This is not the case for Yarn, and therefore the `dependencies` can be also undefined.
See sample package: https://github.com/jprichardson/node-klaw/blob/1.3.1/package.json
cc. @gregmagolan
> Build file generation should not throw if dependency has only optional dependencies

- internal/node/node_repositories.bzl
Fixes https://github.com/bazelbuild/rules_nodejs/issues/347
> Exclude .pyc files from node_runfiles

- internal/npm_install/npm_install.bzl
This lets us reuse the downloaded artifact cache
> Use yarn mutex rather than cache-folder

- .gitignore
- packages/README.md
- packages/bazel-darwin_x64/package.json
- packages/bazel-linux_x64/package.json
- packages/bazel-win32_x64/package.json
- packages/bazel/bazel.js
- packages/bazel/package.json
- packages/mirror.sh
note, there isn't a native node api to replace the node process with bazel, so it stays a child process.
We could use https://github.com/jprichardson/node-kexec/blob/master/src/kexec.cc but then it's different between windows and mac/linux
> Add @bazel/bazel and platform-specific packages

- packages/bazel/bazel.js
In case someone runs Bazel through NPM by using the `@bazel/bazel` package, the exit code is not propagated. Meaning that the exit code will be always `0`, regardless of the result of the child Bazel process.
**Note**: I've also switched to a synchronous `spawn` because there should be no difference in performance. It just allows us to easier handle the exit code.
> fix(@bazel/bazel): exit code not being propagated properly

- .circleci/config.yml
We have tried and failed several times to find memory settings that allow us to build skylint
> Retreat to running skylint/buildifier binaries in the docker image

- internal/node/node_repositories.bzl
On the 30th  of October Node 10.12 is planned to become the new LTS so I think we should update the default version to that. And for yarn it is imo just worth updating as it contains a lot of fixes and improvements since 1.3.
> Update node LTS, yarn to latest version and change defaults.

- package.bzl
Fixes https://github.com/bazelbuild/rules_nodejs/issues/221, we need this change to re-enable rules_nodejs in Bazel CI downstream projects.
/cc @alexeagle
> Update skydoc to latest version to use the Starlark version of http_archive

- internal/e2e/node_loader_no_preserve_symlinks/WORKSPACE
- internal/e2e/node_loader_preserve_symlinks/WORKSPACE
- package.bzl
Version 0.3.1 doesn't work with rules_typescript... rules_typescript currently installs 0.5.0 as the dep:
```
###############################################
_maybe(
http_archive,
name = "bazel_skylib",
url = "https://github.com/bazelbuild/bazel-skylib/archive/0.5.0.zip",
strip_prefix = "bazel-skylib-0.5.0",
sha256 = "ca4e3b8e4da9266c3a9101c8f4704fe2e20eb5625b2a6a7d2d7d45e3dd4efffd",
)
```
> Update to bazel_skylib 0.5.0

- internal/node/node_repositories.bzl
Deprecated in https://github.com/bazelbuild/bazel-skylib/pull/58
> Don't use deprecated lib.bzl

- internal/e2e/node/BUILD.bazel
- internal/e2e/node/data_resolution.spec.js
- internal/node/node_loader.js
Since there can be also runfiles which refer to the current `USER_WORKSPACE`, but actually resolve to the bazel output instead of to the actual local workspace, it can happen that the `node_loader` determines a wrong path to the local workspace.
We can safely fix this by just ensuring that the runfile, which potentially resolves to the local workspace, does not refer to the bazel-bin or bazel-genfiles directory (those paths are templated)
Fixes #352.
cc. @alexeagle
> fix: local workspace path not always properly determined

- internal/npm_install/npm_install.bzl
This should mitigate yarn install timeouts on slow networks. I've seen timeouts while running a Windows VM on OSX and yarn install timeouts have been seen on occasion in CircleCI.
Note: default --network-timeout option in yarn is 30s
> Set --network-timeout option in yarn_install

- package.bzl
This fixed Bazel CI failures (bazelbuild/bazel#6742) such as https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/613#0098d76c-1532-43d0-914e-cc506950c5b4
> Update bazel-toolchains pin

- internal/npm_package/packager.js
This makes it easier to test that the replacement happens in ng_package without having to stamp the artifacts
> Always replace 0.0.0-PLACEHOLDER even if there's no stamp info

- internal/jasmine_node_test/jasmine_runner.js
- internal/jasmine_node_test/test/BUILD.bazel
- internal/jasmine_node_test/test/no_jasmine_test.js
This improves the developer experience if people just use `jasmine_node_test` without adding `jasmine` as an actual runtime dependency. Related to #344
> Improve failure message for invalid jasmine_node_test setup

- internal/node/node_loader.js
This CL changes the "failed to resolve" error message to make it more readable. 
Instead of logging commas between lines, this puts \n in between, and indent the items to match the context.
from:
```
(node:84267) UnhandledPromiseRejectionWarning: Error: //:types-installer_bin cannot find module './actions.js'
looked in:
built-in, relative, absolute, nested node_modules - Error: Cannot find module '/sth.runfiles/ws/package.json'
,
runfiles - Error: Cannot find module '/sth.runfiles/sth.runfiles/ws/package.json'
,
ws/node_modules - Error: Cannot find module '/sth.runfiles/ws/node_modules/sth.runfiles/ws/package.json'
,
node_modules attribute (ws/node_modules) - Error: Cannot find module '/sth.runfiles/ws/node_modules/sth.runfiles/ws/package.json'
```
to:
```
(node:85394) …
```
> node_loader: improve the readability of "failed to resolve" error message

- internal/node/node_repositories.bzl
The logic in `_prepare_node()` was assuming that if we're vendoring
NodeJS then we're also vendoring Yarn. But this is not always the
case.
> Make it possible to vendor NodeJS without vendoring Yarn.

- internal/node/node_loader.js
This removed logged is spammy if a require.resolve() call is expected to fail like this karma code in rules_typescript:
```
try {
// attempt to resolve in @bazel/karma nested node_modules first
return require.resolve(f.replace(/^NODE_MODULES\//, '@bazel/karma/node_modules/'));
} catch (e) {
// if that failed then attempt to resolve in root node_modules
return require.resolve(f.replace(/^NODE_MODULES\//, ''));
}
```
The following logs show up in all karma test logs:
```
Failed to findPath for /private/var/tmp/_bazel_greg/837d12dda6835e241d9d3083438c6bb6/sandbox/darwin-sandbox/1/execroot/build_bazel_rules_typescript/bazel-out/darwin-fastbuild/bin/examples/testing/testing_chromium-local.runfiles/build_bazel_rules_typescript/internal/karma/node_modules/requirejs/require.js
Failed to findPath …
```
> Remove spammy log in node_loader.js when require.resolve() throws

- internal/jasmine_node_test/test/BUILD.bazel
- internal/node/node.bzl
- internal/node/node_loader.js
- internal/node/node_repositories.bzl
- third_party/github.com/buffer-from/BUILD.bazel
- third_party/github.com/buffer-from/LICENSE
- third_party/github.com/buffer-from/index.js
- third_party/github.com/buffer-from/package.json
- third_party/github.com/source-map-support/BUILD.bazel
- third_party/github.com/source-map-support/LICENSE.md
- third_party/github.com/source-map-support/LOCAL_MODS.md
- third_party/github.com/source-map-support/package.json
- third_party/github.com/source-map-support/source-map-support.js
- third_party/github.com/source-map/BUILD.bazel
- third_party/github.com/source-map/LICENSE
- third_party/github.com/source-map/lib/array-set.js
- third_party/github.com/source-map/lib/base64-vlq.js
- third_party/github.com/source-map/lib/base64.js
- third_party/github.com/source-map/lib/binary-search.js
- third_party/github.com/source-map/lib/mapping-list.js
- third_party/github.com/source-map/lib/quick-sort.js
- third_party/github.com/source-map/lib/source-map-consumer.js
- third_party/github.com/source-map/lib/source-map-generator.js
- third_party/github.com/source-map/lib/source-node.js
- third_party/github.com/source-map/lib/util.js
- third_party/github.com/source-map/package.json
- third_party/github.com/source-map/source-map.js
Changed source-map-support to support bazel workspaces to produces shorter readable stacks that help in navigating to the code directly in an editor like VSCode.
Tested with angular/angular repo and VSCode.
Vendor in source-map-support and mod it to support bazel workspaces for workspace rooted paths in stack traces.
Sourcemap properly applies to nodejs test and binaries produced by bazel.
> Use source-map-support that's vendored in

- internal/node/node_loader.js
Given `'rxjs/ajax/index.js'` as `path`, and the following resolutions:
```
var MODULE_ROOTS = [
{module_name: /^rxjs\/ajax\/\b/, module_root: 'rxjs/ajax/'},
{module_name: /^rxjs\/ajax\b/, module_root: 'rxjs/ajax/index.js'},
]
```
The current algorithm would disregard the first match because it left the string unchanged, even though it was the longest regex.
This caused it to return `rxjs/ajax/index.js/index.js` instead of `rxjs/ajax/index.js`.
Followup to https://github.com/bazelbuild/rules_nodejs/pull/474, related to a failure observed in https://github.com/angular/angular/pull/27764.
`rxjs/ajax/index.js` is returned for the given example.
I couldn't find any tests for this logic. Are …
> Consider all matches in resolveToModuleRoot

- .circleci/config.yml
The CI currently check and auto-fix the unformatted BUILD files.
We make sure that the CI only checks and failes on unformatted BUILD files.
> ci: make sure the CI checks for unformatted files

- internal/npm_install/npm_install.bzl
Previously, the `timeout` arg was used for both the `repository_ctx.execute()` timeout and the yarn's `--network-timeout`. Yet, in some cases the default 10mins timeout is not enough for the `npm/yarn install` job to complete (e.g. on CI VM with slow network connection). Additionally, it makes little sense to set the per-request network timeout and the overall command timeout (which potentially involves multiple network requests) to the same value.
This PR introduces a new arg for `yarn_install()` to set `--network-timeout` (defaulting to 5mins) and increases the default `timeout` value to 60mins (from 10mins).
Run into this while investigating buildkite failures related to angular/angular#27508.
> Increase `npm/yarn install` timeout and add new arg for `--network-timeout`

- internal/npm_install/npm_install.bzl
As of Bazel 0.20.0 progress is reported for repository rules such as yarn_install and npm_install so feedback is on by default for these rules which can take some time to complete.
Quiet defaulting to false was intended as a stop-gap measure while Bazel was working on the above change.
Reference: https://github.com/bazelbuild/rules_nodejs/pull/427#issuecomment-440277731
> Default to quiet=True for yarn_install and npm_install now that Bazel outputs progress

- internal/npm_package/packager.js
- package.json
- yarn.lock
I can't think of a reason why someone would want this directory in the package. It's only possible when your npm_package rule is declared in the root package anyway. But we should think a bit more about whether there's a case for vendoring your external deps this way, or whether some other files you publish might have references into the external/ directory?
> don't include external/ directory in npm_package

- internal/npm_package/packager.js
I ran into this exception yesterday and it is helpful to know which file the copy failed on
> Improve error message in npm_package if a file fails to copy

- WORKSPACE
- internal/node/node_repositories.bzl
- package.bzl
- third_party/github.com/bazelbuild/bazel-skylib/LICENSE
- third_party/github.com/bazelbuild/bazel-skylib/lib/BUILD
- third_party/github.com/bazelbuild/bazel-skylib/lib/paths.bzl
The story for installing transitive deps in Bazel is too difficult for end-users downstream
> Remove transitive dep on @bazel_skylib

- internal/npm_package/packager.js
Adding a non-greedy qualifier to the wildcard between BEGIN-INTERNAL & END-INTERNAL fixes https://github.com/bazelbuild/rules_nodejs/issues/516
> Fix npm_package to support multiple BEGIN-INTERNAL/END-INTERNAL blocks in a file

- internal/node/node_loader.js
Fixes Windows node_loader resolution bug that came up in https://github.com/bazelbuild/rules_typescript/pull/374.
> Fix windows node_loader  resolution bug in resolveManifestDirectory()

- internal/npm_install/npm_install.bzl
In the past rules_nodejs would symlink `yarn.lock` which was nice because I could just update a package in the `package.json` file, then do `bazel run` and my `yarn.lock` would be updated automatically. At some point this behaviour was broken.
If `exclude_packages` are empty I see no reason for the copy to take place and it would be nice to have a way to get the previous behaviour back that I kind of got to rely on.
> Symlink yarn lock file if exclude_packages is empty.

- .bazelrc
Now that https://github.com/bazelbuild/bazel/issues/4603 is resolved, it's convenient to have them again
> Allow Bazel to create symlinks

- BUILD.bazel
- internal/npm_package/npm_package.bzl
- internal/npm_package/packager.js
- internal/npm_package/test/npm_package.spec.js
Disables the 0.0.0-PLACEHOLDER replacement for the archive package since it re-writes the npm_package rule and breaks it.
> Fix release archive npm_package rule

- internal/e2e/jasmine/BUILD.bazel
- internal/e2e/jasmine/jasmine_shared_env_bootstrap.js
- internal/e2e/jasmine/jasmine_shared_env_test.spec.js
- internal/jasmine_node_test/jasmine_runner.js
- internal/test/package.json
- internal/test/yarn.lock
Replaces #497 and fixes issue found in https://github.com/angular/flex-layout/pull/964.
A jasmine_node_test bootstrap script now only needs the following lines and jasmine_runner will share the initialized jasmine:
```
const jasmineCore: any = require('jasmine-core');
jasmineCore.boot(jasmineCore);
```
`jasmineCore.boot(jasmineCore)` will initialize `global.jasmine`. For reference, the current bootstrap looks like: https://github.com/angular/angular/blob/master/tools/testing/init_node_no_angular_spec.ts
If using zone.js, call `jasmine-patch.js` after `boot()` to patch `global.jasmine`:
```
import 'zone.js/dist/jasmine-patch.js';
```
Now if the bootstrap script modifies the jasmine env with something like this:
```
afterEach(() => testBedInstance.resetTestingModule());
``` …
> Fix jasmine_runner.js so that an already initialized jasmine will be used

- internal/e2e/fine_grained_no_bin/BUILD.bazel
- internal/e2e/fine_grained_no_bin/package.json
- internal/e2e/fine_grained_no_bin/yarn.lock
- internal/rollup/package.json
- internal/rollup/rollup.config.js
- internal/rollup/yarn.lock
- internal/test/package.json
- internal/test/yarn.lock
Update to a version of rollup-plugin-node-resolve that supports `es2015` entry points with fallback to `module` and `main`: https://github.com/gregmagolan/rollup-plugin-node-resolve/commit/7a33dc249b69497aff3380a37a359158167b4801.
Will put a PR up for rollup-plugin-node-resolve to land this in their repo.
Needed when rolling up rxjs here: https://github.com/angular/angular/pull/27220
> Add support for es2015 entry point field in rollup

- BUILD.bazel
- internal/BUILD.bazel
- internal/node.bzl
> Restore back-compat file internal/node.bzl and mark as deprecated

- internal/web_package/assembler.js
- internal/web_package/test/BUILD.bazel
- internal/web_package/test/index_golden.html_
Showed up in https://github.com/angular/angular/pull/28625 bazel-schematics integration test. It looks like it only happens under Linux.
> Fix fs.copyFileSync `EACCES: permission denied` failure

- README.md
- defs.bzl
- examples/bazel_managed_deps/WORKSPACE
- examples/define_var/WORKSPACE
- examples/parcel/WORKSPACE
- examples/webapp/WORKSPACE
- internal/node/node_repositories.bzl
The common WORKSPACE pattern is to pass no arguments to it, and use yarn_install or npm_install
We can make the trivial WORKSPACE file shorter.
> make node_repositories optional

- DEVELOPING.md
> Add release instructions for @bazel/jasmine

- packages/typescript/package.json
`package.json` metadata change
Clicking on `Homepage` from [npm](https://www.npmjs.com/package/@bazel/typescript) takes you to a 404 page on GitHub.
Clicking on `Homepage` from [npm](https://www.npmjs.com/package/@bazel/typescript) takes you to the `typescript` package directory on GitHub.
> Fix @bazel/typescript homepage URL

- internal/copy_repository/_copy.sh
`/bin/bash` does not exist on all systems. E.g. [NixOS](https://nixos.org/). This patch uses `/usr/bin/env bash` instead, which will pick the correct `bash` from `PATH`.
Loading the workspace fails with
```
ERROR: error loading package '': Encountered error while reading extension file 'defs.bzl': no such package '@build_bazel_rules_typescript//': copy_repository failed:
STDOUT:
STDERR:
java.io.IOException: Cannot run program ".../external/build_bazel_rules_typescript/./_copy.sh" (in directory ".../external/build_bazel_rules_typescript"): error=2, No such file or directory
```
Loading the workspace works.
> Fix _copy.sh shebang

- internal/node/node_repositories.bzl
@alexeagle Can you mirror?
`https://github.com/yarnpkg/yarn/releases/download/v1.13.0/yarn-v1.13.0.tar.gz` => `https://mirror.bazel.build/github.com/yarnpkg/yarn/releases/download/v1.13.0/yarn-v1.13.0.tar.gz`
Thanks.
> Add yarn 0.13.0 and make it the default version of yarn for node_repositories()

- packages/typescript/WORKSPACE
- packages/typescript/docs/BUILD.bazel
- packages/typescript/docs/docs_test.js
- packages/typescript/package.json
Hopefully this fixes it so npmjs will render the README
> fix(@bazel/typescript): remove unknown rules from generated API doc

- packages/jasmine/src/jasmine_runner.js
- packages/jasmine/test/BUILD.bazel
- packages/jasmine/test/filtering_test.js
Instead of manually passing the specs, use the built-in filtering mechanism
> Make test sharding work with jasmine focusing

- internal/copy_repository/copy_repository.bzl
- internal/npm_install/generate_build_file.js
- internal/npm_install/npm_install.bzl
Previously it did not re-copy the package contents, so the bazel workspace would be stale
> fix yarn_install and npm_install after changed packages

- examples/app/BUILD.bazel
- examples/app/index.html
- internal/web_package/injector.js
- internal/web_package/injector_spec.js
- internal/web_package/test/index_golden.html_
Fixes regression from https://github.com/bazelbuild/rules_nodejs/pull/610 in web_package injector.js (which is also used by ts_devserver) where an non-ESModule script is tagged with `nomodule` when there is no matching ESModule script with `type="module"`. This causes the script not to load in a modern ESModule browser.
> Fix web_package injector nomodule issue when no matching ESModule script

- package.bzl
This git_repository was causing me a lot of grief on a very slow internet connection. It's a 100+MB download and not cacheable as a git_repository.
> Use cacheable http_archive with sha256 for io_bazel as its a very large download

- e2e/jasmine/BUILD.bazel
- e2e/jasmine/coverage.spec.js
- e2e/jasmine/coverage_source.js
- packages/jasmine/package.json
- packages/jasmine/src/jasmine_node_test.bzl
- packages/jasmine/src/jasmine_runner.js
- packages/jasmine/test/BUILD.bazel
- packages/jasmine/test/coverage.spec.js
- packages/jasmine/test/coverage_source.js
- packages/jasmine/yarn.lock
jasmine_node_test does not report code coverage
jasmine_node_test does reports code coverage
Example oputput:
```
:~/Documents/rules_nodejs/packages/jasmine$ bazel run test:coverage
INFO: Invocation ID: c4e9cd85-aad8-4fad-9537-71c8a665861c
INFO: Analysed target //test:coverage (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //test:coverage up-to-date:
bazel-bin/test/coverage_loader.js
bazel-bin/test/coverage.sh
INFO: Elapsed time: 0.190s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //test:coverage …
```
> feat(@bazel/jasmine): add coverage reporting

- internal/rollup/BUILD.bazel
- internal/web_package/BUILD.bazel
This prints extra warnings in users builds that they can't fix (and the warnings don't even indicate what file has the dependency)
> Don't load the deprecated jasmine_node_test from other rules.

- packages/jasmine/BUILD.bazel
- packages/jasmine/index.js
- packages/jasmine/src/jasmine_runner.js
Fix for https://github.com/bazelbuild/rules_nodejs/issues/632.
Ensure `jasmine-core` version required by jasmine_runner corresponds to the `jasmine` version that `@bazel/jasmine` depends on.
In the future we may want to allow user to override the version of jasmine used by `jasmine_node_test`. @devversion pointed out that this is not currently possible as the `jasmine` attribute is now meant to point to a user's `@bazel/jasmine` npm dep and not their `jasmine` dep.
> Fix jasmine & jasmine-core requires in jasmine_runner.js

- e2e/ts_devserver/package.json
- examples/app/package.json
- examples/protocol_buffers/package.json
We don't require either for CI or tests and they are not pinned which led to an intermittent CI failure with the gecko driver recently.
This `postinstall` failure in /examples/app, /e2e/ts_devserver and /examples/protocol_buffers happened recently and lasted for a few days until I assume it was fixed by the webdriver-manager team:
```
[17:45:58] I/file_manager - creating folder /home/circleci/rules_nodejs/examples/app/node_modules/webdriver-manager/selenium
[17:45:58] I/config_source - curl -o/home/circleci/rules_nodejs/examples/app/node_modules/webdriver-manager/selenium/standalone-response.xml https://selenium-release.storage.googleapis.com/
[17:45:58] I/config_source - curl -o/home/circleci/rules_nodejs/examples/app/node_modules/webdriver-manager/selenium/chrome-response.xml …
```
> Don't update gecko driver or selenium stand-alone in webdriver-manager update callsv

- e2e/jasmine/BUILD.bazel
- e2e/jasmine/package.json
- e2e/jasmine/yarn.lock
Tests for failure reported in https://github.com/bazelbuild/rules_nodejs/issues/632
> Add jasmine_node_test that fails without fix from #633

- .circleci/config.yml
- scripts/setup_examples_angular.sh
- scripts/test_examples.sh
After checkout replacements made to package.json & WORKSPACE of angular-bazel-example using bash sed. grep is used to sanity check that the replacements took effect.
> Checkout and test angular-bazel-example in CI

- README.md
- packages/typescript/docs/install.md
> Clarify install instructions to fix a pitfall

- examples/app/BUILD.bazel
- examples/app/test/BUILD.bazel
- packages/typescript/internal/devserver/ts_devserver.bzl
moved from https://github.com/bazelbuild/rules_typescript/pull/439
@achew22 could you help me add to the commit message here an explanation of *why* we make this change?
> Add visible alias for the metadata entry of ts_devserver

- internal/npm_install/BUILD.bazel
PR closes https://github.com/bazelbuild/rules_nodejs/issues/652
```
$ bazel query --output=build //internal/npm_install:package_contents
filegroup(
name = "package_contents",
visibility = ["//:__pkg__"],
srcs = ["//internal/npm_install:BUILD.bazel", "//internal/npm_install:generate_build_file.js", "//internal/npm_install:npm_install.bzl", "//internal/npm_install:package.json", "//internal/npm_install:process_package_json.js", "//internal/npm_install:yarn.lock"],
)
```
> fix(npm_install): exclude test directory

- package.bzl
rules_nodejs depends on [bazel_skylib 0.6.0](https://github.com/bazelbuild/bazel-skylib/releases/tag/0.6.0)
rules_nodejs depends on [bazel_skylib 0.8.0](https://github.com/bazelbuild/bazel-skylib/releases/tag/0.8.0)
> Update bazel_skylib dependency to 0.8.0

- internal/npm_install/test/package/delete_build_files.js
> Fix for #652: Running "bazel run @nodejs//:yarn" twice fails with unlink error

- packages/typescript/internal/protobufjs/BUILD.bazel
As part of pre-factoring to prep for https://github.com/bazelbuild/rules_nodejs/pull/655
> Remove unused file export

- scripts/build_packages.sh
- scripts/link_deps.sh
- scripts/publish_release.sh
- scripts/test_e2e.sh
- scripts/test_examples.sh
- scripts/test_legacy_e2e.sh
- scripts/test_packages.sh
- scripts/unlink_all_deps.sh
- scripts/unlink_deps.sh
Should mitigate accidentally committing locally modified package.json files with absolute `file://` entries.
> Update scripts to unlink deps in package.json for nested workspaces after builds & tests to reduce local changes

- packages/bazel/index.js
`@bazel/bazel` should export getNativeBinary() method so that downstream
consumers can locate the actual Bazel binary and spawn a process using
custom options. If loaded as script the code should continue to work as before.
> fix(bazel): export getNativeBinary()

- internal/e2e/rollup/BUILD.bazel
- internal/e2e/rollup/outputgroups.spec.js
- internal/e2e/rollup_code_splitting/BUILD.bazel
- internal/e2e/rollup_code_splitting/outputgroups.spec.js
- internal/rollup/rollup_bundle.bzl
~~This adds sourcemap targets output groups for all the output formats.~~
Today there's the default target which outputs the es5 bundle.js and bundle.js.map. Then there's sub-targets such as `.es2015.js`, `.umd.js` etc. There's also `.js` which is the same as the default target but without the `.map`. But there's no way to easily fetch the .js+map of only the es2015 bundle.
~~This adds a `.js.map` target alongside every `.js` target.~~
This adds an output-group for each bundle type. The tests show an example of `filegroup`s consuming these output-groups.
> feat(rollup): provide sourcemaps for all output types

- packages/jasmine/package.json
Ran into yet another corner case for re-exporting the correct `jasmine-core` from `@bazel/jasmine` npm package here: angular/angular#29913. A direct dependency on `jasmine-core` from `@bazel/jasmine` instead of relying on the transitive dep via `jasmine` would fix the issue.
For reference the case is. `@bazel/jasmine`dep on jasmine is hoisted to the root node_modules so its under `node_modules/jasmine` but root package.json has a conflicting dep on `jasmine-core` so its location is `node_modules/jasmine/node_modules/jasmine-core`.
Replaces #697.
> Add jasmine-core dependency to @bazel/jasmine since it is required in its index

- internal/npm_package/npm_package.bzl
- internal/npm_package/packager.js
- internal/npm_package/test/BUILD.bazel
- internal/npm_package/test/npm_package.spec.js
**BREAKING CHANGE**: npm_package now throws for any files in `srcs` which
do not reside in the same package as the target.
The `deps` attr of `npm_package` should allow files.
A common use case would be named output of other rules, such as
`rollup_bundle`. In which case, user should be able to add
`bundle.umd.js` from `rollup_bundle` to the `deps` of `npm_package`.
> fix(npm_package): deps should allow files

- internal/jasmine_node_test/jasmine_node_test.bzl
- internal/npm_package/test/npm_package.spec.js
Windows: jasmine_node_test uses nodejs_test_macro
Fix the jasmine_node_test() rule on Windows when
tested with Bazel's Windows-native test wrapper
(see https://github.com/bazelbuild/bazel/issues/5508).
jasmine_node_test() now uses nodejs_test_macro()
instead of nodejs_test(). This changes the test's
executable from a Bash script to a native Windows
binary, so the rule can be tested using Bazel's
new Windows-native test wrapper.
The default test wrapper is a Bash script, which
could run shell scripts as subprocesses so it
could test nodejs_test() directly.
The new test wrapper is a native C++ binary that
can only run native Windows binaries. (But it does
not require Bash, see https://github.com/bazelbuild/bazel/issues/5508.)
What …
> Windows: jasmine_node_test uses nodejs_test_macro

- .gitignore
- scripts/clean_all.sh
- scripts/clean_e2e.sh
- scripts/clean_examples.sh
- scripts/clean_packages.sh
This fixes a few pain points for local development.
1. golden files like `internal/npm_install/test/golden/node_modules/@angular/core/BUILD.bazel.golden` are git ignored since they are in a `node_modules` folder. This PR fixes that by adding the negate pattern `!/internal/npm_install/test/golden/node_modules` to gitignore.
2. clean scripts now recursively delete *all* node_modules folders in the repo since `.bazelignore` doesn't behave like `.gitignore` and its `node_modules` entry only tells bazel to ignore the root `/node_modules` folder. Each nested folder must be listed explicitly in `.bazelignore`.
Will file an issue about the `.bazelignore` behavior to Bazel about this soon as it will cause issues for all users of nodejs rules that have nested `node_modules` and multiple …
> Don’t gitignore /internal/npm_install/test/golden/node_modules

- internal/rollup/rollup_bundle.bzl
In order to support external source-maps, the `rollup-plugin-sourcemaps` module has
been added to the rollup configuration. Unfortunately this currently only has an effect
on Windows as the sandbox is not available and the plugin can read the referenced
external `.map` files.
When running in the Bazel sandbox or within RBE, these map files can't be read
by the plugin because the `.map` files are omitted from the `run_rollup` action
inputs. This causes inconsistent behavior and makes the sourcemaps plugin a no-op
right now.
> Rollup bundle rule does not resolve external source maps

- internal/common/check_bazel_version.bzl
- internal/common/check_version.bzl
- internal/common/check_version_test.py
- [x ] Tests for the changes have been added (for bug fixes / features)
- [x ] Docs have been added / updated (for bug fixes / features)
- [x ] Feature (please, look at the "Scope of the project" section in the README.md file)
Before this change, there is no way to check the bazel version falls into a range.  Bazel has been having quite a few breaking changes and a minimum version check (bazel_check_version) is no longer enough.
bazel_check_version_range provides the function to check the bazel version is in a range, not just a minimum version.
- [x ] No
> Add check_bazel_version_range function

- internal/npm_install/generate_build_file.js
- internal/npm_install/node_module_library.bzl
- internal/npm_install/test/golden/BUILD.bazel.golden
- internal/npm_install/test/golden/node_modules/@angular/core/BUILD.bazel.golden
- internal/npm_install/test/golden/node_modules/@gregmagolan/BUILD.bazel.golden
- internal/npm_install/test/golden/node_modules/@gregmagolan/test-a/BUILD.bazel.golden
- internal/npm_install/test/golden/node_modules/@gregmagolan/test-b/BUILD.bazel.golden
- internal/npm_install/test/golden/node_modules/ajv/BUILD.bazel.golden
- internal/npm_install/test/golden/node_modules/jasmine/BUILD.bazel.golden
- internal/npm_install/test/golden/node_modules/rxjs/BUILD.bazel.golden
- internal/npm_install/test/golden/node_modules/unidiff/BUILD.bazel.golden
- internal/npm_install/test/golden/node_modules/zone.js/BUILD.bazel.golden
Generated `__pkg` targets should not use `srcs` and should only specify `__files` targets in `deps` so that `sources_aspect` picks up all `dev_scripts` via `deps` tree which allows the transitive lookup in `node_module_library` to be removed.
> Cleanup srcs/deps/scripts attributes in node_module_library and its usage

- e2e/typescript_2.7/BUILD.bazel
- e2e/typescript_2.8/BUILD.bazel
- e2e/typescript_2.9/BUILD.bazel
- e2e/typescript_3.0/BUILD.bazel
- e2e/typescript_3.1/BUILD.bazel
- internal/npm_install/generate_build_file.js
- internal/npm_install/test/golden/@angular/core/BUILD.bazel.golden
- internal/npm_install/test/golden/@gregmagolan/test-a/BUILD.bazel.golden
- internal/npm_install/test/golden/@gregmagolan/test-b/BUILD.bazel.golden
- internal/npm_install/test/golden/BUILD.bazel.golden
- internal/npm_install/test/golden/ajv/BUILD.bazel.golden
- internal/npm_install/test/golden/jasmine/BUILD.bazel.golden
- internal/npm_install/test/golden/node_modules/@angular/core/BUILD.bazel.golden
- internal/npm_install/test/golden/node_modules/@gregmagolan/BUILD.bazel.golden
- internal/npm_install/test/golden/node_modules/@gregmagolan/test-a/BUILD.bazel.golden
- internal/npm_install/test/golden/node_modules/@gregmagolan/test-b/BUILD.bazel.golden
- internal/npm_install/test/golden/node_modules/ajv/BUILD.bazel.golden
- internal/npm_install/test/golden/node_modules/jasmine/BUILD.bazel.golden
- internal/npm_install/test/golden/node_modules/rxjs/BUILD.bazel.golden
- internal/npm_install/test/golden/node_modules/unidiff/BUILD.bazel.golden
- internal/npm_install/test/golden/node_modules/zone.js/BUILD.bazel.golden
- internal/npm_install/test/golden/rxjs/BUILD.bazel.golden
- internal/npm_install/test/golden/unidiff/BUILD.bazel.golden
- internal/npm_install/test/golden/zone.js/BUILD.bazel.golden
- packages/typescript/internal/build_defs.bzl
These are all the changes required in this repo to get npm strict deps to work.
We have a chicken & egg problem to land this so we need to:
1) Land this PR
2) Update the rules_nodejs commit hash in rules_typescript and land https://github.com/bazelbuild/rules_typescript/pull/445
3) Update the commit hash in rules_nodejs in another PR
(3) will be a breaking change and downstream users that are depending on transitive @npm deps in their ts_library or ng_module rules will see errors that look like so:
```
main.spec.ts:1:21 - error TS2307: transitive dependency on external/npm/node_modules/typescript/lib/typescript.d.ts not allowed. Please add the BUILD target to your rule's deps.
1 import * as ts from 'typescript';
```
> Structural changes for npm strict deps support

- internal/common/sources_aspect.bzl
Soon, Bazel will forbid iteration on a depset, it needs to be explicitly
converted to list.
> Fix build with --incompatible_depset_is_not_iterable

- packages/karma/browser_repositories.bzl
- packages/karma/karma.conf.js
OSX Chromium 73+ requires disabling of the sandbox under Bazel
Windows still on Chromium 66 and updating that is a separate task and requires changes to rules_webtesting as the archive name & executable path has changed
> Update @bazel/karma to latest sable Chromium 74 for osx & linux

- WORKSPACE
- package.bzl
With this change, the code works with Bazel flag `--incompatible_disable_deprecated_attr_params`, which will be enabled soon.
> Update protobuf dependency

- internal/e2e/fine_grained_no_bin/BUILD.bazel
- internal/e2e/fine_grained_no_bin/index.js
- internal/node/node_loader.js
If I call `require.resolve("../test.js", { paths: ["/some/path/in/sandbox"] })` the options are not forwarded correctly because the `_resolveFilename` method takes 4 parameters.
All expected parameters are forwarded, so are the options now and paths will be respected.
I ran into this as the latest version of one of our npm dependencies is making use of this case and that fix fixes it.
> Forward all args to originalResolveFilename

- examples/bazel_managed_deps/BUILD.bazel
- examples/bazel_managed_deps/WORKSPACE
- examples/bazel_managed_deps/deps.spec.js
via an example of how to make a target for node_modules/.bin/*
Example also shows use of migration instructions for users that were depending on `node_modules/.bin/BUILD` targets: https://github.com/bazelbuild/rules_nodejs/wiki#node_modulesbinbuild-file-no-longer-generated.
> Add test coverage for manual_build_file_contents... 

- .circleci/config.yml
Fix angular-bazel-example test in CI which was crashing and flaking out
`bazel test //e2e:all` was crashing before the tests even started in CI. Possibly out of memory but not sure how that is possible as it was running in the xlarge 16GB container. This PR moves the angular-bazel-example test to its own CI job (which speeds up overall CI time as its critical path) and runs the same CI tests that angular-bazel-example runs in its own CI.
> Fix angular-bazel-example CI

- e2e/karma/BUILD.bazel
- e2e/karma/init-test.js
- e2e/karma/test-initialized.spec.js
- packages/karma/karma.conf.js
Currently when someone specifies a `static_files` target that transitively brings in
a package "X", and there is a target in the `deps` that transitively also brings in "X",
the files from "X" are accidentally **not** included in the Karma ConcatJS bundle. 
This causes the tests to fail since a required dependency is not executed/included.
> fix(karma): static_files overwrite files specified in dependencies

- packages/bazel-darwin_x64/package.json
- packages/bazel-linux_x64/package.json
- packages/bazel-win32_x64/package.json
- packages/bazel/package.json
- packages/buildifier-darwin_x64/package.json
- packages/buildifier-linux_x64/package.json
- packages/buildifier-win32_x64/package.json
- packages/buildifier/package.json
- packages/buildozer-darwin_x64/package.json
- packages/buildozer-linux_x64/package.json
- packages/buildozer-win32_x64/package.json
- packages/buildozer/package.json
- packages/create/package.json
- packages/jasmine/package.json
The Apache license version 2.0 SPDX short identifier is Apache-2.0
//cc @clydin 
More info: https://spdx.org/licenses/
> fix: license SPDX should be `Apache-2.0` instead of `Apache 2.0`

- packages/bazel/index.js
It was failing in some cases, see attached bug.
We shouldn't recommend a global install anyway. using yarn bazel or npx bazel is probably better
Fixes #656
> Remove detection logic for warning on global bazel

- examples/vendored_node/WORKSPACE
The docs for node_repositories() reflect this now and the reason is that node_repositories() will set node options depending on version used
> Update examples/vendored_node to reflect best practice of specifying node version

- internal/jasmine_node_test/jasmine_node_test.bzl
- packages/jasmine/src/jasmine_node_test.bzl
- packages/jasmine/test/BUILD.bazel
- packages/jasmine/test/templated_args_test.js
Currently, it is not possible to specify `templated_args` on a `jasmine_node_test`. This is because the `jasmine_node_test` implementation unconditionally passes its own `templated_args` to the underlying `nodejs_test` rule. It is an error in the loading phase to have a target with duplicated keywords. 
My use case is to pass `--node_options=--experimental-modules` to the underlying `nodejs_binary`, which allows node to load ES modules [natively](https://nodejs.org/api/esm.html).
General support for ES modules in rules_nodejs is a larger topic that calls for more design and discussion, but I think this commit is independently useful. Thoughts?
> jasmine_node_test: pass templated_args through to nodejs_test.

- internal/rollup/rollup_bundle.bzl
Having it there causes it to always be built, whether requested or not.
This partially unblocks using rollup_bundle in dev mode.
if you expect the rollup_bundle es5.min file to be a runtime dependency of a rule, you must now include it in the data[] of that rule
> Remove es5.min rollup_bundle output from runfiles

- packages/typescript/WORKSPACE
https://github.com/bazelbuild/rules_typescript/pull/455 must land first and the commit updated to upstream
UPDATE: https://github.com/bazelbuild/rules_typescript/pull/455 landed and commit updated to upstream
> Update to latest rules_typescript commit

- .circleci/config.yml
- commitlint.config.js
- package.json
- yarn.lock
To prepare for changelog generation, require commit messages to be well-formed. The scope part of the commit should reference one of the `@bazel` npm packages, or use "builtin" for things in the `build_bazel_rules_nodejs` repository rule.
Also run bazel lint and format on push, since I keep forgetting to do this and it costs an extra CI roundtrip
> pre-push and commit-msg git hooks

- .bazelci/presubmit.yml
- internal/node/node.bzl
- internal/npm_install/npm_umd_bundle.bzl
- internal/rollup/rollup_bundle.bzl
- packages/typescript/WORKSPACE
Depsets are no longer iterable on Bazel 0.26.1
> Compatibility with Bazel 0.26.1

- packages/typescript/WORKSPACE
Now that https://github.com/bazelbuild/rules_typescript/pull/453 has landed
> build(typescript): switch back to upstream commit of rules_typescript

- package.bzl
* rules_sass https://github.com/bazelbuild/rules_sass/pull/87 has landed so can switch back to upstream
* stardoc commits we were depending on have since been releases so can switch to a release archives of io_bazel & io_bazel_skydoc
> build: update dev dependencies

- .bazelrc
- internal/common/BUILD.bazel
This should unblock Bazel 0.27 RC which requires a python toolchain
See #809
> test: disable our one py_test

- .circleci/config.yml
- internal/node/node_loader.js
- internal/node/test/BUILD.bazel
- internal/node/test/module-name.js
- scripts/test_all.sh
Skip module root resolution in node resolver if main entry point. Also don't throw on resolve failure so that resolve does cascade down incase the module_root conflicts with the workspace name for fully resolved requires
Fixes #834
> fix(builtin): fix for issue 834

- packages/create/index.js
- packages/create/test.js
This is required to install an extra node_modules for use by the
ts_devserver rule.
> fix(create): run ts_setup_workspace in TypeScript workspaces

- common.bazelrc
- e2e/ts_library/WORKSPACE
- e2e/ts_library/reference_types_directive/BUILD.bazel
- e2e/ts_library/reference_types_directive/tsconfig_types.ts
- internal/npm_install/test/package/BUILD.bazel
- package.json
- packages/typescript/WORKSPACE
- packages/typescript/internal/build_defs.bzl
- yarn.lock
This should help users stay on the happy path
> feat(create): add workers flags

- .bazelci/presubmit.yml
- package.bzl
Switch back to upstream rules_sass commit now that https://github.com/bazelbuild/rules_sass/pull/88 has landed.
Switch back to latest Bazel version (0.27.0) in bazelci config
> Update rules sass upstream

- packages/typescript/WORKSPACE
Now that https://github.com/bazelbuild/rules_typescript/pull/458 has landed
> build: switch to upstream rules_typescript commit

- .circleci/config.yml
- .circleci/env.sh
- e2e/ts_devserver/package.json
- e2e/ts_devserver/yarn.lock
- examples/app/package.json
- examples/app/yarn.lock
- examples/protocol_buffers/package.json
- examples/protocol_buffers/yarn.lock
- internal/node/node_repositories.bzl
- packages/typescript/package.json
- packages/typescript/yarn.lock
- scripts/check_deps.sh
There are a few commonly used npm packages such as webdriver-manager that now require node >= 10.15.0.
> Update to node 10.16.0 default for node_repositories

- internal/rollup/rollup_bundle.bzl
This allows usage of for..of on iterators, even when targeting ES5.
The following code gets mis-downleveled by tsc:
```
let foo = new Map();
for (const [k, v] of foo) {
console.log(k, v);
}
```
into:
```
var foo = new Map();
for (var _i = 0, foo_1 = foo; _i < foo_1.length; _i++) {
var _a = foo_1[_i], k = _a[0], v = _a[1];
console.log(k, v);
}
```
because of https://github.com/Microsoft/TypeScript/issues/11209 .  This is broken code. 
Since `tsc` is hardcoded to target ES5, we should add this flag in order to prevent `rollup_bundle` from emitting broken code.
The sample code gets transpiled correctly:
```
var __values = (this && this.__values) || function (o) {
var m = …
```
> rollup_bundle/tsc: add --downlevelIteration

- .bazelci/presubmit.yml
- internal/node/node_repositories.bzl
> Fix node cross compile on Windows

- packages/typescript/internal/protobufjs/ts_proto_library.bzl
Instead of the deprecated .proto. provider .
`ts_proto_library` depends on the `.proto.` provider which is going to be removed in Bazel 1.0:
https://github.com/bazelbuild/bazel/issues/7152
Issue Number: https://github.com/bazelbuild/bazel/issues/7152
It uses the new `ProtoInfo` provider.
> Update ts_proto_library to use ProtoInfo.

- internal/rollup/BUILD.bazel
- packages/jasmine/BUILD.bazel
- packages/jasmine/src/BUILD.bazel
- packages/karma/src/BUILD.bazel
- packages/labs/BUILD.bazel
- packages/labs/src/webpack/BUILD.bazel
- packages/protractor/BUILD.bazel
- packages/stylus/BUILD.bazel
- packages/stylus/src/BUILD.bazel
- packages/typescript/BUILD.bazel
- packages/typescript/replacements.bzl
- packages/typescript/src/index.bzl
> fix: fencing for npm packages

- packages/jasmine/src/jasmine_node_test.bzl
- packages/jasmine/src/jasmine_runner.js
- packages/jasmine/test/BUILD.bazel
- packages/jasmine/test/test_config_file.js
- packages/jasmine/test/test_config_file.json
Finally chose an approach to fix this.
- Accept a config file like in #744 
- now the user can have their spec files named anything, doesn't need to follow our conventions
> Jasmine custom config

- docs/Karma.md
- docs/TypeScript.md
- packages/karma/docs/install.md
- packages/typescript/docs/install.md
As a phrasal verb, [*set up* is two words.][set-up]
[set-up]: https://en.wiktionary.org/wiki/setup#Verb
wchargin-branch: set-up
> docs: fix “setup” typos

- packages/create/BUILD.bazel
- packages/hide-bazel-files/BUILD.bazel
- packages/jasmine/BUILD.bazel
- packages/karma/BUILD.bazel
- packages/labs/BUILD.bazel
- packages/protractor/BUILD.bazel
- packages/stylus/BUILD.bazel
- packages/typescript/BUILD.bazel
- tools/defaults.bzl
Would like to reduce the boilerplate as we make more and more packages
> refactor: reduce some duplication in npm_package rules

- package.bzl
It has been deprecated for many releases and should be removed before 1.0
> chore: remove deprecated rules_nodejs_dependencies helper

- .bazelrc
- .circleci/bazel.rc
It's annoying when tests are failing locally that they run twice, so I've been adding --flaky_test_attempts=1 manually.
Also BuildKite was already setting --flaky_test_attempts=3 so we really only need to update CircleCI
> refactor: move flaky_test_attempts to CI config

- defs.bzl
- scripts/on-version.js
Fix on release script from clobbering BAZEL_VERSION in //:defs.bzl
> build: fix on release script & BAZEL_VERSION

- internal/rollup/rollup.config.js
Allows rollup to resolve browser mainFields in prod the same as we added for umd mainFields for dev.
Not too sure how to test this
> feat(builtin): add browser to rollup mainFields

- .circleci/config.yml
- e2e/BUILD.bazel
- e2e/ts_auto_deps/BUILD.bazel
- e2e/ts_auto_deps/dummy_test.sh
- e2e/ts_auto_deps/package.json
- e2e/ts_auto_deps/simple/BUILD
- internal/bazel_integration_test/bazel_integration_test.bzl
- internal/bazel_integration_test/test_runner.js
This e2e test was causing issues in https://github.com/bazelbuild/rules_nodejs/pull/1040 since the circleci assertion was using "latest" for npm packages but local_repository for rules_nodejs.
> test: move e2e/ts_auto_deps assertion from circleci to bazelci

- declaration_provider.bzl
This gives us a principled way for rules to generate and consume TypeScript typings
> feat(builtin): add a DeclarationInfo provider

- internal/node/node_loader.js
The format of Node's own error from loader.js is https://github.com/nodejs/node/blob/a49b20d3245dd2a4d890e28582f3c013c07c3136/lib/internal/modules/cjs/loader.js#L264
Issue Number: #1015
The error message reflects the same as Node's error message here: https://github.com/nodejs/node/blob/a49b20d3245dd2a4d890e28582f3c013c07c3136/lib/internal/modules/cjs/loader.js#L264
Use the new error message format.
> Reformat the error message for Node loader.js

- e2e/BUILD.bazel
- packages/typescript/src/package.json
Set it to 3.0 or greater. This lets us drop some e2e testing which was taking a long time on CI.
Note that typescript doesn't do semver so we are conservative about advertising support for versions we don't test on.
> fix(typescript): add peerDependency on typescript

- .bazelci/presubmit.yml
- .circleci/config.yml
- DEVELOPING.md
- common.bazelrc
- docs/Terser.md
- docs/index.md
- internal/bazel_integration_test/test_runner.js
- internal/golden_file_test/bin.js
- internal/golden_file_test/golden_file_test.bzl
- internal/node/node.bzl
- internal/node/node_loader.js
- internal/npm_install/browserify-wrapped.js
- internal/npm_install/generate_build_file.js
- internal/npm_install/pre_process_package_json.js
- internal/rollup/rollup.config.js
- internal/rollup/terser-wrapped.js
- internal/rollup/tsc-directory.js
- packages/karma/src/karma.conf.js
- packages/protractor/src/protractor.conf.js
- packages/terser/src/terser_minified.bzl
- packages/terser/test/debug/BUILD.bazel
- packages/terser/test/inline_sourcemap/spec.js
- packages/terser/test/user_config/BUILD.bazel
- packages/terser/test/user_config/output.debug.golden.js_
- all rules updated to use DEBUG and VERBOSE_LOGS environment variables
- added golden_debug attribute golden_file_test to support the case where a rule has different output if DEBUG is set; for example
```
golden_file_test(
name = "test",
actual = "out.min.js",
golden = "output.golden.js_",
golden_debug = "output.debug.golden.js_",
)
```
> feat: add default DEBUG and VERBOSE_LOGS configuration_env_vars to nodejs_binary

- internal/node/node.bzl
- toolchains/node/BUILD.bazel
- toolchains/node/node_toolchain.bzl
- Support the toolchains attribute of rules like genrule, so they can get the NODE_PATH
- Expose files and a path to node, rather than whether the node binary is locally installed or came from Bazel fetching it
> refactor(builtin): improve node toolchain

- internal/node/node_loader.js
If the manifest has an entry in the output_base but not in the binDir or genDir, we get a wrong path for later resolutions
Fixes #1087
> fix(builtin): fix localWorkspacePath logic

- BUILD.bazel
- internal/linker/BUILD.bazel
- internal/linker/README.md
- internal/linker/link_node_modules.bzl
- internal/linker/link_node_modules.js
- internal/linker/test/BUILD.bazel
- internal/linker/test/integration/BUILD.bazel
- internal/linker/test/integration/pkg_a/BUILD.bazel
- internal/linker/test/integration/pkg_a/index.js
- internal/linker/test/integration/program.js
- internal/linker/test/integration/rule.bzl
- internal/linker/test/integration/test.sh
- internal/linker/test/link_node_modules.spec.js
This is a separate process we run right before node programs.
Its job is to create symlinks so that the node_modules tree exists and
has all the packages we might want to load at runtime.
This will eventually replace the need for a custom module resolver,
custom typescript path mappings, and the existing module_mappings.bzl
support for TS/runtime mappings.
> feat(builtin): introduce a linker

- internal/node/node_loader.js
I can't reproduce this locally on my Windows machine so something must be different on buildkite Windows CI in how it sets `process.env.RUNFILES_MANIFEST_FILE` as it looks like it has mixed slashes when passed into `loadRunfilesManifest(process.env.RUNFILES_MANIFEST_FILE)`
> fix: node_loader windows fix

- internal/bazel_integration_test/bazel_integration_test.bzl
- internal/common/devmode_js_sources.bzl
- internal/common/expand_into_runfiles.bzl
- internal/common/windows_utils.bzl
- internal/node.bzl
- internal/node/node.bzl
- internal/rollup/rollup_bundle.bzl
- packages/karma/src/karma_web_test.bzl
- packages/protractor/src/protractor_web_test.bzl
- packages/typescript/src/internal/devserver/ts_devserver.bzl
- toolchains/node/node_toolchain.bzl
Now that node entry_point is a label we can do this.
This also makes _to_manifest_path naming consistent in all the rules.
Note: expand_location_into_runfiles is still used for templated_args in nodejs_binary & nodejs_test
> refactor: replace usages of expand_path_into_runfiles to _to_manifest_path

- internal/node/node_loader.js
- internal/rollup/rollup.config.js
That version was released nearly a year ago.
Fixes #910
> chore: remove 0.13 migration message

- WORKSPACE
- internal/npm_install/generate_build_file.js
- internal/npm_install/test/check.js
- internal/npm_install/test/generate_build_file.spec.js
- internal/npm_install/test/golden/@gregmagolan/test-a/bin/BUILD.bazel.golden
Currently it's not possible to specify a dynamic dependency for a scoped package. e.g. the default `dynamic_deps` value that adds `tsickle` to `@bazel/typescript` doesn't work because it never matches.
This is because the dynamic dependency logic currently checks against the `pkg._name`, which is just the trailing path segment of the package path. This is incorrect and confusing as it omits the package scope. e.g. `@bazel/typescript` => `typescript`.
> fix(npm_install): dynamic_deps attribute not working for scoped packages

- packages/typescript/src/internal/ts_repositories.bzl
This was introduced a year ago in https://github.com/bazelbuild/rules_typescript/pull/276/files to help avoid a breaking change to rxjs. They no longer need it, and very unlikely anyone else ever used it.
A compatibility layer was removed. See discussion in https://github.com/bazelbuild/rules_nodejs/issues/1086
Fixes #1086
> chore: remove tsc_wrapped_deps compatibility

- rules_webtesting.patch
Updates to latest rules_webtesting commit to pick up two Windows fixes.
1) https://github.com/bazelbuild/rules_webtesting/commit/e082ffd85190a9573b2367ef2ee7dadc87dc21c7
2) https://github.com/bazelbuild/rules_webtesting/commit/e7e838126b64c9a51dc06078e2f491b9a07b144e
We are using a patch to pull in (1) at the moment so this PR also removes the patch.
Not having (2) is blocking the rules_nodejs update in angular/angular: https://github.com/angular/angular/pull/32151
Other options are:
1) wait for rules_webtesting cuts the next release so we can update to the released version
2) explicitly pull this rules_webtesting commit into https://github.com/angular/angular/pull/32151 for now so it can land
> build: update to latest rules_webtesting commit to pickup windows fixes

- .circleci/config.yml
Strangely, CircleCI works on this repo but does not work on a cloned
repo because of a duplicate variable name. Fixes #1138.
> chore: rename duplicate CircleCI variable

- packages/terser/src/index.js
- packages/terser/test/exec/BUILD.bazel
- packages/terser/test/exec/spec.js
this is missing needed negative tests to make sure error output is useful and exit code is correct.
> chore: parallelize terser runs

- e2e/typescript/BUILD.bazel
These rollup_bundles snuck into e2e/typescript/BUILD.bazel but they are not testing anything
> test: cleanup e2e/typescript build file

- examples/angular/src/BUILD.bazel
store.umd.js will be automatically added by yarn_install via APF detection. Also store.umd.min.js breaks with Ivy as ivy-ngcc does not transform store.umd.min.js file (only store.umd.js)
> test: examples/angular ts_devserver does not need to included @ngrx/store/bundles/store.umd.min.js

- scripts/clean_nested_workspaces.sh
The script gets confused when there a file such as /e2e/e2_karma_stack_trace/node_modules/@bazel/karma/WORKSPACE and when there are nested node_modules such as /e2e/e2_karma_stack_trace/node_modules/@bazel/karma/node_nodules
> chore: fix issue in clean_nested_workspaces.sh script

- README.md
This PR updates the "sections below" reference to point to the installation docs, since the details and alternatives are not present in the sections below of the README.
The documentation refers to "sections below", but the sections below do not contain additional details or alternatives for installing rules_nodejs.
Link to the docs page that contains the additional details and alternatives.
> fix(README): update "sections below" reference

- internal/common/collect_es6_sources.bzl
collect_es6_sources is going to be removed along with the legacy rollup_bundle but for now this change removes one of the few uses of the legacy “typescript” provider remaining.
> refactor: switch collect_es6_sources to use JSEcmaScriptModuleInfo

- examples/angular/patches/@angular+bazel+9.0.0-next.8.patch
- packages/typescript/src/internal/build_defs.bzl
- providers.bzl
Some consumers may only be interested in the javascript sources that are produced directly by a dep and not in the sources produced by transitive deps. This change allows those consumers to select only those sources.
BREAKING CHANGES:
Helper function `transitive_js_ecma_script_module_info` in `//:providers.bzl` renamed to `js_ecma_script_module_info`. It now returns a JSEcmaScriptModule info with both `sources` and `direct_sources` fields populated.
> feat(typescript): add direct_sources field to JSEcmaScriptModuleInfo

- examples/angular/patches/@angular+bazel+9.0.0-next.8.patch
- providers.bzl
This will make updating angular/angular much easier. Alias to be removed before 1.0 release.
> feat(typescript): add a transitive_js_ecma_script_module_info alias to js_ecma_script_module_info

- examples/app/BUILD.bazel
- examples/app/package.json
- examples/app/tsconfig-test.json
- examples/app/yarn.lock
- internal/node/npm_package_bin.bzl
- packages/typescript/docs/install.md
This will give us enough room to avoid major `ts_library` changes for 1.0
> feat: document the escape hatch from ts_library

- internal/npm_install/generate_build_file.js
- internal/npm_install/generate_build_file.ts
when local packages already managed with build files are linked into node_modules they may be erroneously re-exported causing directory has a BUILD file failures. 
this should be a fix for #871 
when searching for packages under a given path if one is a symlink it'll be skipped.
> fix: dont generate build files in symlinked node_modules

- packages/terser/src/index.js
Directory mode should match file mode which already allows .mjs files
```
def _filter_js(files):
return [f for f in files if f.is_directory or f.extension == "js" or f.extension == "mjs"]
```
> fix(terser): terser_minified should support .mjs files when running on directory

- docs/install.md
The question of how to manage multiple independent sets of npm deps has come up on slack several times now, and it was something I was confused by initially. Hopefully this makes things a little clearer, especially for folks migrating existing code bases.
The install document now describes how to use separate `yarn_install` calls for each `package.json`.
> docs: add instructions for multiple sets of npm deps

- BUILD.bazel
- declaration_provider.bzl
- internal/linker/link_node_modules.bzl
- internal/node/node.bzl
- internal/node/npm_package_bin.bzl
- internal/npm_install/node_module_library.bzl
- internal/npm_install/npm_umd_bundle.bzl
- internal/npm_package/npm_package.bzl
- internal/providers/BUILD.bazel
- internal/providers/declaration_info.bzl
- internal/providers/js_providers.bzl
- internal/providers/npm_package_info.bzl
- internal/rollup/rollup_bundle.bzl
- packages/karma/src/karma_web_test.bzl
- packages/karma/src/web_test.bzl
- packages/labs/src/protobufjs/ts_proto_library.bzl
- packages/protractor/src/protractor_web_test.bzl
- packages/rollup/src/rollup_bundle.bzl
- packages/typescript/src/internal/build_defs.bzl
- packages/typescript/src/internal/devserver/ts_devserver.bzl
- providers.bzl
Put all shared provider code into .bzl files in /providers folder and re-export all from //:providers.bzl so that users have a consistent load location. Legacy load locations kept around so dependency sandwich with angular/angular is simpler to resolve. Should be able to remove them by 1.0.
> refactor: all providers exported from //:providers.bzl

- internal/npm_install/generate_build_file.js
- internal/npm_install/generate_build_file.ts
Issue Number: #1162
Ability to pass a `canIgnore` list of strings containing peer dependency names that can be ignored.
This is one implementation, we could make it so we can pass it via the `*_install` rule instead if it might be cleaner.
> Add ability to ignore peer depdenencies from package.json

- examples/angular/src/BUILD.bazel
- examples/angular_view_engine/src/BUILD.bazel
- examples/kotlin/BUILD.bazel
- internal/linker/link_node_modules.bzl
- internal/node/bazel_require_script.js
- internal/node/node.bzl
- internal/node/node_launcher.sh
- internal/node/npm_package_bin.bzl
- internal/npm_install/generate_build_file.js
- internal/npm_install/generate_build_file.ts
- internal/npm_install/test/generate_build_file.spec.js
- internal/providers/node_runtime_deps_info.bzl
- packages/rollup/src/rollup_bundle.bzl
- packages/rollup/test/integration/BUILD.bazel
- packages/rollup/test/plugins/BUILD.bazel
- providers.bzl
This replaces the dynamic_deps mechanism for pulling user-specified plugins into the node_modules tree
> refactor: use deps declared on rollup_bundle

- examples/angular/WORKSPACE
this removes the need for
--host_force_python=PY2
> chore(examples): upgrade ruels_docker

- packages/karma/src/index.ts
Replace the eval() with <script> tags for each script, so that they still create global variables
Similar to g3 cl/198411444
Fixes #922
> fix(karma): load scripts in strict mode

- packages/rollup/src/BUILD.bazel
- packages/rollup/src/index.js
- packages/rollup/src/package.json
It looks like npm was complaining because there was a "bin" entry to "index.js".
> refactor(rollup): remove index.js file

- tools/defaults.bzl
this patch refactors the _GLOBAL_ODEOWNERS variable to a list,
additionally refactoring the logic when appending _GLOBAL_OWNERS to the
`teams` property of a `codeowners()` rule to ensure that users in
_GLOBAL_OWNERS are not duplicated in the generated output.
I didn't see any tests for the current macro (other than the `golden_file_test()` to test the generated output from all usages of the rule/macro). There is no documentation update required.
The `_GLOBAL_OWNERS` variable is a string, and is appended to each `teams` property in `codeowners()` rules (as long as `no_parent = False` [the default]).
This presents two problems:
1. A string is not extensible, when other global owners need …
> fix: prevent dpulicate entries in owners files for global owners

- packages/rollup/src/rollup_bundle.bzl
- ~[ ] Tests for the changes have been added (for bug fixes / features)~
- ~[ ] Docs have been added / updated (for bug fixes / features)~
Per https://github.com/rollup/rollup/blob/master/docs/999-big-list-of-options.md#outputsourcemap, 'hidden' is supported for output.sourcemap, but not `rollup_bundle` rule.
> rollup_bundle: add "hidden" as a valid sourcemap option

- .bazelci/presubmit.yml
- common.bazelrc
- docs/Built-ins.md
- docs/Terser.md
- internal/bazel_integration_test/test_runner.js
- internal/golden_file_test/bin.js
- internal/node/node.bzl
- internal/providers/js_providers.bzl
- package.json
- packages/create/index.js
- packages/terser/src/terser_minified.bzl
- packages/terser/test/debug/BUILD.bazel
- packages/terser/test/inline_sourcemap/spec.js
- packages/terser/test/sourcemap/directory_spec.js
- packages/terser/test/sourcemap/terser_spec.js
Deprecate `--define DEBUG=1` and use `--compilation_mode=dbg` instead. The value of compilation mode will be passed to any nodejs executables as  'COMPILATION_MODE' environment variable. All builtin rules/tests that depends on `DEBUG` are now using `COMPILATION_MODE` instead.
Issue Number: #1323 
Use `--compilation_mode=dbg` to trigger the debugging build.
Defining `--define DEBUG` will no longer trigger a debugging build. To allow users to use to the new flag, a warning message will be printed if `--define DEBUG` is set while `--compilation_mode` is not `dbg`.
`DEBUG` is kept in `default_env_vars`, as many npm packages use it to trigger the debugging behavior. However, I do believe …
> builtin: support --compilation_mode flag

- package.bzl
Context: https://github.com/bazelbuild/bazel/issues/10270
> Mirror all http_archives.

- WORKSPACE
Pins bazel version for rbe_autoconfig to BAZEL_VERISON. This fixes a bazelci failure on the macos_fake_rbe job that showed up when Bazel 1.2.0 was selected in rbe_default.
```
(02:39:31) DEBUG: /private/var/tmp/_bazel_buildkite/6597d199fda0844cb2301c486cfe87c0/external/bazel_toolchains/rules/rbe_repo.bzl:477:5: Bazel 1.2.0 is used in rbe_default.
--
  | (02:39:31) ERROR: An error occurred during the fetch of repository 'rbe_default':
  | Traceback (most recent call last):
  | File "/private/var/tmp/_bazel_buildkite/6597d199fda0844cb2301c486cfe87c0/external/bazel_toolchains/rules/rbe_repo.bzl", line 505
  | validate_host(ctx)
  | File "/private/var/tmp/_bazel_buildkite/6597d199fda0844cb2301c486cfe87c0/external/bazel_toolchains/rules/rbe_repo/util.bzl", line 147, in validate_host
  | …
```
> build: fix macos_fake_rbe job on bazelci

- examples/angular/src/BUILD.bazel
- examples/angular_view_engine/src/BUILD.bazel
- examples/webapp/differential_loading.bzl
- internal/node/npm_package_bin.bzl
- internal/node/test/BUILD.bazel
To match genrule behavior described here: https://docs.bazel.build/versions/master/be/make-variables.html#predefined_genrule_variables:
```
RULEDIR: The output directory of the rule, that is, the directory corresponding to the name of the package containing the rule under the genfiles or the bin tree.
```
Also added $(@D) to be equal to the path of the directory artifact when output_dir=True.
> fix(builtin): $(RULEDIR) npm_package_bin expansion should always be the root output directory

- internal/pkg_web/pkg_web.bzl
This allows generating an index.html file into a different folder in the output tree (so that it doesn't collide within put index.html file) and then re-mapping
the output in pkg_web back to /index.html. ts_devserver already supports this via additional_root_paths so this brings the same functionality to pkg_web.
It is useful for the case where you have a single input index.html file and you inject scripts tags and output to a dir such as _/index.html and consume the output in both ts_devserver & pkg_web. For example,
```
html_insert_assets(
name = "inject_scripts",
outs = ["_/index.html"],
args = [
"--html",
"$(location :index.html)",
"--out",
"$@",
"--assets",
"$(location @npm//:node_modules/zone.js/dist/zone.min.js)",
"bundle.min.js",
],
data = [
":index.html", …
```
> fix(builtin): additional_root_paths in pkg_web should also include paths in genfiles and bin dirs

- internal/node/bazel_require_script.js
- packages/node-patches/BUILD.bazel
- packages/node-patches/src/fs.ts
- packages/node-patches/src/subprocess.ts
fixes #1401 
this should fix jest :crossed_fingers: the example repro still fails but i think its because of a legitimate reason.
> fix: support realpath.native and fix crash in mkdirp

- internal/node/bazel_require_script.js
- packages/node-patches/src/fs.ts
- packages/node-patches/test/fs/realpath.ts
fixes missing realpathSync.native. fs.realpathSync was duplicated.
> Realpath native sync

- internal/node/node_repositories.bzl
Based on discussion on #763 we think users have good reason to control this setting as they may have symlinks in their sources
and their program may require following or not following those symlinks in order to run correctly.
Fixes #763
> chore: undeprecate preserve_symlinks option to node_repositories

- internal/linker/link_node_modules.bzl
- internal/linker/test/integration/rule.bzl
- internal/node/node.bzl
- internal/node/node_launcher.sh
- internal/npm_install/generate_build_file.js
- internal/npm_install/generate_build_file.ts
- internal/npm_install/test/golden/@gregmagolan/test-a/index.bzl.golden
- internal/npm_install/test/golden/jasmine/index.bzl.golden
- internal/providers/node_runtime_deps_info.bzl
- packages/node-patches/BUILD.bazel
For #1382 
Pairing with @mrmeku on it today
> Hook up linker to nodejs_binary/nodejs_test

- internal/npm_install/generate_build_file.js
- internal/npm_install/generate_build_file.ts
- internal/npm_install/test/generate_build_file.spec.js
> fix(builtin): strip BOM when parsing package.json

- internal/node/node.bzl
- packages/labs/src/protobufjs/ts_proto_library.bzl
As described in [the bazel docs](https://docs.bazel.build/versions/master/skylark/performance.html#use-depsets) unnecessarily nesting `depset`s is a performance anti-pattern.
I think all these cases are pretty basic changes?
> perf: avoid unnecessary nested depset()

- packages/rollup/src/rollup_bundle.bzl
Added clarification from https://github.com/bazelbuild/rules_nodejs/issues/1416 to the documentation.
> Clarification on how rollup_bundle works with ts_library inputs

- defs.bzl
- docs/index.md
- examples/angular/WORKSPACE
- examples/angular/rules_docker.patch
- examples/angular_view_engine/WORKSPACE
- examples/nestjs/WORKSPACE
- examples/nestjs/rules_docker.patch
Users must now switch to loading from index.bzl
Fixes #1068
> chore: make defs.bzl error

- internal/linker/index.js
- internal/linker/link_node_modules.ts
- internal/linker/test/link_node_modules.spec.ts
Fixes #1411
The overall change is to build a recursive hierarchy instead of just an array of arrays (one level of the hierarchy?). That hierarchy is then the order changes must be processed in, siblings in the hierarchy can be processed concurrently as long as the parent was already processed.
IDK if such a drastic change was really necessary, but it's the path I started down. Maybe we can just adjust the existing implementation but keep the tests?
This also does a bit less `mkdirp` calls, the `@foo/c/c/c/c` test now has I think 17 mkdirp/symlink calls instead of 21 🤷‍♂ 
~~2 of the tests fail before the change, I might try finding more cases though...~~
5 of the tests fail before the change, I think all of which are ~unique situations. I've outlined these more in the issue.
> fix(builtin): link module_name to directories recursively to avoid directory clashes

- e2e/packages/WORKSPACE
- e2e/packages/npm1/package.json
- e2e/packages/npm2/package.json
- e2e/packages/npm_determinism.spec.js
- e2e/packages/yarn1/package.json
- e2e/packages/yarn2/package.json
- e2e/packages/yarn_determinism.spec.js
- internal/npm_install/npm_install.bzl
`args` in yarn_install and npm_install can be used to pass arbitrary arguments so we removed the following attributes:
* prod_only from yarn_install and npm_install; should be replaced by args = ["--prod"] and args = ["--production"] respectively
* frozen_lockfile from yarn_install; should be replaced by args = ["--frozen-lockfile"]
* network_timeout from yanr_install; should be replaced by args = ["--network_timeout", "<time in ms>"]
> refactor(builtin): add `args` to yarn_install & npm_install

- .bazelci/presubmit.yml
master broke on the bump to 2.0.0 so needs to be fixed before we can upgrade
> build: pin bazel on bazelci to 1.2.1

- BUILD.bazel
- bootstrap.js
- e2e/jasmine/BUILD.bazel
- internal/common/expand_into_runfiles.bzl
- internal/linker/index.js
- internal/linker/link_node_modules.ts
- internal/node/node.bzl
- internal/node/node_loader.js
- internal/node/test/BUILD.bazel
- internal/node/test/bootstrap.js
- internal/node/test/bootstrap.spec.js
- internal/node/test/bootstrap1.js
- internal/node/test/bootstrap2.js
- internal/node/test/bootstraps.spec.js
* fix(builtin): bug fix in linker where bin folder was being included in runfiles path for tests when link type was 'bin'
bootstrap attribute in nodejs_binary, nodejs_test & jasmine_node_test removed
This can be replaced with the `--node_options=--require=$(location label)` argument such as,
```
nodejs_test(
name = "bootstrap_test",
templated_args = ["--node_options=--require=$(rlocation $(location :bootstrap.js))"],
entry_point = ":bootstrap.spec.js",
data = ["bootstrap.js"],
)
```
or
```
jasmine_node_test(
name = "bootstrap_test",
srcs = ["bootstrap.spec.js"],
templated_args = ["--node_options=--require=$(rlocation $(location :bootstrap.js))"],
data = ["bootstrap.js"],
)
```
`templated_args` `$(location)` and `$(locations)` are now correctly expanded when there is no …
> refactor: remove `bootstrap` attribute & fix $(location) expansions in nodejs_binary templated_args

- examples/angular/WORKSPACE
- examples/angular_view_engine/WORKSPACE
- package.bzl
Allows for the removal of install_source_map_support.
> build: update to rules_sass 1.24.0

- common.bazelrc
- examples/parcel/parcel.bzl
- examples/worker/uses_workers.bzl
- internal/bazel_integration_test/BUILD.bazel
- internal/bazel_integration_test/bazel_integration_test.bzl
- internal/bazel_integration_test/test_runner.js
- internal/golden_file_test/bin.js
- internal/node/node.bzl
- internal/pkg_web/pkg_web.bzl
- internal/providers/node_runtime_deps_info.bzl
- package.json
- packages/create/index.js
- packages/labs/src/protobufjs/ts_proto_library.bzl
- packages/labs/src/webpack/webpack_bundle.bzl
- packages/rollup/test/version_stamp/BUILD.bazel
- packages/rollup/test/version_stamp/golden_debug.js_
- packages/rollup/test/version_stamp/rollup.config.js
- packages/terser/src/terser_minified.bzl
- packages/terser/test/inline_sourcemap/spec.js
- packages/terser/test/sourcemap/directory_spec.js
- packages/terser/test/sourcemap/terser_spec.js
- packages/typescript/src/internal/build_defs.bzl
Fixes https://github.com/bazelbuild/rules_nodejs/issues/1446
----------------------
* fix: don't bake COMPILATION_MODE into launcher as exported environment var
This approach is incorrect as tools that are build for host such as "rollup_bin" in the rollup_bundle rule will see the --host_compilation_mode and not the --compilation_mode configuration value when built by Bazel as their cfg in the rule is correctly set to "host".
```
"rollup_bin": attr.label(
doc = "Target that executes the rollup binary",
executable = True,
cfg = "host",
default = "@npm//rollup/bin:rollup",
),
```
The correct approach is to pass COMPILATION_MODE via the actions.run env attribute.
For the rollup_bundle rollup_bin tool, this is passed via run_node:
```
def run_node(ctx, inputs, arguments, executable, **kwargs): …
```
> --compilation_mode fixes

- e2e/jasmine/BUILD.bazel
- e2e/jasmine/jasmine_shared_env_bootstrap.js
- internal/golden_file_test/bin.js
- internal/linker/BUILD.bazel
- internal/linker/index.js
- internal/linker/link_node_modules.ts
- internal/linker/runfiles_helper.js
- internal/node/node.bzl
- internal/node/node_launcher.sh
- internal/npm_install/test/check.js
- packages/jasmine/src/jasmine_runner.js
* export BAZEL_WORKSPACE, BAZEL_NODE_LINKER & BAZEL_NODE_PATCH_REQUIRE env variables from node launcher (in addition to currently exported BAZEL_TARGET & BAZEL_PATCH_ROOT)
* linker now uses BAZEL_WORKSPACE & BAZEL_TARGET so that its runfiles resolve support works with non-test targets that don't have TEST_WORKSPACE & TEST_TARGET envs
* adds resolveWorkspaceRelative() & patchRequire() to linker runfiles resolve support. The former is useful if you want to resolve without worrying about the workspace name. The latter is useful for nodejs_binary bootstrap scripts that want to patch require via the linker (such as e2e/jasmine/jasmine_shared_env_bootstrap.js)
* tests targets can safely use TEST_TARGET & TEST_WORKSPACE and some of these are switched over
Please check if your PR fulfills the …
> feat(builtin): allow patching require in bootstrap scripts

- packages/karma/src/karma_web_test.bzl
- packages/protractor/src/protractor_web_test.bzl
* fix(protractor): pass --node_options to protractor
This enables debugging protractor tests with --node_options=--inspect-brk
```
$ bazel run --config=debug //packages/protractor/test/protractor:test_chromium-local
...
Running protractor tests
-----------------------------------------------------------------------------
version     : 5.4.2
pwd         : /private/var/tmp/_bazel_greg/35306ad70b8da8f7bc31590523de35c0/execroot/build_bazel_rules_nodejs/bazel-out/darwin-dbg/bin/packages/protractor/test/protractor/test_chromium-local.sh.runfiles/build_bazel_rules_nodejs
conf        : ../build_bazel_rules_nodejs/packages/protractor/test/protractor/test_wrapped_test.conf.js
node_options: --node_options=--inspect-brk
Debugger listening on ws://127.0.0.1:9229/7244faba-d905-4072-b0ba-301f9a0e1648 …
```
> Fix protractor & karma debugging

- examples/nestjs/package.json
- examples/nestjs/src/BUILD.bazel
- examples/nestjs/src/main.spec.ts
- examples/nestjs/src/main.ts
- examples/nestjs/yarn.lock
Adds a basic example of how to use the clustering module in Nestjs.
It currently fails with 
```
Error: Cannot find module 'examples_nestjs/src/app.module'
Require stack:
- /SNIP/execroot/examples_nestjs/bazel-out/darwin-fastbuild/bin/src/server.sh.runfiles/examples_nestjs/src/main.js
```
So also doubles as a test for the linker applying correctly to `nodejs_binary`
When this passes then this should be resolved https://github.com/bazelbuild/rules_nodejs/issues/227
> feat(examples): add nodejs_binary cluster example

- .bazelci/presubmit.yml
rules_nodejs is currently failing in Bazel's Downstream Pipeline due to https://github.com/bazelbuild/bazel/issues/10554
We need this change to tell Bazel CI to not pass `--test_env=USE_BAZEL_VERSION` for Angular's integration tests.
> presubmit.yml: Set skip_use_bazel_version_for_test: true

- internal/common/module_mappings.bzl
- internal/node/node.bzl
- internal/node/test/BUILD.bazel
* fix(builtin): nodejs_binary collects module_mappings for linker
Module name cannot be equal to the workspace name with the linker so this change removes the regression test for 834. This was a corner case and was already broken with the 1.0 for npm_package_bin so this fix makes nodejs_binary consistent with npm_package_bin and the new desired behavior for 1.0.
* fix(builtin): legacy module_mappings_runtime_aspect handles dep with module_name but no module_root
> Nodejs binary module mappings

- .bazelrc
- .circleci/config.yml
- internal/node/node.bzl
- internal/node/npm_package_bin.bzl
- internal/node/test/BUILD.bazel
- internal/node/test/define.spec.js
- internal/node/test/expand_variables.golden
- internal/node/test/expand_variables.js
- internal/npm_install/test/bazel_bin_test.sh
- internal/providers/node_runtime_deps_info.bzl
- tools/npm_packages/testy/index.js
- tools/npm_packages/testy/package.json
This behaves similarly to `configuration_env_vars` in `nodejs_binary` except it passes the env vars to the process via the `env` attribute of `ctx.actions.run`.
Also add support for picking up env vars from `ctx.configuration.default_shell_env` if they are not found in `ctx.vars`.
* `ctx.vars` will contain values from `--define=FOO=BAR`
* `ctx.configuration.default_shell_env` will `--action_env=FOO=BAR` (but not from `--action_env=FOO`).
-----------
test: add test coverage for npm_package_bin configuration_env_vars
And test coverage for using --action_env=FOO=BAR to pass env variables to npm_package_bin & nodejs_binary
> feat(builtin): add configuration_env_vars to npm_package_bin

- packages/karma/src/karma_web_test.bzl
Previously, running a web test target with `bazel run` worked, and didn't result in an unbound variable exception. Now with the new runfile bash helpers v2, unbound variables are reported, and in `bazel run` the `TEST_TMPDIR` variable is not set.
There are two ways to fix this: (1) allowing unbound variables by running `set +u` after the helpers, or (2) by just properly handling unbound variables. The latter seems more future-proof to me and best practice.
> Do not error with unbound variable when running karma web test with `bazel run`

- internal/node/node_repositories.bzl
- internal/npm_install/npm_install.bzl
Also do the same for @nodejs//:yarn & @nodejs//:yarn_node_repositories targets.
This allows yarn to pickup the `yarn-path` attribute of `.yarnrc` which is only checked inside `${process.cwd()}/.yarnrc` when yarn runs. Previously we ran yarn with `--cwd` which works for all other `.yarnrc` options except `yarn-path`.
> fix(builtin): set cwd before running yarn for yarn_install

- internal/npm_install/npm_install.bzl
- package.json
- yarn.lock
This fixes a regression in 1.2.0 where the repository rule generated shell script `yarn` in the root of the external repository created by yarn_install conflicts with the npm package `yarn` directory that generate_build_files.js wants to create.
The error observed was:
```
Error: ENOTDIR: not a directory, mkdir 'yarn/bin'
at Object.mkdirSync (fs.js:823:3)
at mkdirp (/private/var/tmp/_bazel_pryan/7a08068b62d3caa281adb87aa0ce207a/external/npm/generate_build_file.js:81:16)
at writeFileSync (/private/var/tmp/_bazel_pryan/7a08068b62d3caa281adb87aa0ce207a/external/npm/generate_build_file.js:89:9)
at generatePackageBuildFiles
```
Also fixes the same potential problem with the repository rule generated `npm` shell script.
What kind of …
> fix: yarn_install failure if yarn is a dependency

- packages/hide-bazel-files/index.js
```
// If an optional dependency failed to install it is possible that readdirSync will
// return a folder name that no longer exists and lstatSync will throw with an error such as
// `Error: ENOENT: no such file or directory, lstat
// '/private/var/folders/0l/nj_q9kzj49gdz1w6f5v9tw3h0000gn/T/tmp-49206kt9HWV3A8daE/node_modules/fsevents'`
// This seems to be because yarn does parallel installs and runs parallel step.
```
> fix: osx hide-bazel-files issue with fsevents

- package.json
- packages/typescript/test/strict_deps/BUILD
- packages/typescript/test/strict_deps/child.ts
- packages/typescript/test/strict_deps/child2.ts
- yarn.lock
Add missing coverage to verify that ts_library strict deps of @npm dependencies works
I added a comment as something to think about:
```
```
> test: check that ts_library @npm strict deps work

- .vscode/settings.json
- examples/jest/BUILD.bazel
- examples/jest/WORKSPACE
- examples/jest/jest.bzl
- examples/jest/package.json
- examples/jest/patches/jest-haste-map+24.9.0.patch
- examples/jest/yarn.lock
Before, the jest example macro used the `runTestsByPath` command line flag to specify test locations. Now, using a small patch to jest to enable symlinks, the more iodmatic method of using a test match glob pattern is used.
`testMatch: ['**/*.test.js']`
> feat: enable test file crawling for jest example

- internal/npm_install/npm_install.bzl
Unset YARN_IGNORE_PATH before calling yarn incase it is set so that
.yarnrc yarn-path is followed if set. This is for the case when calling
bazel from yarn with `yarn bazel ...` and yarn follows yarn-path in
.yarnrc it will set YARN_IGNORE_PATH=1 which will prevent the bazel
call into yarn from also following the yarn-path as desired.
> fix: unset YARN_IGNORE_PATH in yarn_install before calling yarn

- internal/linker/link_node_modules.bzl
- internal/linker/test/integration/BUILD.bazel
Fixes #1595.
The `elif` path in
```
if mappings[k][0] == "runfiles":
return True
elif v[0] == "runfiles":
return False
```
is now exercised by the linker integration tests.
> fix(builtin): fix logic error in linker conflict resolution

- internal/pkg_npm/packager.js
Some repos like bazelisk use a --workspace_status_command that returns tags from the repo, and their tagging scheme starts with a v prefix. We should strip that before turning it into an npm version number, which should always be numeric.
> fix(builtin): strip leading v prefix from stamp

- .circleci/config.yml
- examples/angular_bazel_architect/BUILD.bazel
- examples/angular_bazel_architect/e2e/protractor.conf.js
Adds required target and configuration to make protractor on the Angular Bazel Architect example work under bazel.
> feat(examples): add protractor angular architect

- packages/typescript/docs/install.md
"noEmit" compiler flag is not compatible with `ts_library` rule. It is helpful to explicitly call this out during installation so that anyone using that flag is aware and disables it.
- [n/a ] Tests for the changes have been added (for bug fixes / features)
- [ x] Docs have been added / updated (for bug fixes / features)
- [x ] Documentation content changes
Documentation does not mention "noEmit" compiler flag, causing possible confusion.
Issue Number: https://github.com/bazelbuild/rules_nodejs/issues/1592
Added explicit explanation that "noEmit" is incompatible with ts_library, in the installation section.
- [ x] No
> Update install.md for "noEmit" compiler flag

- examples/angular/src/BUILD.bazel
- examples/angular_view_engine/src/BUILD.bazel
In Windows `_/ts_scripts.js` will be expanded to `C:/Program Files/Git/ts_scripts.js`. 
```
[
'C:\\users\\alag\\_bazel_alag\\rj2iva3m\\external\\build_bazel_rules_nodejs\\internal\\node\\_node_bin\\node',
'C:\\users\\alag\\_bazel_alag\\rj2iva3m\\execroot\\examples_angular\\node_modules\\html-insert-assets\\src\\main.js',
'--html=src/example/index.html',
'--out=bazel-out/x64_windows-fastbuild/bin/src/index.html',
'--roots=.',
'bazel-out/x64_windows-fastbuild/bin/src',
'--assets',
'bazel-out/x64_windows-fastbuild/bin/src/styles.css',
'external/npm/node_modules/@angular/material/prebuilt-themes/deeppurple-amber.css',
'external/npm/node_modules/zone.js/dist/zone.min.js',
'./_C:/Program Files/Git/ts_scripts.js'
]
```
This seems like some character escaping issue but in general escaping is hell …
> fix: angular example ts_scripts path in Windows

- WORKSPACE
- packages/labs/src/protobufjs/ts_proto_library.bzl
- packages/labs/test/protobufjs/BUILD.bazel
- packages/labs/test/protobufjs/test.proto
- packages/labs/test/protobufjs/test.ts
This change wraps es5 sources generated with `ts_proto_library` to be wrapped in "default" mode. The "default" mode behaves like UMD, supporting both AMD and CommonJS. This change is necessary to support Node, as Node does not use AMD. Fixes #562
When using `ts_proto_library`, the application fails at runtime with `ReferenceError: define is not defined`
Issue Number: #562
Works in Node - `ts_proto_library` will now emit UMD modules instead of AMD.
> change ts_proto_library to default es5 wrapping

- e2e/ts_devserver/package.json
- e2e/ts_devserver/yarn.lock
- examples/angular/package.json
- examples/angular/yarn.lock
- examples/angular_view_engine/package.json
- examples/angular_view_engine/yarn.lock
- examples/app/package.json
- examples/app/yarn.lock
`html-insert-assets` version `0.5.0` includes the following fix: https://github.com/jbedard/html-insert-assets/pull/6 which is needed for better Windows support.
Closes #1604
> fix: html script injection is broken on windows

- .bazelci/presubmit.yml
- .circleci/bazel.rc
- .circleci/config.yml
- DEVELOPING.md
- package.json
> chore: remove local_resources flag

- examples/angular/WORKSPACE
- examples/angular_view_engine/WORKSPACE
- package.bzl
This unblocks removing install_source_map_support from nodejs_binary in the future for the 2.0 release (https://github.com/bazelbuild/rules_nodejs/pull/1464).
> build: update to rules_sass 1.25.0

- .bazelignore
This shouldn't be necessary as Bazel normally ignores this since it manages the symlink but I keep getting into a state where I can't build without doing a bazel clean in this repo with bazel complaining about the contents of bazel-out so adding this here as it prevents this from happening.
> build: add bazel-out to .bazelignore

- internal/common/expand_variables.bzl
- internal/node/npm_package_bin.bzl
A little pre-factor for when expand_variables is used in other rules where there are no outs.
> fix: logic error in expand_variables

- internal/pkg_web/BUILD.bazel
- internal/pkg_web/assembler.js
> fix(builtin): use posix paths in assembler

- internal/node/launcher.sh
- internal/node/test/BUILD.bazel
- internal/node/test/test_runfiles_helper.golden
- internal/node/test/test_runfiles_helper.js
This is for using `BAZEL_NODE_RUNFILES_HELPER ` in `bazel build` when there are no runfiles and with a tool that does not support workers. The cwd is a path such as: `/private/var/tmp/_bazel_greg/35306ad70b8da8f7bc31590523de35c0/sandbox/darwin-sandbox/18/execroot/build_bazel_rules_nodejs`.
```
export BAZEL_NODE_RUNFILES_HELPER=$(rlocation "build_bazel_rules_nodejs/internal/linker/runfiles_helper.js")
```
resolves to `/Users/greg/google/rules_nodejs/internal/linker/runfiles_helper.js` when workers are on as there is no sandbox (such as ts_library).
&
resolves to `bazel-out/host/bin/external/build_bazel_rules_typescript/internal/tsc_wrapped_bin.sh.runfiles/build_bazel_rules_nodejs/internal/linker/runfiles_helper.js` when workers are off as there is a sandbox
The latter is a relative path to …
> fix: ensure BAZEL_NODE_RUNFILES_HELPER & BAZEL_NODE_PATCH_REQUIRE are absolute

- examples/angular_bazel_architect/BUILD.bazel
- examples/angular_bazel_architect/angular.json
- examples/angular_bazel_architect/package.json
This PR adds;
1)  `lint` as a target
2) Changes npm script to use bazelisk
3) Disables `forkTypeChecker` as under Windows this currently errors out with:
```
Error: spawn C:\users\alag\_bazel_alag\jeen2jsq\external\build_bazel_rules_nodejs\internal\node\_node_bin\node ENOENT
at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
at onErrorNT (internal/child_process.js:456:16)
at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
at onErrorNT (internal/child_process.js:456:16)
at processTicksAndRejections (internal/process/task_queues.js:80:21) {
errno: 'ENOENT',
code: 'ENOENT',
syscall: 'spawn …
```
> fix(examples): add fixes to angular architect

- packages/create/index.js
Technically this could get us in trouble, if a new TS release isn't compatible with tsc_wrapped.
However we work pretty quickly to resolve these.
Fixes #1602
The alternative is we could populate this version from whatever TS we test against in this repo so we know it will work
> fix(create): use latest typescript

- examples/angular/src/index.html
This PR adds a link to the talks section of the bazel.angular.io site. The [link](https://www.youtube.com/watch?v=kzPMll6vB04&feature=youtu.be) points to the talk that [@MattMackay](https://twitter.com/MattMackay) recently gave at [AngularTorronto](https://www.youtube.com/channel/UCUlbE1BakJPBVx8OAzc5quA)
> docs(talks): add new talk slides and video link

- packages/rollup/src/rollup_bundle.bzl
- packages/rollup/test/sourcemaps/BUILD.bazel
Arguments passed to rollup. These can be used to override config file settings.
These argument are appended to the command line before all arguments that are always added by the
rule such as `--output.dir` or `--output.file`, `--format`, `--config` and `--preserveSymlinks` and
also those that are optionally added by the rule such as `--sourcemap`.
See rollup CLI docs https://rollupjs.org/guide/en/#command-line-flags for complete list of supported arguments.
> feat(rollup): add `args` attribute to rollup_bundle rule

- packages/rollup/src/rollup_bundle.bzl
As rollup_bundle already supports specific rollup flags with specific
attributes on the rollup_bundle rule, adding a boolean attribute for
silent makes the most sense.
This boolean determines if the --silent flag is added to the rollup command
when called.
I was unable to add tests for this as its change is to the stdout of the execution
of bazel, not the results of the rollup command.
> feat(rollup): add silent attr to rollup_bundle to support --silent flag

- package.json
- packages/jasmine/src/index.from_src.bzl
- packages/jasmine/src/index.js
- packages/jasmine/src/jasmine_node_test.bzl
- packages/jasmine/src/jasmine_runner.js
- packages/jasmine/src/package.json
- yarn.lock
I think this is considered a bugfix since a test runner is expected to write results to the `XML_OUTPUT_FILE`, however there was no explicit error that this is fixing. 
Currently, no test details are written to the testlogs directory, rather the output is captured via bazel core and written into a default file.
The `$XML_OUTPUT_FILE` is populated with proper test results detailing times/statuses/results from specs/suites from jasmine.
It could be considered a breaking change if a consumer has changed the param `jasmine` which defaults `@npm//@bazel/jasmine` to a different package altogether (as opposed to just changing the repository label from the default `@npm`. If a consumer has …
> Configures detailed output to XML_OUTPUT_FILE

- README.md
LogiOcean is a lead fin-tech company in China focusing on powering up analytics and business intelligence.
We are an early adoptor of Angular + Bazel. We are also mentioned as such by Brad Green on May 3rd 2019 at ng-conf.
> docs: add LogiOcean as an adaptor to README.md

- examples/angular/src/BUILD.bazel
- examples/angular_view_engine/src/BUILD.bazel
In Windows runfiles are not always available thus we need to use the real location using `rlocation`.
Closes #1606
> fix(examples): fix angular examples prod serve doesn't work on windows

- e2e/ts_devserver/package.json
- e2e/ts_devserver/yarn.lock
- examples/angular/package.json
- examples/angular/yarn.lock
- examples/angular_view_engine/package.json
- examples/angular_view_engine/yarn.lock
- examples/app/package.json
- examples/app/yarn.lock
@alexeagle we discussed this on slack a bit and I went with a change to make paths relative to the html file: https://github.com/jbedard/html-insert-assets/commit/26d7118eaa73f0a3ee2b9bbcbcdf3388b298b182
This seems to work well. The only real difference in all the example apps is the css/js files are relative (`./` instead of `/`). This way the app can be placed in a subdirectory and a `<base href>` or just plain relative paths will work correctly.
FYI @gregmagolan
> chore(examples): upgrade html-insert-assets to 0.6.0

- internal/common/module_mappings.bzl
- internal/linker/link_node_modules.bzl
- internal/node/node.bzl
- internal/npm_install/node_module_library.bzl
- packages/typescript/src/internal/devserver/ts_devserver.bzl
workspace_name function was added back in 0.21.0 looks like so we can cleanup the TODOs now.
Pre-factor for #1715.
> refactor: use new label workspace_name

- docs/index.md
- docs/install.md
> fix(docs): invalid link of examples

- packages/typescript/BUILD.bazel
- packages/typescript/replacements.bzl
- packages/typescript/src/internal/BUILD.bazel
- packages/typescript/src/internal/ts_project.bzl
- packages/typescript/src/internal/ts_project_options_validator.ts
- packages/typescript/src/package.json
- packages/typescript/test/ts_project/a/BUILD.bazel
- packages/typescript/test/ts_project/empty_intermediate/tsconfig-a.json
- packages/typescript/test/ts_project/validation/BUILD.bazel
- packages/typescript/test/ts_project/validation/a.ts
- packages/typescript/test/ts_project/validation/tsconfig.json
> Validate ts project

- internal/node/launcher.sh
- internal/node/node.bzl
- internal/node/test/BUILD.bazel
- internal/node/test/main.ts
- internal/node/test/tsconfig.json
Pre-factor out of https://github.com/bazelbuild/rules_nodejs/pull/1715
If entry point is a generated file in bazel-out nodejs_binary fails with
```
Error: Cannot find module '/private/var/tmp/_bazel/.../foobar.sh.runfiles/wksp/bazel-out/plat-form/bin/path/to/entry_point.js'
```
> fix(builtin): fix for nodejs_binary entry point in bazel-out logic

- WORKSPACE
- rules_typescript_pr_494.patch
Pre-factored out of https://github.com/bazelbuild/rules_nodejs/pull/1715
https://github.com/bazelbuild/rules_nodejs/pull/1737 should land first
Typescript PR: https://github.com/bazelbuild/rules_typescript/pull/494
> Fix typescript module mappings

- packages/typescript/src/internal/build_defs.bzl
- packages/typescript/test/target_module_attributes/BUILD.bazel
- packages/typescript/test/target_module_attributes/a.ts
- packages/typescript/test/target_module_attributes/override_output_test.js
- packages/typescript/test/target_module_attributes/tsconfig-override.json
This allows users control over the language level & module formats produced by both the dev and prod outputs of ts_library
NB: the tsconfig `bazelOpts.googmodule` if set will still override the module format to CommonJS & `bazelOpts.devmodeTargetOverride` will trump the `devmode_target` attribute so this is non-breaking. In a future major release `bazelOpts.devmodeTargetOverride ` will be removed.
Control over devmode module format is requested by @filipesilva for the angular-cli bazel migration.
> feat(typescript): add devmode_target, devmode_module, prodmode_target & prodmode_module attributes

- packages/typescript/src/internal/ts_project.bzl
- packages/typescript/test/ts_project/a/BUILD.bazel
- packages/typescript/test/ts_project/a/tsconfig-extended.json
- packages/typescript/test/ts_project/a/tsconfig.json
Allows ts_project to work with extra tsconfig indirections
Fixes #1754
> fix(typescript): include extended tsconfigs in _TsConfigInfo

- commitlint.config.js
- internal/linker/index.js
- internal/linker/link_node_modules.ts
- internal/linker/test/link_node_modules.spec.ts
- internal/node/test/BUILD.bazel
- internal/node/test/npm_package_bin.spec.js
Currently linker is linking node_modules folder in the cwd which is `runfiles/wksp/node_modules` but this location means that script in external repositories such as `runfiles/external_wksp/path/to/script.js` will not resolve packages. This PR changes the linker to link to `runfiles/node_modules`.
-----------
test added in separate commit that fails without the fix (as expected) with:
```
FAIL: //internal/node/test:npm_package_bin_test (see /private/var/tmp/_bazel_greg/35306ad70b8da8f7bc31590523de35c0/execroot/build_bazel_rules_nodejs/bazel-out/darwin-fastbuild/testlogs/internal/node/test/npm_package_bin_test/test.log)
INFO: From Testing //internal/node/test:npm_package_bin_test:
==================== Test output for //internal/node/test:npm_package_bin_test: …
```
> fix(builtin): under runfiles linker should link node_modules folder at root of runfiles tree

- examples/angular_bazel_architect/BUILD.bazel
- examples/angular_bazel_architect/projects/frontend-lib/BUILD.bazel
- internal/pkg_npm/BUILD.bazel
- internal/pkg_npm/npm_script_generator.js
- internal/pkg_npm/packager.js
- internal/pkg_npm/pkg_npm.bzl
- internal/pkg_npm/test/BUILD.bazel
- internal/pkg_npm/test/pkg_npm.spec.js
This fixes an issue where pkg_npm has a single dep which is a directory artifact but the contents of that dep are not re-rooted. Re-rooting is the expected behaviour as the only way to create a valid npm package with a package.json at the root is to re-root to the output directory of the dep as that is the only place a package.json may live in this case.
The fix is actually to not copy anything but to just forward the directory artifact dep onto the default info of pkg_npm. Some refactoring done so that the npm scripts are generated in a separate action from the package.js which is not run in the single directory artifact dep case.
**Also fixes the dependency on bazel-out symlink for the .pack & .publish scripts. Those script now contain absolute paths to the package root in bazel-out.** …
> fix(builtin): fix for pkg_npm single directory artifact dep case

- BUILD.bazel
- examples/app/test/BUILD.bazel
- index.bzl
- internal/BUILD.bazel
- internal/npm_install/npm_install.bzl
- internal/npm_version_check.js
- internal/version.bzl
- package.json
- packages/jasmine/BUILD.bazel
- packages/jasmine/src/package.json
- packages/karma/BUILD.bazel
- packages/karma/src/package.json
- packages/protractor/BUILD.bazel
- packages/protractor/src/package.json
- packages/rollup/BUILD.bazel
- packages/rollup/src/package.json
- packages/terser/BUILD.bazel
- packages/terser/src/package.json
- packages/typescript/BUILD.bazel
- packages/typescript/src/package.json
- packages/worker/BUILD.bazel
- packages/worker/package.json
- scripts/on-version.js
- tools/npm_version_check.js
- version.bzl
Adds a way to check the npm package version against the bazel rules_nodejs version ensuring they don't skew when installed at a user level.
fixes https://github.com/bazelbuild/rules_nodejs/issues/1280
> Rules nodejs version check

- internal/linker/BUILD.bazel
- internal/linker/index.js
- internal/linker/link_node_modules.ts
- internal/node/node.bzl
- third_party/github.com/bazelbuild/bazel/tools/bash/runfiles/runfiles.bash
> refactor(builtin): cleanup and optimizations in nodejs_binary & linker

- internal/npm_version_check.js
Version check hot fix.
/cc @Toxicable
> fix(builtin): fix npm_version_check.js when running outside of bazel

- internal/linker/index.js
- internal/linker/link_node_modules.ts
- internal/linker/test/link_node_modules.spec.ts
- internal/node/node.bzl
- third_party/github.com/bazelbuild/bazel/tools/bash/runfiles/runfiles.bash
Fixes #1781.
Under runfiles, the linker should symlink node_modules at `execroot/my_wksp` so that when there are no runfiles (default on Windows) and scripts run out of `execroot/my_wksp` they can resolve node_modules with standard node_module resolution.
Also, restore BAZEL_WORKSPACE name environment variable. The optimization of deriving the workspace name from the path does not work on RBE. While we can derive the workspace from the pwd when running locally because it is in the execroot path `execroot/my_wksp`, on RBE the `execroot/my_wksp` path is reduced a path such as `/w/f/b` so the workspace name is obfuscated from the path. So we provide the workspace name here as an environment variable avaiable to all actions for the runfiles helpers to use.
> fix(builtin): always symlink node_modules at `execroot/my_wksp/node_modules` even when running in runfiles

- packages/rollup/src/index.js
Node caches `require()` calls, so when we re-`require()` the potentially changed `rollup.config.cjs.js` we need to ensure it's not cached.
Basically copying: https://github.com/rollup/rollup/blob/v1.31.0/cli/run/loadConfigFile.ts#L52
> fix(rollup): fix worker not picking up config file changes

- internal/linker/test/issue_1813/BUILD.bazel
- internal/linker/test/issue_1813/index.test.js
- internal/linker/test/issue_1813/jest.config.js
- package.json
- patches/jest-haste-map+25.3.0.patch
- yarn.lock
Issue #1813 was fixed by #1800 which is already landed. #1805 also fixes via a different mechanism and will also land soon.
> test(builtin): add test for issue 1813

- .circleci/config.yml
- scripts/ci/run_integration_tests.sh
If an integration test is failing, retries can hit the no_output_time. Also add test_output=streamed to integration test CI.
> ci: increase no_output_timeout to 30m for integration job

- .circleci/config.yml
- e2e/webapp/BUILD.bazel
- examples/angular/package.json
- examples/angular/src/BUILD.bazel
- examples/angular/src/app/BUILD.bazel
- examples/angular/src/app/hello-world/BUILD.bazel
- examples/angular/src/app/home/BUILD.bazel
- examples/angular/src/app/todos/BUILD.bazel
- examples/angular/src/shared/material/BUILD.bazel
- examples/angular/yarn.lock
- internal/bazel_integration_test/bazel_integration_test.bzl
- internal/bazel_integration_test/test_runner.js
- packages/typescript/src/internal/build_defs.bzl
- packages/typescript/test/lit_plugin/BUILD.bazel
This causes hard-to-reproduce resource leaks as demonstrated in #1803
Also we didn't fully understand this before, for example if a worker process stayed running we'd never re-link under it when deps change
For now make the conservative fix to keep these two capabilities distinct
Fixes #1803
> fix(typescript): don't mix worker mode and linker

- internal/npm_install/npm_umd_bundle.bzl
To make a UMD bundle of the popular react testing library enzyme, bundling json files from @npm//entities is required
> fix(npm_umd_bundle): include all json files

- internal/node/node_patches.js
- packages/node-patches/src/fs.ts
Follow up fix to #1800.
The short-circuit logic for lstat and lstatSync needs updating after adding in guards logic. Fixes issue observed in angular-cli with webpack enhanced resolver.
> fix(builtin): fix node patches lstat short-circuit logic

- internal/node/launcher.sh
- internal/node/node.bzl
In a6e29c2add19dd487035b0951f5271053a0a11e2 we added support for generated entry_point by adding a secondary lookup.
In 863c7de48046c35dfe29f6a4f625ca3e7057b030 we reversed the order of the lookups to make rollup work in a certain use case.
Neither of these was principled, because we know ahead of time whether the entry_point is generated. We can use a single lookup.
This also makes sure that programs run in the location where the linker will put them (note that the logic in question runs before the linker has created the node_modules directory in the execroot.)
This is why #1787 observes that some node programs were broken - we were running the entry point as
bazel-out/host/bin/external/npm/@graphql-codegen/cli/bin/graphql-codegen.sh.runfiles/npm/node_modules/@graphql-codegen/cli/bin.js …
> fix(builtin): look in the execroot for nodejs_binary source entry_points

- e2e/jasmine/.bazelignore
- examples/angular/.bazelignore
- examples/angular_bazel_architect/.bazelignore
- examples/angular_view_engine/.bazelignore
- examples/app/.bazelignore
- examples/closure/.bazelignore
- examples/jest/.bazelignore
- examples/nestjs/.bazelignore
- examples/parcel/.bazelignore
- examples/protocol_buffers/.bazelignore
- examples/react_webpack/.bazelignore
- examples/vendored_node/.bazelignore
- examples/vendored_node_and_yarn/.bazelignore
- examples/web_testing/.bazelignore
- examples/webapp/.bazelignore
- packages/create/index.js
In the projects created with @bazel/create and in our examples.
Fixes issue reported on slack, where building examples/react_webpack fails on the second run
(because a glob in ts_project was picking up sources under bazel-out)
> chore: add bazel-out and dist folders to bazelignore

- README.md
It seems that `npm init @bazel` requires an argument, the name of the subdirectory which will be created. Changing the README to reflect that requirement.
The "Quickstart" section of the the README instructs users to run `npm init @bazel`, but that command, if run as specified, will print an error message that may be confusing to people who are new to Bazel.
Updates the README to say `npm init @bazel myproject`, along with a very short bit of documentation saying basically what that will do.
> Docs: Add mandatory argument to `npm init @bazel`

- internal/linker/index.js
- internal/linker/link_node_modules.ts
- internal/linker/test/local/BUILD.bazel
- internal/linker/test/local/fit/BUILD.bazel
- internal/linker/test/local/fit/main.ts
- internal/linker/test/local/fit/package.json
- internal/linker/test/local/fit/tsconfig.json
- internal/linker/test/local/test.js
```
const maybe = path.resolve(`${symlinkRoot}/external/${root}`);
if (fs.existsSync(maybe)) {
// Under runfiles, when not in the sandbox we must symlink node_modules down at the execroot
// `execroot/my_wksp/external/npm/node_modules` since `runfiles/npm/node_modules` will be a
// directory and not a symlink back to the root node_modules where we expect
// to resolve from. This case is tested in internal/linker/test/local.
return maybe;
}
// However, when in the sandbox, `execroot/my_wksp/external/npm/node_modules` does not exist,
// so we must symlink into `runfiles/npm/node_modules`. This directory exists whether legacy
// external runfiles are on or off.
return path.resolve(`${startCwd}/../${root}`)
```
What kind of change …
> fix(builtin): fix linker issue when running test with "local" tag on osx & linux

- WORKSPACE
- examples/vendored_node_and_yarn/WORKSPACE
- internal/node/node_repositories.bzl
- internal/npm_install/npm_install.bzl
- package.json
Also always symlink package.json and lock file and copy over data files to ensure that yarn_install and npm_install rerun when any of these change and to ensure that all of the labels passed to `data` are evaluated by Bazel to ensure they are regular files. A typo in a label is a very easy error to make as the label must be `//:patches/jest-haste-map+25.3.0.patch` and not `//patches:jest-haste-map+25.3.0.patch` for example if `//patches` is not a package. With this fix, Bazel will check that the labels passed to `data` are valid.
Fixes #1712
Fixes #1714
Fixes #1311
Fixes #1601
> fix(builtin): rerun yarn_install and npm_install when node version changes

- package.bzl
Someone deleted a published release from github
> ci: fix broken master

- packages/rollup/package.json
>=2.3.0 adds API support for CLI/config parsing: https://github.com/rollup/rollup/pull/3445
Is that the right commit message (feat)?
> feat(rollup): update the peerDependencies version range to >=2.3.0 <3.0.0

- docs/README.md
- docs/_includes/drawer.html
- docs/examples.md
- examples/angular/README.md
- examples/angular_bazel_architect/README.md
- examples/angular_view_engine/README.md
- examples/jest/README.md
This is mostly so that Angular devs who are pointed here by the deprecation are better able to find their way around
> docs: index of examples

- packages/labs/src/grpc_web/BUILD.bazel
- packages/labs/src/grpc_web/change_import_style.js
- packages/labs/test/grpc_web/proto/BUILD.bazel
- packages/labs/test/grpc_web/proto/pizza_service.proto
Currently there's an issue when protoc generates code using the const syntax. Previous versions of the proto compiler did not use this syntax, but newer one's do.
Update the regexp to handle const syntax.
> fix(labs): handle const/let syntax in generated protoc js

- examples/BUILD.bazel
- examples/angular/angular.json
- examples/angular/package.json
- examples/angular/yarn.lock
The package was just deprecated by angular team
> chore: remove @angular/bazel references from example

- packages/terser/index.js
Running `terser_minifed` with old version of terser does not have binary `terser` will fail to resolve binary:
```
bazel-out/k8-fastbuild/bin/build.min --config-file ... (remaining 1 argument(s) skipped)
Use --sandbox_debug to see verbose messages from the sandbox
Error: Cannot find module 'terser/bin/terser'. Please verify that the package.json has a valid "main" entry
at Function.module.constructor._resolveFilename
```
peeking it, binary resolution fallback is wrapped like below:
```
try {
} finally {
}
```
and depends on runtime, this will execute `finally` but also does not suppress exception thrown in `try` ends up execution fails. PR amends fallback to catch …
> fix(terser): allow fallback binary resolution

- docs/install.md
- internal/common/os_name.bzl
- internal/node/launcher.sh
- internal/node/node_repositories.bzl
- internal/node/test/nodejs_toolchain_test.bzl
- packages/typescript/devserver/BUILD.bazel
- toolchains/node/BUILD.bazel
Connects to #231 
A start at adding support for linux/arm64. This unblocks me for my current use-case, but there is still work to do.
When I run `bazel test //...` on an aarch64 device, currently it fails with the following output:
```
ERROR: /root/.cache/bazel/_bazel_root/c6d1af4279bc20274c5613de1579a2dc/external/io_bazel_rules_webtesting/go/metadata/main/BUILD.bazel:19:1: Configurable attribute "actual" doesn't match this configuration (would a default condition help?).
Conditions checked:
@io_bazel_rules_webtesting//common/conditions:linux
@io_bazel_rules_webtesting//common/conditions:mac
@io_bazel_rules_webtesting//common/conditions:windows
```
I think rules_webtesting needs to be updated in a similar way to add aarch64 support.
That being said, this PR shouldn't break any existing …
> Add linux arm64 support

- examples/angular/tools/angular_prerender.bzl
- internal/bazel_integration_test/BUILD.bazel
- internal/node/node.bzl
- internal/node/require_patch.js
- internal/npm_install/BUILD.bazel
- internal/npm_install/generate_build_file.ts
- internal/npm_install/index.js
- internal/npm_install/test/BUILD.bazel
- internal/npm_install/test/golden/@gregmagolan/test-a/bin/BUILD.bazel.golden
- internal/npm_install/test/golden/@gregmagolan/test-a/index.bzl.golden
- internal/npm_install/test/golden/jasmine/bin/BUILD.bazel.golden
- internal/npm_install/test/golden/jasmine/index.bzl.golden
- internal/pkg_npm/BUILD.bazel
- internal/pkg_web/BUILD.bazel
- packages/karma/BUILD.bazel
- packages/labs/protobufjs/BUILD.bazel
`install_source_map_support` attribute removed from `nodejs_binary`. `source-map-support` is vendored in at `/third_party/github.com/source-map-support` so it can always be installed.
> refactor: remove install_source_map_support from nodejs_binary since it is vendored in

- internal/js_library/js_library.bzl
- internal/providers/declaration_info.bzl
- packages/typescript/internal/ts_project.bzl
- packages/typescript/test/ts_project/js_library/BUILD.bazel
- packages/typescript/test/ts_project/js_library/a.d.ts
- packages/typescript/test/ts_project/js_library/a.js
- packages/typescript/test/ts_project/js_library/b.ts
- packages/typescript/test/ts_project/js_library/tsconfig.json
- providers.bzl
Adds a declaration_info provider factory which simplifies ts_project. Also add a ts_project test to validate that js_library be a dep to ts_project.
Removed provide_declarations() factory function for DeclarationInfo. Use declaration_info() factory function instead.
To discuss is whether or not to promote js_library to public API for 2.0?
> feat(builtin): add DeclarationInfo to js_library

- examples/protocol_buffers/app.e2e-spec.ts
- examples/protocol_buffers/app.ts
- examples/protocol_buffers/car.proto
- examples/protocol_buffers/package.json
- package.json
- packages/labs/grpc_web/change_import_style.js
- yarn.lock
Webpack had issues with the way symbols were exported from the generated esm files of grpc service definition from ts_proto_library. Specifically because the exported symbols were placed onto an imported object.
This PR exports symbols from a newly defined variable rather than attaching the symbols to an imported object.
> fix(labs): make grpc service files tree shakable

- internal/node/launcher.sh
- internal/node/npm_package_bin.bzl
- internal/node/test/BUILD.bazel
- internal/node/test/stderr_output_test.golden
- internal/node/test/stdout_output_test.golden
- internal/node/test/terser_diagnostics_stats.js
- internal/node/test/terser_input_with_diagnostics.js
- internal/providers/node_runtime_deps_info.bzl
adds `stdout` and `stderr` attributes to `npm_package_bin` and `run_node` to capture stdout into the specified file
closes #1466
> feat: add stdout capture to npm_package_bin

- e2e/BUILD.bazel
- e2e/node_loader_no_preserve_symlinks/BUILD.bazel
- e2e/packages/npm1/package-lock.json
- e2e/packages/npm2/package-lock.json
- e2e/packages/yarn1/yarn.lock
- e2e/packages/yarn2/yarn.lock
- examples/angular/tools/angular_prerender.bzl
- internal/linker/index.js
- internal/linker/link_node_modules.ts
- internal/node/launcher.sh
- packages/labs/protobufjs/BUILD.bazel
- packages/node-patches/BUILD.bazel
discussed in meeting with @soldair - we can decouple enabling the linker/node-patches from disabling the custom monkey-patched _loader.js
We should be able to always enable the linker and node-patches, while keeping the loader.js for existing code that depends on it. require()s that aren't handled by loader.js will fall through to what the linker lays out on disk.
> refactor: always link

- internal/js_library/js_library.bzl
- internal/node/node.bzl
- internal/node/npm_package_bin.bzl
- internal/npm_install/node_module_library.bzl
- internal/pkg_npm/pkg_npm.bzl
- internal/providers/js_providers.bzl
- packages/jasmine/jasmine_node_test.bzl
- packages/karma/karma_web_test.bzl
- packages/labs/grpc_web/ts_proto_library.bzl
- packages/labs/protobufjs/ts_proto_library.bzl
- packages/protractor/protractor_web_test.bzl
- packages/rollup/rollup_bundle.bzl
- packages/terser/terser_minified.bzl
- packages/terser/test/js_srcs/BUILD.bazel
- packages/terser/test/js_srcs/produces_js_as_defaultinfo.bzl
- packages/terser/test/js_srcs/src1.js
- packages/terser/test/js_srcs/src1b.js
- packages/terser/test/js_srcs/src2.js
- packages/terser/test/js_srcs/terser_spec.js
- packages/typescript/internal/build_defs.bzl
- packages/typescript/internal/ts_project.bzl
- providers.bzl
**BREAKING CHANGE**
Adds JSModuleInfo provider as the common provider for passing & consuming javascript sources and related files such as .js.map, .json, etc.
For 1.0 we added JSNamedModuleInfo and JSEcmaScriptModuleInfo which were provided by ts_library and consumed by rules that needed to differentiate between the two default flavors of ts_library outputs (named-UMD & esm). We left out JSModuleInfo as its use case was unclear at the time.
For 2.0 we're adding JSModuleInfo as generic javascript provided for the rules_nodejs ecosystem. It is not currently opinionated about the module format of the sources or the language level. Consumers of JSModuleInfo should be aware of what module format & language level is being produced if necessary.
The following rules provide JSModuleInfo:
* …
> feat(builtin): add JSModuleInfo provider

- internal/linker/link_node_modules.bzl
- internal/providers/node_runtime_deps_info.bzl
- internal/providers/test/BUILD.bazel
- internal/providers/test/_run_node_out.txt
- internal/providers/test/js-write-file.js
- internal/providers/test/run_node_test.bzl
If two `run_node` calls are made from the same rule, the module mappings files generating actions will conflict. This adds the `mnemonic` into the file name (if provide) to separate the different actions generating the files.
> fix: allow multiple run_node calls to be made from the same rule context

- packages/typescript/internal/ts_project.bzl
When TS compiles a project with JSON files, it doesn't generate `.js` or `.map` or `.d.ts`. The file is kept as is.
> fix(typescript): Exclude .json from _out_paths

- internal/linker/index.js
- internal/linker/link_node_modules.ts
- internal/linker/test/no_npm_deps/BUILD.bazel
- internal/linker/test/no_npm_deps/input.js
- internal/linker/test/no_npm_deps/no_npm_deps.bzl
Before fix:
```
ERROR: /Users/greg/google/rules_nodejs/internal/linker/test/no_third_party_deps/BUILD.bazel:3:1: Optimizing JavaScript internal/linker/test/no_third_party_deps/linker_test.js [terser] failed (Exit 1) terser.sh failed: error executing command bazel-out/host/bin/external/npm/terser/bin/terser.sh internal/linker/test/no_third_party_deps/input.js --output bazel-out/darwin-fastbuild/bin/internal/linker/test/no_third_party_deps/linker_test.js
Use --sandbox_debug to see verbose messages from the sandbox
[link_node_modules.js] manifest file bazel-out/host/bin/external/npm/terser/bin/terser.sh.runfiles/npm/terser/bin/_terser.module_mappings.json
[link_node_modules.js] manifest contents {
"workspace": "build_bazel_rules_nodejs",
"bin": "bazel-out/host/bin",
"root": …
```
> fix(builtin): fix linker bug when there are no third-party modules

- packages/typescript/internal/build_defs.bzl
If `@bazel/typescript` is a dep of ts_library such as 
```
ts_library(
name = "lib",
srcs = [
"index.ts",
],
deps = [
"@npm//@bazel/typescript",
"@npm//@microsoft/api-extractor",
"@npm//@types/node",
],
)
```
as seen in `packages/bazel/src/api-extractor/BUILD.bazel` in angular/angular, then the linker needs to include `third_party/github.com/bazelbuild/bazel/src/main/protobuf/worker_protocol.proto` as an input as worker.js will run out of its linked location in node_modules & only files that are inputs to ts_library will be there.
The failure was only observed on Angular repo RBE since running ts_library has workers on by default it is not sandboxed.
Failure mode is:
```
ERROR: /home/circleci/ng/packages/bazel/src/api-extractor/BUILD.bazel:8:11: Compiling TypeScript (devmode) …
```
> fix(typescript): add .proto files from npm deps to inputs of ts_library

- internal/node/node.bzl
Currently it breaks rules that do not provide the new `JSModuleInfo` instead of the `JSNamedModuleInfo`,
Issue Number: Fixes #1998
To be backwards compatible with earlier versions still support the `JSNamedModuleInfo` provider for nodejs_binary dependencies along with the new `JSModuleInfo`.
This should help dependencies to transition to the new provider without having to patch it.
> fix(builtin): fixes nodejs_binary to collect JSNamedModuleInfo

- internal/linker/index.js
- internal/linker/link_node_modules.ts
- internal/linker/test/link_node_modules.spec.ts
Currently the builtin linker sometimes does not generate links as
defined in the module mappings on Windows. This results in unexpected
and confusing runtime issues, and differences with other platforms.
The linker fails to generate links if module mappings result in
a different symlink/module hierarchy (as computed by `reduceModules`).
For example, consider in a previous linker run, we linked the module
`@angular/cdk/overlay` into `node_modules/@angular/cdk/overlay`. In
a second run then, we actually link `@angular/cdk`. The linker will
fail to do that as the `node_modules/@angular/cdk` folder already
exists (due to missing sandbox/runfile symlinking in windows)
We fix this by clearing such leftover linker directories so that
the newly configured module mapping can be created. In order …
> fix(builtin): linker silently not generating expected links in windows

- internal/npm_install/generate_build_file.ts
- internal/npm_install/index.js
I don't think anyone should be using a dev build for a really old bezel version
This makes the behavior consistent for new local dev builds and official releases.
> chore: treat Bazel dev builds as 2.1+ for hiding BUILD files

- internal/providers/node_runtime_deps_info.bzl
- internal/providers/test/BUILD.bazel
- internal/providers/test/js-clone-file.js
- internal/providers/test/run_node_test.bzl
`run_node`'s `inputs` param doesn't serve as a drop-in for `ctx.action.run`'s corresponding `inputs` param. The former only accepts lists, whereas `ctx.action.run` [also accepts depsets](https://docs.bazel.build/versions/master/skylark/lib/actions.html#run).
Allow `run_node` to accept depsets in the `inputs` param, as well as refactoring the creation of `inputs` for the internal `ctx.actions.run` call to build a depset, rather than a list.
This allows callers of `run_node` to avoid flattening depsets, which is usually [O(n^2) cost](https://docs.bazel.build/versions/master/skylark/performance.html#avoid-calling-depsetto_list).
> feat: add depset support to run_node inputs, matching ctx.action.run

- docs/BUILD.bazel
- internal/providers/declaration_info.bzl
- internal/providers/js_providers.bzl
- internal/providers/linkable_package_info.bzl
- internal/providers/node_runtime_deps_info.bzl
- providers.bzl
- tools/stardoc/templates/aspect.vm
- tools/stardoc/templates/provider.vm
Include the docstrings for providers and aspects that were missed from the builtins documentation page
closes #2009
> docs: update generated builtin docs to include aspects and providers

- internal/node/node.bzl
- packages/typescript/test/some_module/BUILD.bazel
- packages/typescript/test/some_module/run_node_test.bzl
- packages/typescript/test/some_module/writer.ts
Repro of issue with `run_node` replacement for `ctx.actions.run` 
(contrived) custom rule using an executable via run_node
invoked via bazel `build //packages/typescript/test/some_module:test` as `--nobazel_patch_module_resolver` is added by default by run_node, the entry_point on the executable is resolved to the ts file.
This works for `bazel run //packages/typescript/test/some_module:writer_bin` as this will patch require and resolve the
ts to js
> test: add repro case for run_node with ts_library built executable

- examples/angular_view_engine/package.json
- examples/angular_view_engine/patches/@angular+bazel+9.0.5.patch
- examples/angular_view_engine/yarn.lock
Updating @angular/bazel past 9.0.5 breaks ViewEngine which is only supported by ng_module due to https://github.com/angular/angular/pull/35841. It is recommended that Angular + Bazel users switch to Ivy and use ts_library with use_angular_plugin. See examples/angular.
> chore: update examples/angular_view_engine to @angular/bazel 9.0.5

- package.bzl
This allows users to consume the rules from source without colliding with a matching ruleset they already installed.
Note that rules_typescript devdeps were already using _maybe
> chore: change our devdeps to use _maybe

- .bazelrc
- BUILD.bazel
- internal/node/BUILD.bazel
- packages/cypress/BUILD.bazel
- packages/jasmine/BUILD.bazel
- packages/karma/BUILD.bazel
- packages/protractor/BUILD.bazel
- packages/rollup/BUILD.bazel
- packages/terser/BUILD.bazel
Sets --incompatible_restrict_string_escapes to ensure no regression is introduced, branched from https://github.com/bazelbuild/rules_nodejs/pull/2067
closes https://github.com/bazelbuild/rules_nodejs/issues/1301
> build: set --incompatible_restrict_string_escapes

- packages/labs/protobufjs/ts_proto_library.bzl
- packages/rollup/rollup_bundle.bzl
- packages/terser/terser_minified.bzl
Have the docs for rules_nodejs use the `@npm//@bazel/foo` in the examples for the load sites for different packages.
The current docs show loading them from `//packages/foo`, which causes confusion. The common case seems to be to have a external workspace called `@npm`
closes: #2092, #2087
> docs: use @npm//@bazel for example load sites

- WORKSPACE
- packages/cypress/BUILD.bazel
- packages/cypress/internal/cypress_repository.bzl
- packages/cypress/internal/install-cypress.js
- packages/cypress/internal/plugins/index.template.js
- packages/cypress/internal/run-cypress.js
- packages/cypress/internal/template.cypress_web_test.bzl
cypress_repository now fails if cypress verify fails
set the HOME env variable since cypress writes files to it
remove unused includeScreenshots / includeVideos variables
browserify files are no longer included in test output files
screenshots/videos are stored directory in TEST_UNDECLARED_OUTPUTS_DIR
> fix(cypress): allow for async cypress plugins

- docs/index.md
- examples/webapp/differential_loading.bzl
Otherwise if it's in a subfolder, babel will think it's an npm package
> fix(examples): use ./ prefix on babel config file

- packages/typescript/internal/ts_project.bzl
- packages/typescript/test/ts_project/declaration_only/BUILD.bazel
- packages/typescript/test/ts_project/declaration_only/a.d.ts_
- packages/typescript/test/ts_project/declaration_only/a.ts
- packages/typescript/test/ts_project/declaration_only/tsconfig.json
This lets you type-check a `ts_project(emit_declaration_only=True)` just by building it (its default outputs).
> fix(typescript): produce .d.ts as default output rather than empty

- internal/node/node_repositories.bzl
- scripts/update-nodejs-versions.js
This PR updates the list of NodeJS versions in `/internal/node/node_repositories.bzl` to a complete list >= `8.0.0`.
This PR also includes the script that I created to generate the repository list. If this isn't desired since it's not automatic and doesn't have tests I can remove it.
It mentions to update `/docs/install.md`, but the document doesn't seem to have a version list in it.
Currently the list of versions is incomplete, so users either need to choose an already supported version of NodeJS or create their own set of node_repositories in their WORKSPACE.
Users can specify any version >= 8.0.0 and it will just work. This will need to be updated every now and …
> Add NodeJS versions

- packages/typescript/internal/ts_project.bzl
- packages/typescript/internal/ts_project_options_validator.ts
- packages/typescript/test/ts_project/tsbuildinfofile/BUILD.bazel
- packages/typescript/test/ts_project/tsbuildinfofile/a.ts
- packages/typescript/test/ts_project/tsbuildinfofile/tsconfig.json
Like other options that affect tsc outputs, Bazel needs to know the value from the tsconfig if its set.
Add it to our validator so there's a buildozer command to sync the option value into the BUILD file.
Fixes #2137
> fix(typescript): add the tsBuildInfoFile option to ts_project

- internal/pkg_npm/pkg_npm.bzl
- packages/rollup/rollup_bundle.bzl
- providers.bzl
It can be useful if you need to turn on/off stamping per-target.
`java_binary` gives a dedicated stamp attribute for this purpose
Fixes #1693
> docs: document the node_context_data attribute

- internal/node/node_repositories.bzl
This option should not be on by default as it creates issues when running programs out of `node_modules/.bin` which are all symlinks and for these programs to work it is convention that node be able to resolve their symlinks to their actual `node_module` location.
Also, with our node patches, node will not be able to resolve a main symlink out of the sandbox anymore which was the original reason that `--preserve-symlinks-main` was set.
If users want to use this option they can still pass it to their program with `--node_options=--preserve-symlinks-main`.
> fix(builtin): don't set --preserve-symlinks-main by default

- internal/linker/link_node_modules.bzl
- internal/linker/test/workspace_link/BUILD.bazel
- internal/linker/test/workspace_link/bar/BUILD.bazel
- internal/linker/test/workspace_link/bar/main.js
- internal/linker/test/workspace_link/bar/package.json
- internal/linker/test/workspace_link/foo/BUILD.bazel
- internal/linker/test/workspace_link/foo/main.ts
- internal/linker/test/workspace_link/foo/package.json
- internal/linker/test/workspace_link/foo/tsconfig.json
- internal/linker/test/workspace_link/test.js
- internal/node/node.bzl
- internal/node/npm_package_bin.bzl
- internal/providers/node_runtime_deps_info.bzl
- packages/rollup/rollup_bundle.bzl
- packages/rollup/test/workspace_link/BUILD.bazel
- packages/rollup/test/workspace_link/bar.js
- packages/rollup/test/workspace_link/foo.js
- packages/rollup/test/workspace_link/main.js
- packages/rollup/test/workspace_link/rollup.config.js
- packages/rollup/test/workspace_link/spec.js
- packages/terser/terser_minified.bzl
- packages/typescript/internal/build_defs.bzl
- packages/typescript/internal/ts_project.bzl
Link the workspace root to the bin_dir to support absolute requires like 'my_wksp/path/to/file'.
If source files need to be required then they can be copied to the bin_dir with copy_to_bin.
> feat: add link_workspace_root to nodejs_binary, npm_package_bin, rollup_bundle, terser_minified, ts_project

- packages/rollup/index.js
- packages/rollup/test/integration/foo/BUILD.bazel
Fixes #2084
... will try adding a test still.
> fix(rollup): allow config files to override default onwarn method

- packages/terser/terser_minified.bzl
Follow up to https://github.com/bazelbuild/rules_nodejs/pull/2175. terser_minified doesn't need link_workspace_root since it never does any node_modules resolution.
> feat: link_workspace_root not needed in terser_minified

- README.md
- [ X ] Other... Please describe: Add spica to adopters
> Add spica to adopter organization list

- examples/from_source/WORKSPACE
- internal/npm_install/BUILD.bazel
- internal/npm_install/generate_build_file.ts
- internal/npm_install/index.js
- internal/npm_install/npm_install.bzl
- internal/npm_install/test/BUILD.bazel
- internal/npm_install/test/generate_build_file.spec.js
- internal/npm_install/test/package.spec.json
Issue Number: #2110
With strict_visibility enabled (currently defaults false), only dependencies within the given `package.json` file are given public visibility.
All transitive dependencies are given limited visibility, enforcing that all direct dependencies are listed in the `package.json` file.
If enabled, by setting `strict_visibility` to `True` on the `npm_install` / `yarn_install` rule, this may introduce a breaking change if not all direct dependencies are listed in the given `package.json` file. 
Currently the setting defaults to `False`, and all generated `BUILD.bazel` files are given public visibility.
> feat: add strict_visibility to npm_install / yarn_install rules

- examples/vendored_node_and_yarn/.bazelrc
- internal/node/node_repositories.bzl
Issue Number: #2185
When using vendored_node or vendored_yarn, don't add globs to the generated node_repositories `BUILD.bazel` files, allowing users to set `--incompatible_disallow_empty_glob`
> fix: don't glob yarn or node files when using vendored_node or vendored_yarn

- packages/rollup/bin/BUILD.bazel
- [ x] Bugfix
When using rules_nodejs from source, I get visibility errors:
```
WARNING: /home/doug/Development/rules_typescript_proto/test/BUILD.bazel:103:14: in rollup_bundle rule //test:test_es6_bundling: Target '//test:test_es6_bundling' violates visibility of target '@build_bazel_rules_nodejs//packages/rollup/bin:rollup-worker'. Continuing because --nocheck_visibility is active
WARNING: /home/doug/Development/rules_typescript_proto/test/BUILD.bazel:103:14: in @build_bazel_rules_nodejs//internal/providers:npm_package_info.bzl%node_modules_aspect aspect on rollup_bundle rule //test:test_es6_bundling: Target '//test:test_es6_bundling' violates visibility of target …
```
> Fixes a visibility issue with rollup-worker

- examples/create-react-app/BUILD.bazel
Fixes #2143
Issue Number:2143
`webpack-dev-server` hot reload not working. It because its watch library [chokidar](https://github.com/paulmillr/chokidar) not work in some case that contains link.
> fix(examples): prevent ibazel EOF

- internal/js_library/js_library.bzl
- internal/js_library/test/transitive/BUILD.bazel
- internal/js_library/test/transitive/a.d.ts
- internal/js_library/test/transitive/transitive_declarations_test.bzl
Transitive typings are added to typings_depsets, but we were checking
the typings array instead.
Signed-off-by: Duarte Nunes <duarte@hey.com>
Currently, a `ts_project` cannot depend on a `js_library` with transitive declaration files (such as when the `js_library` depends on another `ts_project`. This PR fixes this.
Now the `js_library` propagates declarations downstream.
> fix(builtin): js_library: correctly propagate DeclarationInfos

- internal/npm_install/npm_install.bzl
A user reports that their build file generation takes longer than 600 seconds.
It's probably a bug that we are so slow, but let's address that separately (maybe in our work for npm v7)
Also note we could have made this timeout user-configurable, but I think the extra API surface isn't worth the benefit.
Fixes #2231
> fix(builtin): give a longer timeout for _create_build_files

- package.json
Bump the allowed NodeJS version restriction in the main `package.json` file
> chore: allow node versions <= 14.14.0

- docs/index.md
Simple typo fix: packagae -> package
> "package" misspelled

- examples/app/BUILD.bazel
- packages/typescript/internal/ts_project.bzl
- packages/typescript/test/ts_project/a/BUILD.bazel
- packages/typescript/test/ts_project/b/BUILD.bazel
- packages/typescript/test/ts_project/c/BUILD.bazel
BREAKING CHANGES
ts_project extends attribute no longer accepts a list, it should be a single tsconfig.json file or a ts_config label
Fixes #2140
> chore(typescript): remove deprecated extends[]

- examples/angular_bazel_architect/README.md
Fix a typo in the readme of Angular architect example.
> docs: fix a typo of angular-architect example

- toolchains/node/BUILD.bazel
Bazel is changing how @bazel_tools/conditions:darwin is implemented.
With old implementation based on flags, it was ok to have darwin and
darwin_x86_64 in a select. This was based on flag --cpu=darwin and
--cpu=dawin_x86_64.
New implementation is based on constraints, where "darwin" means OS (and
any CPU), while "darwin_x86_64" mean only specific CPU. As such they
cannot be used in the same select, because the selection would be
ambiguous.
> Fix select with condition on darwin.

- internal/linker/test/workspace_link/BUILD.bazel
Will revisit the linker and test, but this is blocking PRs from being merged
> build: add 'fix-windows' tag due to windows flaky tests

- examples/react_webpack/BUILD.bazel
- examples/react_webpack/tsconfig.json
- internal/node/node.bzl
- packages/typescript/BUILD.bazel
- packages/typescript/internal/BUILD.bazel
- packages/typescript/internal/ts_project.bzl
- packages/typescript/internal/worker/BUILD.bazel
- packages/typescript/internal/worker/worker_adapter.js
- packages/typescript/replacements.bzl
- packages/typescript/test/ts_project/worker/BUILD.bazel
- packages/typescript/test/ts_project/worker/big.ts
Issue Number: https://github.com/bazelbuild/rules_nodejs/issues/1726
Introduce experimental `supports_workers` property on ts_project to persist worker tsc --watch processes
Unsupported on windows with current implementation which relies on suspending/resuming tsc --watch process
> feat(typescript): worker mode for ts_project

- .bazelci/presubmit.yml
- index.bzl
- internal/node/node_repositories.bzl
- internal/pkg_npm/npm_script_generator.js
- internal/pkg_npm/pkg_npm.bzl
- internal/pkg_npm/test/BUILD.bazel
- internal/pkg_npm/test/diff_pack_dir.sh
`npm_package.pack` rule not work in Windows OS since it will generate a `run_npm.sh` which is not work in Windows, so this PR will generate a `bat` file to make it workable.
> fix: npm_package.pack should work in windows os

- internal/node/node_repositories.bzl
In this commit https://github.com/bazelbuild/rules_nodejs/commit/bc36519, `npm_package.pack` supports windows, the `bat` file looks like 
```
"C:/users/jiali/_bazel_jiali/rud5dwj5/external/nodejs_windows_amd64/bin/node.cmd" "C:/users/jiali/_bazel_jiali/rud5dwj5/external/nodejs_windows_amd64/bin/nodejs/node_modules/npm/bin/npm-cli.js" pack "C:\users\jiali\_bazel_jiali\rud5dwj5\execroot\angular/bazel-out/x64_windows-fastbuild/bin/packages/zone.js/npm_package" "%*"
```
And the final "%*" become a `space` and finally the command will run as 
`npm pack package_name ""`
And it will generate an additional `undefined-0.10.0.tgz`, which is not needed at all.
This PR changed the `"%*"` to `%*`
> fix: npm_package.pack on Windows should not generate undefined.tgz

- examples/jest/yarn.lock
- internal/linker/index.js
- internal/linker/link_node_modules.ts
- internal/linker/test/workspace_link/BUILD.bazel
When resolving runfiles from MANIFEST, resolution is non-deterministic as it depends on order of entries MANIFEST if source tree or output tree is resolved to (first match is returned).
When linking link_workspace_root with no runfiles (on Windows for example), link may be to the source tree which is incorrect.
Resolving from MANIFEST is now deterministic. Resolution will prefer output tree over source tree if there is a single output tree match in the MANIFEST.
When linking link_workspace_root with no runfiles (on Windows for example), linker no longer links against source tree if there is no output tree resolution available. The solution is a generalized one so all …
> fix(builtin): make linker deterministic when resolving from manifest & fix link_workspace_root with no runfiles

- internal/node/launcher.sh
The launcher script as produced by nodejs_binary targets does forward SIGTERM/SIGINT to the child node process, however it currently does not wait for the child process to actually terminate in that case.
The reason is that `wait` command used [more details in the 3rd example here](http://veithen.io/2014/11/16/sigterm-propagation.html) terminates instantly in that case.
So the launcher script terminates, while the child process is still running.
E.g. the output of [this demo script](https://github.com/Schibum/rules_nodejs/blob/sigterm_demo/examples/sigterm_demo/demo.sh):
```bash
#!/bin/bash
launcher=`bazel run --run_under "echo " :bin`
$launcher & pid=$!; sleep 1; …
```
> fix: launcher script terminates while nodejs is still running on SIGTERM

- packages/typescript/internal/ts_project.bzl
On the 3.x branch we now have strict visibility for npm deps. The example app doesn't have protobufjs in the package.json dependencies (as it shouldn't) so we can't add `@npm//protobufjs` to the users `:tsconfig_worker` program generated by the macro.
Error was
```
ERROR: /private/var/folders/r7/2kp53v7n091gcz93xlt7wtd80000gn/T/tmp-86197YyCMi6BVlKJ1/BUILD.bazel:16:1: in nodejs_binary rule //:tsconfig_worker: target '@npm//protobufjs:protobufjs' is not visible from target '//:tsconfig_worker'. Check the visibility declaration of the former target if you think the dependency is legitimate
```
> fix(typescript): don't depend on protobufjs, it's transitive

- BUILD.bazel
- internal/pkg_npm/pkg_npm.bzl
- internal/pkg_npm/test/BUILD.bazel
- packages/rollup/rollup_bundle.bzl
- rollup_bundle config_file no longer has substitutions from a "bazel_stamp_file" - use bazel_version_file instead
- pkg_npm no longer has replace_with_version attribute, use substitutions instead
Fixes #2158
> chore: remove old stamping

- examples/jest/.bazelrc
- examples/jest/BUILD.bazel
- examples/jest/README.md
- internal/common/windows_utils.bzl
- internal/node/launcher.sh
- internal/node/test/env.spec.js
> fix(examples): fix jest example on windows

- internal/linker/index.js
- internal/linker/link_node_modules.ts
Example how this looks now:
```
[20 / 21] Bundling JavaScript bundle.js [parcel]; 4s remote-cache, darwin-sandbox
ERROR: /private/var/folders/r7/2kp53v7n091gcz93xlt7wtd80000gn/T/tmp-48948DHy4HrXTwhRy/BUILD.bazel:4:1: Bundling JavaScript bundle.js [parcel] failed (Exit 1) parcel.sh failed: error executing command bazel-out/host/bin/external/npm/parcel-bundler/bin/parcel.sh build foo.js --out-dir bazel-out/darwin-fastbuild/bin --out-file bundle.js ... (remaining 2 argument(s) skipped)
Use --sandbox_debug to see verbose messages from the sandbox
ERROR: rules_nodejs linker requires Node v10 or greater, but is running on 8.11.2
Note that earlier Node versions are no longer in long-term-support, see
https://nodejs.org/en/about/releases/
INFO: Elapsed time: 40.360s, Critical Path: 12.97s
INFO: 0 …
```
> fix(builtin): give better error when linker runs on Node <10

- package.json
I think we should use a more relaxed node engine restriction as I don't see no reason why not to allow always the most up to date LTS version being in use at the moment. \cc @alexeagle
> chore: allow node versions >=12 <=14

- third_party/github.com/bazelbuild/rules_typescript/internal/tsc_wrapped/compiler_host.ts
Facing the following error when building using Bazel typescript
```
external/build_bazel_rules_typescript/internal/BUILD.bazel:49:4: Action external/build_bazel_rules_typescript/internal/tsc_wrapped/cache.js failed (Exit 2): tsc.sh failed: error executing command bazel-out/host/bin/external/npm/typescript/bin/tsc.sh --declaration -p external/build_bazel_rules_typescript/internal/tsconfig.json --outDir ... (remaining 3 argument(s) skipped)
Use --sandbox_debug to see verbose messages from the sandbox tsc.sh failed: error executing command bazel-out/host/bin/external/npm/typescript/bin/tsc.sh --declaration -p external/build_bazel_rules_typescript/internal/tsconfig.json --outDir ... (remaining 3 argument(s) skipped)
Use --sandbox_debug to see verbose messages from the sandbox …
```
> Fix compilation issue due to string mismatch

- examples/angular/package.json
- examples/angular_bazel_architect/package.json
- examples/angular_view_engine/package.json
- examples/protocol_buffers/package.json
- examples/web_testing/package.json
- packages/concatjs/package.json
- packages/concatjs/web_test/karma_web_test.bzl
Remove the `jasmine-core` peer dep from `@bazel/concatjs`. This PR also removes it from the examples that don't use `@bazel/jasmine` to test that it's not load bearing. 
With `strict_visibility` enabled now by default, previously this would have caused bazel visibility errors.
> Remove jasmine-core as a peer dep for @bazel/concatjs

- e2e/webapp/test.js
- internal/bazel_integration_test/test_runner.js
- internal/check_bazel_version.js
- internal/npm_install/test/browserify.spec.js
- internal/npm_install/test/check.js
- internal/pkg_web/test2/spec.js
- packages/concatjs/web_test/test/karma_typescript/user_files.spec.js
- packages/create/test.js
- packages/labs/test/protobufjs/BUILD.bazel
- packages/labs/test/protobufjs/test.ts
- packages/protractor/protractor-utils.ts
- packages/protractor/protractor.conf.js
- packages/terser/test/directory-args.spec.js
- packages/terser/test/exec/spec.js
- packages/terser/test/sourcemap/terser_spec.js
Broken out from https://github.com/bazelbuild/rules_nodejs/pull/2324/files
> refactor: explicitly use runfiles helper

- packages/protractor/BUILD.bazel
- packages/protractor/package.json
- packages/protractor/test/protractor-2/on-prepare.js
- packages/protractor/test/protractor-utils/index_test.ts
- packages/protractor/test/protractor/conf.ts
This makes it 'linkable' for local consumption, so we don't rely as much on the --bazel_patch_module_resolver
patched require() function. Evidently from the examples, this is non-breaking and users can continue to deep-import the helper, though it's no longer necessary
> refactor(protractor): load protractor-utils from @bazel/protractor

- e2e/node_loader_preserve_symlinks/BUILD.bazel
- e2e/packages/BUILD.bazel
- e2e/typescript/BUILD.bazel
- examples/angular/tools/BUILD.bazel
- examples/kotlin/BUILD.bazel
- examples/user_managed_deps/BUILD.bazel
- internal/node/test/BUILD.bazel
- internal/node/test/binary_as_data/BUILD.bazel
- internal/npm_install/BUILD.bazel
- internal/npm_install/test/BUILD.bazel
- internal/pkg_npm/BUILD.bazel
- internal/pkg_web/BUILD.bazel
- packages/jasmine/test/BUILD.bazel
- packages/labs/grpc_web/BUILD.bazel
- packages/labs/test/grpc_web/BUILD.bazel
- packages/node-patches/BUILD.bazel
- packages/protractor/protractor_web_test.bzl
- packages/protractor/test/protractor-utils/BUILD.bazel
- third_party/github.com/bazelbuild/rules_typescript/internal/BUILD.bazel
We are about to flip the default for this flag in #2125 so we need to explicitly opt-in in places where we need the behavior.
Ideally most of these should be fixed, this would be necessary if we ever want to deprecate the module resolver patches
> refactor: make dependencies on --bazel_patch_module_resolver explicit

- internal/node/launcher.sh
If you turn off the linker, you're reverting to earlier rules_nodejs behavior where third-party node modules can
only be resolved using the patched require() function that knows where to find them
> fix(builtin): --nobazel_run_linker implies --bazel_patch_module_resolver

- BUILD.bazel
- examples/angular/WORKSPACE
- examples/angular_view_engine/WORKSPACE
- package.bzl
- rules_sass.issue127.patch
This includes an explicit opt-in to the --bazel_patch_module_resolver flag, which we need before flipping the default.
Note that there's some issue upstream AFAICT so I filed https://github.com/bazelbuild/rules_sass/issues/127 and patched that here
> chore: update rules_sass to latest

- CHANGELOG.md
This drops all the commits for changes in `third_party/github.com/bazelbuild/rules_typescript`. I assume we want to drop all of them? Most are ancient, but there's a couple newer ones that might actually be new changes?
* https://github.com/bazelbuild/rules_nodejs/commit/8bd9734
* https://github.com/bazelbuild/rules_nodejs/commit/02aac76
I also couldn't find where the "PiperOrigin-RevId: 221634093" came from but I assume that's super old from rules_typescript.
> chore(docs): remove old rules_typescript changes from 3.0.0-rc.0 changelog

- internal/bazel_integration_test/test_runner.js
- internal/npm_install/npm_install.bzl
To be more hermetic with the install of the dependencies use the frozen lockfile flag to install the exact version from the `yarn.lock` file.
To update a dependency use the vendored yarn binary with `bazel run @nodejs//:yarn upgrade <dep-name>`.
Fixes #941
Currently the `yarn_install` rule will use the `yarn install` command and installs the latest version that is possible in the range of the `packag.json`
Issue Number: #941
The new behaviour is using the frozen lock file option for yarn installs, this means that it will install the exact version from the `yarn.lock` file
> feat(builtin): yarn install use --frozen-lockfile as default

- internal/node/launcher.sh
NPM tools are currently run out of external/{md}/node_modules. If the
tool loads user-provided files in the execroot, which is the common
case, then this can lead to bad interactions.
Two examples of bad interactions are:
1. A tool that loads React and the user code too,
hooks becoming unusable.
2. A tool that calls into a bundler like Webpack,
potentially bundling duplicate packages.
Signed-off-by: Duarte Nunes <duarte@hey.com>
Issue Number: #2286 
A user-provided flag controls where the NPM tool is loaded from.
Tests and docs are missing, looking for early feedback.
> feat: allow running NPM tools from execroot

- internal/generated_file_test/generated_file_test.bzl
The test itself just runs diff, so it's always fast. This prevents warnings under bazel test --test_verbose_timeout_warnings
Note that the **kwargs are passed to both the binary and test targets here, so users can't pass this attribute
> fix(builtin): don't pass kwargs to generated_file_test .update binary

- package.bzl
Matches the `bazel-toolchains` version used for rbe with the bazel version to remove the DEBUG warning messages in the output
> build: match bazel-toolchains version with bazel version

- examples/angular/src/BUILD.bazel
Since rules_nodejs v3 the `--bazel_patch_module_resolver` flag is required to run the universal server
> fix(examples): angualr universal_server

- docs/Built-ins.html
- docs/Built-ins.md
- internal/js_library/js_library.bzl
`JsModuleInfo` had a typo, fixing to `JSModuleInfo`
`JsNamedModuleInfo` had a typo, fixing to `JSNamedModuleInfo`
> chore: Fix JSModuleInfo and JSNamedModuleInfo case typo in docs

- CHANGELOG.md
Add a link to the 3.0.0 migration wiki docs in the final 3.0.0 change entry
> docs: add migration wiki link to CHANGELOG

- .github/workflows/update-nodejs-versions.yml
I've been getting regular emails from my fork telling me that this
action has failed. We really only need to run this on the original
repo anyway, and we can achieve this by using the `if` option.
More info:
https://github.community/t/stop-github-actions-running-on-a-fork/17965/2
I get emails from my fork saying that this action has failed.
This action should no longer run on forks of this repo.
> fix: skip update NodeJS versions action on forks

- packages/typescript/internal/ts_project.bzl
A `host` root directory is necessary for TypeScript to resolve imports for a tool executed at build time with `cfg = "host"`.
This is necessary for:
```
some_rule = rule(
implementation = _some_rule_impl,
attrs = {
"_binary": attr.label({
default: "//some/nodejs_binary/tool/built/with/ts_project",
executable: True,
cfg = "host",
}),
},
)
```
Because Bazel will build the tool in the `host` configuration, meaning generated *.js files will be dropped into `bazel-out/host/bin/...`, and `tsc` needs to know to look for dependent `ts_project()` outputs in that directory.
Arguably a similar change is also necessary for `cfg = "exec"`, however files would be in `bazel-out/k8-opt-exec-*/bin`, which can't be easily hard-coded in a tsconfig, so that's a problem to be tackled separately.
Please check …
> docs(typescript): add `host` configuration to `rootDirs`

- internal/npm_install/npm_install.bzl
When debugging npm / yarn installs and setting the `quiet` attribute to `False` on `yarn_install` or `npm_install`, it's also helpful to pass that attribute though to the build file generation stage.
> fix(builtin): pass quiet attr though to build file generation on npm / yarn install

- internal/node/node_repositories.bzl
Removes `mirror.bazel.build` from the list of default `node_urls` used when fetching NodeJS. We don't control the bazel.build mirror, and don't think the responsibility sits with the bazel team to mirror these packages.
closes #2406
> fix: remove mirror.bazel.build from list of node_urls used to fetch NodeJS by default

- packages/concatjs/_README.md
Fix load statements in examples from the `ts_devserver` -> `concatjs_devserver` refactor
closes #2414
> docs: fix load statements in examples for concatjs_devserver

- examples/vendored_node/WORKSPACE
- examples/vendored_node/vendored.spec.js
- examples/vue/WORKSPACE
- internal/bazel_integration_test/bazel_integration_test.bzl
- internal/bazel_integration_test/test_runner.js
- internal/node/node_versions.bzl
- internal/pkg_npm/pkg_npm.bzl
- scripts/update-nodejs-versions.js
- tools/defaults.bzl
Adds support for NodeJS ^15.0.0
Main issue was captured in https://github.com/npm/cli/issues/2145, due to a breaking change in how npm handles transitive node_modules of file linked paths.
The included change here generates a tar file for the package and replaces the file path to the tar into the `package.json` under test.
closes #2339 
closes #2256
> feat: add support for NodeJS 15.x

- packages/typescript/internal/ts_project.bzl
- packages/typescript/test/ts_project/allow_js/BUILD.bazel
- packages/typescript/test/ts_project/allow_js/verify.js
.js files are not captured as outputs of ts_project if allow_js is set to true and .js files are passed as inputs
https://github.com/bazelbuild/rules_nodejs/issues/2390
This change will make .js files outputs of ts_project if allow_js is true when js files are passed in
Although this behavior is probably desired, this will break anyone who currently uses `ts_project` with `allow_js`  and passes in js files to generate typings and does not pass in an `out_dir` because bazel will say that file is both an input and output. This is technically the same behavior as running `tsc` on js files without an out_dir because it will refuse to overwrite the file but a change in how the ts_project …
> fix(typescript): capture js files in outputs of ts_project if allow_js

- internal/node/launcher.sh
- third_party/github.com/bazelbuild/bazel/tools/bash/runfiles/runfiles.bash
creating a file in the source dir leaves a mess when not running in an execroot
followup to #2409
> fix(builtin): when using chdir attribute, don't write to source dir

- internal/linker/index.js
- internal/linker/link_node_modules.ts
This latent bug was hit recently by the Angular team when upgrading to rules_nodejs 2.3.2.
The logic was clearly wrong in that a symlink with a target of `<runfiles resolution failed>` is attempted under certain conditions and then in a no-sandbox-environment, if that module had been previously linked successfully by another target, `await fs.promises.rename(tmpPath, modulePath);` would fail inside `createSymlinkAndPreserveContents`.
```
[link_node_modules.js] symlink( @angular/upgrade__linker_tmp -> <runfiles resolution failed> )
```
from larger log of 
```
link_node_modules.js] createSymlinkAndPreserveContents( @angular/upgrade )
[link_node_modules.js] symlink( @angular/upgrade__linker_tmp -> <runfiles resolution failed> )
[link_node_modules.js] symlink( …
```
> fix: linker fix for invalid symlink creation path in createSymlinkAndPreserveContents

- internal/pkg_npm/pkg_npm.bzl
- internal/pkg_npm/test/tgz_out/BUILD.bazel
- internal/pkg_npm/test/tgz_out/main.js
- internal/pkg_npm/test/tgz_out/package.json
- internal/pkg_npm/test/tgz_out/test.sh
- tools/defaults.bzl
Adds an optional attribute to the `pkg_npm` macro to generate the `.tar` target. When set, the value is used as the filename, which must end in `.tgz`. If using this, the `pkg_npm` files must include a valid `package.json` file, otherwise npm will error.
> fix(builtin): only generate a .tar pkg_npm output when requested

- index.bzl
Turns the name-only filegroup into a filegroup with sources in the published output. Visibility and deps are also forwarded.
This would allow downstream rule authors to depend on the `bzl` targets in `srcs` attributes of `bzl_library`, without imposing skylib on all users of rules_nodejs.
Slack thread context: https://bazelbuild.slack.com/archives/CA31HN1T3/p1611882849199500
> fix: forward srcs, deps and visibility of dummy_bzl_library to the filegroup when publishing

- e2e/packages/npm1/package.json
- e2e/packages/npm2/package.json
- e2e/packages/yarn1/package.json
- e2e/packages/yarn2/package.json
- internal/npm_install/generate_build_file.ts
- internal/npm_install/index.js
- internal/npm_install/npm_install.bzl
- tools/fine_grained_deps_npm/package-lock.json
- tools/fine_grained_deps_npm/package.json
- tools/fine_grained_deps_yarn/package.json
- tools/fine_grained_deps_yarn/yarn.lock
This fixes `yarn_install` & `npm_install` to copy `package.json` & lock files into the external repository to a folder that corresponds to the package.json's workspace folder and the package manager is then run out that location so that relative paths to `data` files are preserved (same as they would be outside of bazel) if the `package.json` is _not_ at the root of the WORKSPACE.
If you had a nested `package.json` and were using `yarn_install` or `npm_install` with `symlink_node_modules = False,` and passing in `data` that you were referencing during install, then you would have had to use the work-around of absolute workspace paths to the `data` files. This fix will allow you to use the same relative paths that you would use if you were running `yarn` or `npm` outside of bazel in this …
> fix: relative data paths in yarn_install & npm_install when symlink_node_modules=False and package.json is not at root

- docs/Concatjs.html
- docs/Concatjs.md
- docs/Rollup.html
- docs/Rollup.md
- docs/Terser.html
- docs/Terser.md
- docs/install.html
- packages/terser/index.js
- tools/stardoc/post-process-docs.js
It was producing wrong outputs that dropped one path segment.
Also add a better error if the terser_bin attribute is missing (when not in a repo named @npm)
> fix(docs): fix regex that replaces //packages with @bazel

- docs/Rollup.md
- packages/rollup/install.md
This is a possible docs update to mention including `rollup` itself as a dev dependency, since I ran into errors when I tried to use the rollup rules without having the `rollup` library itself installed.
> docs(rollup): mention including the rollup library in devDependencies

- packages/typescript/internal/ts_project.bzl
When the user tries to build the `ts_project` target from external repositories, the build will fail with the message that the `rootDir` is not configured correctly and some source files are missing.
```
» bazel build //demo/openapi/ui:ts_default_project
(08:57:00) INFO: Invocation ID: 659b8763-ef47-4764-a3e3-d218cad6f4ec
(08:57:00) INFO: Current date is 2021-02-11
(08:57:21) INFO: Analyzed target //demo/openapi/ui:ts_default_project (698 packages loaded, 25793 targets configured).
(08:57:21) INFO: Found 1 target...
(08:57:43) ERROR: /private/var/tmp/_bazel_antonignatov/763a2cabf15dec26eb96cb2ab1f1b9f8/external/org_bitbucket_projectplato_frontlib/lib/BUILD.bazel:21:11: Compiling …
```
> fix(typescript): fixed build for external ts_project targets

- packages/esbuild/esbuild.bzl
- packages/esbuild/test/define/BUILD.bazel
- packages/esbuild/test/define/bundle_test.js
- packages/esbuild/test/define/main.ts
`esbuild` passes global definitions as `--define=the_var=value` instead of `--define:the_var=value` [as documented](https://esbuild.github.io/api/#define).
Pass global definitions as `--define:the_var=value`.
> fix: use ':' instead of '=' for esbuild 'define' argument

- packages/esbuild/BUILD.bazel
- packages/esbuild/esbuild.bzl
- packages/esbuild/index.docs.bzl
The current esbuild doc pages only shows the wrapper macro and not the full rule. This change exports the rule under the `index.docs.bzl` pattern ready to be picked up on the next publish
> docs: export esbuild rule for docs

- package.json
- yarn.lock
Bumps the clang-format version used for formatting. While doing the docs work, the previous version does not handle the `??` operator within arrow functions correctly and produces broken code after formatting, this version fixes that.
> chore: bump clang-format version

- internal/node/require_patch.js
Performance enhancement
When using libraries like js-dom that provide a browser-like api inside nodejs, the source map support can be tricked into thinking that it is running in a browsers, which will attempt to use `XMLHttpRequest` instead of `require('fs')`. Depending on implementation of the XMLHttpRequest (presumably loaded by js-dom or alternative), this can be much slower to load source maps from disk, causing a higher latency run of nodejs. 
Even if the user is using a browser-like experience within nodejs, the nodejs implementation of source map support should always be superior, thus we should hint to the source map support to always use the nodejs fs module …
> Ensure using the nodejs source-map support

- packages/esbuild/esbuild.bzl
- packages/esbuild/test/external-flag/BUILD.bazel
- packages/esbuild/test/external-flag/bundle_test.js
- packages/esbuild/test/external-flag/main.ts
esbuild passes externals as `--external=the_dependency` instead of `--external:the_dependency` [as documented](https://esbuild.github.io/api/#external).
Pass externals as `--external:the_dependency`.
I named the test directory `external-flag` since I thought `external` might be confused with external dependencies.
The test uses `fs` as the external dependency and runs a Jasmine test to check if `console.log(fs)` appears in the bundle. This isn't strictly necessary since the bundle will fail to build if `fs` is not available, but I thought it would be best to have a test target in the PR. It might be more correct to check for `var fs = __toModule(require("fs"));`, but …
> fix: use ':' instead of '=' for esbuild 'external' argument

- commitlint.config.js
- packages/esbuild/esbuild.bzl
- packages/esbuild/test/workspace-mapping/BUILD.bazel
- packages/esbuild/test/workspace-mapping/bundle.golden.txt
- packages/esbuild/test/workspace-mapping/main.js
- packages/esbuild/test/workspace-mapping/module-one/BUILD.bazel
- packages/esbuild/test/workspace-mapping/module-one/index.js
- packages/esbuild/test/workspace-mapping/module-two/BUILD.bazel
- packages/esbuild/test/workspace-mapping/module-two/index.js
> fix(esbuild): add link_workspace_root for workspace absolute imports

- examples/esbuild/WORKSPACE
- packages/esbuild/esbuild.bzl
- packages/esbuild/esbuild_repo.bzl
- packages/esbuild/test/typescript/BUILD.bazel
- packages/esbuild/test/typescript/bundle.golden.txt
- packages/esbuild/test/typescript/generated-module/BUILD.bazel
- packages/esbuild/test/typescript/main.ts
- packages/esbuild/test/typescript/relative-module/BUILD.bazel
- packages/esbuild/test/typescript/relative-module/lib.ts
It was possible for esbuild to break out of the sandbox and find the `.ts` file inputs, this could be seen if the `.ts` file was generated, as it would live in bazel-out/
This also fixes an issue where external npm modules may not have gotten resolved correctly when bundling
Bumps the tested version of esbuild and adds the `--preserve-symlinks` flag by default. 
This will require uses to bump the version of esbuild used in their projects
> fix(esbuild): add --preserve-symlinks flag by default and npm module mappings

- packages/esbuild/esbuild.bzl
- packages/esbuild/test/alias-mapping/BUILD.bazel
- packages/esbuild/test/bundle/BUILD.bazel
- packages/esbuild/test/define/BUILD.bazel
- packages/esbuild/test/external-flag/BUILD.bazel
- packages/esbuild/test/splitting/BUILD.bazel
- packages/esbuild/test/typescript/BUILD.bazel
- packages/esbuild/test/workspace-mapping/BUILD.bazel
This option injects a `defineProperty` to existing function to keep its names for debugging purposes. 
```js
function foo () {}
Object.defineProperty(foo, 'name', {value: 'foo'})
```
This however breaks older browsers since you cannot re-define a function name.
`defineProperty` for name is no longer injected
Reference fix upstream: https://github.com/formatjs/formatjs/commit/450d3047cdffbb64a86a31240999b7f4248908db
> fix: remove `--keep-names`

- packages/esbuild/_README.md
- packages/esbuild/esbuild_repo.bzl
* Sync the esbuild version in the docs so that it matches the deps file. The version mentioned in the README did not support the `--preserve-symlinks` flag, which looks like it is required by the latest version of these esbuild rules (I got a build error stating that `--preserve-symlinks` was not a valid flag)
* Add reminders to keep these docs in sync
* Also add reminders to bump SHAs -- I tried bumping the esbuild version, and forgot to update the SHAs, but this resulted in Bazel silently using the old archive. (BTW, instead of using the `_ESBUILD_VERSION` variable, I think it might be better to hard-code the full URLs without string interpolation, so that the SHA is right in your face as you're updating the URL, and you immediately think "ah right, I need to update the SHA too." -- …
> Update esbuild version in docs

- internal/node/node.bzl
- internal/node/npm_package_bin.bzl
- internal/node/test/BUILD.bazel
- internal/node/test/env.spec.js
- internal/providers/node_runtime_deps_info.bzl
Adds an `env` property in the form a string keyed dict to `nodejs_binary`, `nodejs_test` and anything that uses the `run_node` helper (eg `npm_package_bin`).
closes #2497
> feat(builtin): add env attribute to nodejs test and binary and run_node helper

- packages/esbuild/package.json
Adds the missing postinstall check on the rules_nodejs versions. The script was included in the package, but not run.
closes #2493
> fix(esbuild): run npm version check as postinstall

- examples/esbuild/package-lock.json
- examples/esbuild/package.json
- examples/esbuild/src/BUILD.bazel
- examples/esbuild/src/main.ts
- packages/esbuild/helpers.bzl
When the esbuild rule is in the root `BUILD.bazel` file, `rule_path` is empty, splitting on this results in a list with one empty string, which is then translated into one path segment. When `rule_path` is empty, the rule is already in the correct base path.
This also adds an npm dependency to the example to exercise node_module resolution when bundling.
closes #2503
> fix(esbuild): set correct base url when rule is at root

- tools/defaults.bzl
If an `npm_package` used for packaging overrides the `substitutions` attribute, then common replacements will not be merged into the dict. These are required to remove load statements such as `bazel_skylib`
> build: ensure common substitutions are replaced on all packages by default

- packages/rollup/index.js
This works around https://github.com/rollup/rollup/issues/3874 by not using the old cache at all when this property changes. Seems weird we have to work around such a thing but I sure wasted a lot of time wondering why changes in the config file weren't being picked up by rollup.
> fix(rollup): include externals config in worker cache key

- packages/typescript/internal/build_defs.bzl
"es2019" and  "es2020" are not listed in the list of available targets, and bazel returns the following error message
> invalid value in 'devmode_target' attribute: has to be one of 'es3', 'es5', 'es2015', 'es2016', 'es2017', 'es2018' or 'esnext' instead of 'es2020'
Authorize "es2019" and  "es2020"
> Add es2019 and es2020 script targets

- third_party/github.com/bazelbuild/rules_typescript/internal/common/compilation.bzl
Otherwise, .tsx files are silently ignored from coverage output
.tsx files can be instrumented now, and are not ignored.
> Allows TSX files to be marked as instrumented

- docs/changing-rules.html
- docs/changing-rules.md
The current behavior is confusing. Linking the angular js files makes it more confusing.
> docs: clarify usage of patch-package for patching local npm dependencies

- examples/angular_bazel_architect/src/app/app-routing.module.ts
Relative routing is not used in the angular_bazel_architect example.
Parameter `relativeLinkResolution` introduced by Angular migration is
not required.
PR for change as asked in https://github.com/bazelbuild/rules_nodejs/pull/2495#discussion_r592991820
> fix(examples): remove relativeLinkResolution

- internal/common/module_mappings.bzl
- internal/js_library/js_library.bzl
- internal/js_library/test/strip_prefix/BUILD.bazel
- internal/js_library/test/strip_prefix/test.js
Solution to #2482
Open questions:
- What is the preferred name for this attr? I have called it `strip_path` but perhaps you have a preference for a different name.
- How would you like this tested? A new directory in `/e2e` or is there an existing one that it is suitable to add to?
See issue Number: #2482
The `LinkablePackageInfo` provider can now point into a subdirectory without that subdirectory being present in the import, as detailed in the issue above.
N/A
> Add strip_prefix attr to js_library

- .bazelrc
- packages/concatjs/devserver/BUILD.bazel
- toolchains/node/BUILD.bazel
See https://github.com/bazelbuild/bazel/issues/8622
> chore: incompatible_use_platforms_repo_for_constraints

- packages/esbuild/esbuild.bzl
Fixes the breakage at HEAD with the esbuild rule and bazel 2.0.0 by allowing the empty string as an input value. This is already handled in the rule, in later versions of bazel, no value being empty string was implicitly allowed.
> fix(esbuild): allow empty string as an input to sourcemap for bazel 2.x support

- package.json
- packages/jasmine/package.json
- yarn.lock
https://github.com/larrymyers/jasmine-reporters/pull/202 updated the xlmdom dependency to a version that doesn't have the security vulnerability https://github.com/advisories/GHSA-h6q6-9hqw-rwfv -- bumping the version here to pull in that dep.
> Update jasmine-reporters to fix xmldom vulnerability

- internal/js_library/js_library.bzl
Add transitive typings to runfiles provider produced by `js_library`. Allows downstream consumers that require the `.d.ts` files at runtime (eg typechecking) to access the files via the runfiles tree.
> fix(builtin): add transitive typings to runfiles provider produced by js_library

- packages/esbuild/esbuild.bzl
I've tested this change with a local patch, and it works great with or without RBE enabled. Happy to add tests if it makes sense for a change like this.
Currently esbuild `execution_requirements` are hardcoded to disable remote execution. When running a build with remote execution enabled, the esbuild action will always run locally.
If running with `--spawn_strategy=remote`, you get the following error:
```
ERROR: /Users/siggi/Code/buildbuddy/app/BUILD.bazel:13:8: Bundling Javascript app/app.mjs [esbuild] failed: No usable spawn strategy found for spawn with mnemonic Action.  Your --spawn_strategy, --genrule_strategy and/or --strategy flags are probably too strict. Visit …
```
> Propagate esbuild `no-remote-exec` from tags

- packages/esbuild/esbuild.bzl
When an esbuild rule is passed an argument like "--inject:path/in/repo.js",
this works when building in the local workspace, as esbuild is invoked
with the correct working directory. But if the esbuild rule is in
a remote workspace (eg bazel build @other_workspace//path/in:esbuild_rule),
then the path is no longer valid.
By expanding $(location ...) references in provided arguments, it allows
callers of the rule to pass arguments like the following, which work
in both local and remote repo cases:
esbuild(args = ["--inject:$(location //path/in:repo.js)"], ...)
> feat(esbuild): support location expansion in esbuild args

- packages/esbuild/helpers.bzl
An esbuild rule that ran fine in a local repo (eg bazel build //:my_esbuild_rule)
fails when built externally (eg bazel build @other_workspace//:my_esbuild_rule).
By prepending the workspace root to the bin path, the resulting base
URL works correctly in both local and remote repo invocations, allowing
esbuild output to be consumed by a different repo.
This change fixes remote repos in Bazel 4.0.0. 3.7.0 seems to require a
workspace_root.replace("external/", "") call first in order
to get the correct location. So while this patch should not break anything
that was not already broken, it only fixes/adds support for remote repos
in 4.0+.
> fix(esbuild): files not being found when building external repo

- packages/jasmine/jasmine_node_test.bzl
- packages/jasmine/test/BUILD.bazel
- packages/rollup/rollup_bundle.bzl
- packages/terser/terser_minified.bzl
Jasmine runner adds all transitive specs to active execution, which results in some specs running multiple times. 
This can be especially problematic when there are multiple `ts_projects` with test specs that depend on each other. For example:
```
ts_project(name="proj_a") → jasmine_node_test(name="test_a") // will run specs from proj_a
↓
ts_project(name="proj_b") → jasmine_node_test(name="test_b") // will run specs from proj_a and proj_b
↓
ts_project(name="proj_c") → jasmine_node_test(name="test_c") // will run specs from proj_a, proj_b and proj_c
```
Only specs from direct deps are added to active execution
> fix(jasmine): transitive specs are no longer added to the test suite

- package.bzl
Bumps the `bazel-toolchains` version to include configs for bazel 4
> build: bump bazel-toolchains version

- packages/typescript/internal/ts_project.bzl
- packages/typescript/internal/ts_project_options_validator.ts
- packages/typescript/test/ts_project/jsx/BUILD.bazel
- packages/typescript/test/ts_project/jsx/a.tsx
- packages/typescript/test/ts_project/jsx/b.jsx
- packages/typescript/test/ts_project/jsx/tsconfig.json
- packages/typescript/test/ts_project/jsx/verify-preserve.js
When tsc is instructed to preserve jsx, the emitted files have a .jsx
extension for .tsx and .jsx inputs, which means ts_project needs to be
aware of the option to properly define outputs.
The current behavior causes the `ts_project` rule to fail as it is expecting different outputs.
In the new behavior, `ts_project` is aware of the `jsx` compiler option and sets output files accordingly.
> feat(typescript): add support for "jsx: preserve" compiler option

- packages/esbuild/esbuild.bzl
- packages/esbuild/test/output/BUILD.bazel
- packages/esbuild/test/output/bundle_test.js
- packages/esbuild/test/output/main.ts
When passing 'output', esbuild throws `Error in esbuild: rule(...) got multiple values for parameter 'output'`
Fix esbuild_macro always passing the 'output' argument as generated by the rule's name even when the user provides their own 'output' argument.
I think there may also be a bug with 'output_map' since as far as I can tell, esbuild doesn't let you specify the output file for the sourcemap and always bases it off of the output file's name. Perhaps it shouldn't be an argument to the rule.
> fix(esbuild): 'output' is passed twice when used

- examples/esbuild/WORKSPACE
- packages/esbuild/_README.md
- packages/esbuild/esbuild.bzl
- packages/esbuild/esbuild_repo.bzl
- packages/esbuild/test/splitting/bundle.spec.js
- packages/esbuild/test/typescript/BUILD.bazel
- packages/esbuild/test/typescript/bundle.golden.txt
Fixes #2552
The golden change is interesting but I think makes sense... I think all those modules should be treated the same? I'm not sure why it outputs UMD, but now it's consistent.
> fix(esbuild): update to esbuild 0.11

- toolchains/node/BUILD.bazel
Enables rules_nodejs to be used in cross-compilation contexts, where
the target architecture is not supported by rules_nodejs.
rules_nodejs's default toolchains are limited via target_compatible_with,
which means they will not work when cross-compiling to Android or iOS
with --platforms for example. With this change, users can define their
own toolchain that is limited by execution platform instead of target
platform.
For example, if you're targeting an unsupported platform, but building
on a Mac, you can place the following in the local WORKSPACE:
register_toolchains("//ts/node_toolchain")
And the following in ts/node_toolchain/BUILD.bazel:
toolchain(
name = "node_toolchain",
exec_compatible_with = [
"@platforms//os:osx",
"@platforms//cpu:x86_64",
],
toolchain = …
> feat: make node toolchain_type public so new toolchains can be added

- packages/esbuild/esbuild.bzl
- packages/esbuild/test/css/BUILD.bazel
- packages/esbuild/test/css/bundle_test.js
- packages/esbuild/test/css/dep.ts
- packages/esbuild/test/css/external.css
- packages/esbuild/test/css/main.ts
When esbuild encounters an 'import "./foo.css"' reference in normal (non-splitting)
mode, it will place the contents of that file in a .css file next to the
main output .js file.
This patch adds a flag output_css, which when set to True, will declare
the created .css file as another output, so it can be consumed by other
rules.
> feat(esbuild): add output_css flag to esbuild()

- packages/esbuild/esbuild.bzl
- packages/esbuild/helpers.bzl
- packages/esbuild/test/typescript/ts_as_srcs/BUILD.bazel
- packages/esbuild/test/typescript/ts_as_srcs/main.ts
- packages/esbuild/test/typescript/ts_as_srcs/output.golden.txt
- packages/esbuild/test/typescript/ts_as_srcs/questions/BUILD.bazel
- packages/esbuild/test/typescript/ts_as_srcs/questions/index.ts
- packages/esbuild/test/typescript/ts_as_srcs/questions/wood-chuck.ts
- packages/esbuild/test/typescript/ts_as_srcs/service/index.ts
- packages/esbuild/test/typescript/ts_as_srcs/service/service.ts
- packages/esbuild/test/vanilla_js/BUILD.bazel
- packages/esbuild/test/vanilla_js/main.js
- packages/esbuild/test/vanilla_js/name.js
- packages/esbuild/test/vanilla_js/output.golden.txt
Esbuild can take `.ts` files as an input and compile to js, this change allows that, and shows that you can plumb together both `esbuild`, `ts_project` and `js_library` in novel ways to compile Typescript and bundle it.
It's a little tricky to handle the `entry_point`, as we resolve a `.ts` entrypoint to its js for the user. This change means that if a `.ts` file is passed to `entry_point` then it's expected to be in `srcs`, rather than `deps`.
As a breaking change in 4.0.0, I'd like to propose that we _don't_ automagically resolve to a `.js` input, and the user has to specify the correct extension, or at least provide a flag to flip to the new behaviour, or back to the `legacy_resolve_ts_entry_points` (I like verbose names). 
closes #2594
> feat(esbuild): allow ts / tsx files in esbuilds srcs

- packages/typescript/internal/ts_project.bzl
> fix(typescript): output path for .json in root package

- examples/esbuild/WORKSPACE
- packages/esbuild/BUILD.bazel
- packages/esbuild/_README.md
- packages/esbuild/esbuild.bzl
- packages/esbuild/esbuild_repo.bzl
- packages/esbuild/launcher.js
- packages/esbuild/test/vanilla_js/BUILD.bazel
- packages/esbuild/test/vanilla_js/main.js
- packages/esbuild/test/vanilla_js/output.golden.txt
Use `run_node` to call esbuild via a launcher rather than invoking directly. This addresses two issues:
* using `run_node` allows us to invoke the linker fist. We no longer have to teach esbuild how to resolve `node_modules`, fixing https://github.com/bazelbuild/rules_nodejs/issues/2586
* Opens up the possibility of using esbuild via an API rather than directly, allowing us to add support for plugins if needed
Currently 1st party sources are still resolved though the `jsconfig.json` file, as this does change the bundle output slightly. 
closes https://github.com/bazelbuild/rules_nodejs/issues/2586
> fix(esbuild): use run_node to call esbuild via a launcher rather than invoking directly

- packages/terser/index.js
On Node 14 with Terser 5, Terser binary will fail to to be found as `require.resolve` will error out.  See https://github.com/terser/terser/pull/971
We will fall through and attempt to do different resolve logic based on the version of Node
> fix: add support for terser 5 under node 12 and higher

- internal/pkg_npm/packager.js
- internal/pkg_web/assembler.js
- packages/rollup/install.md
- packages/rollup/test/integration/rollup.config.js
- packages/rollup/test/version_stamp/rollup.config.js
Based on Bazel's documentation, values provided through the workspace_status_command can contain
whitespace on the same line the key is defined on:
> The key names can be anything but they may only use upper case letters and underscores. The
> first space after the key name separates it from the value. The value is the rest of the line
> (including additional whitespaces).
The `parseStatusFile` utility function is updated to rely on a regex for performing this parsing to
match the described behavior.
> fix(builtin): properly parse status file value containing spaces

- internal/node/node_repositories.bzl
> fix(builtin): resolve vendored node/yarn from external repo

- third_party/github.com/bazelbuild/rules_typescript/internal/tsc_wrapped/tsc_wrapped.ts
> fix(typescript): handle .tsx inputs to angular

- examples/angular/src/BUILD.bazel
- examples/angular/src/example/index.prod.html
- examples/angular/src/prerender.ts
By default the es5 bundle created with Babel is transpiled to use require
for loading modules. This does not work with SystemJS, which is used in the
Angular example. This PR changes the transpilation to SystemJS.
Issue Number: #1869
> fix(examples): transpile Angular es5 bundle to SystemJS

- internal/node/node_repositories.bzl
This is useful for a user who doesn't use yarn at all, and has network sandboxing for their build such that the default download location isn't accessible.
> fix(builtin): gracefully handle the case of empty yarn_urls

- examples/vue/WORKSPACE
- internal/node/node_versions.bzl
- scripts/update-nodejs-versions.js
Adds 16.0.0 to the list of node versions and sets the node version to 16.0.0 for the Vue example as a smoke test
> feat(builtin): add version 16.x.x versions of NodeJS

- packages/protractor/protractor_web_test.bzl
- packages/protractor/test/protractor-2/BUILD.bazel
Currently it is not possible to specify the `protractor_web_test`
server using a configurable attribute. i.e. using `select`.
This happens because the `server` attribute is accessed directly
in the macro so that Bazel is unable to respect the `select`. We
fix this by no longer accessing the server in the macro.
> fix(protractor): unable to specify `server` as configurable attribute

- internal/node/node_repositories.bzl
This is the version debian sid currently has (https://packages.debian.org/sid/yarnpkg)
> chore(builtin): add yarn v1.22.10 to known yarn versions

- examples/angular/package.json
- examples/angular/yarn.lock
- examples/web_testing/package.json
- examples/web_testing/yarn.lock
- package.json
- packages/concatjs/package.json
- packages/concatjs/web_test/BUILD.bazel
- packages/concatjs/web_test/karma.conf.js
- packages/concatjs/web_test/test/karma/BUILD.bazel
- packages/concatjs/web_test/test/karma/coverage.spec.js
- packages/concatjs/web_test/test/karma/coverage_source.js
- packages/concatjs/web_test/test/karma/coverage_source_uncovered.js
- packages/concatjs/web_test/test/karma_typescript/BUILD.bazel
- packages/concatjs/web_test/test/karma_typescript/coverage.spec.ts
- packages/concatjs/web_test/test/karma_typescript/coverage_source.ts
- packages/concatjs/web_test/test/karma_typescript/coverage_source_uncovered.ts
- yarn.lock
This PR enables junit reports for karma_web_test, by adding karma-junit-reporter as a
peer dependency and adding an appropriate configuration that works with bazel.
BREAKING CHANGE: karma-junit-reporter is now a peer dependency of @bazel/concatjs
**It's unclear to me if this is required or if this is part of base expectation**
Issue Number: #983
Junit Report is created at path specified via the XML_OUTPUT_FILE environment variable.
karma-junit-reporter is now a peer dependency of @bazel/concatjs. Add the `karma-junit-reporter` package as a dev dependency to your project (`yarn add karma-junit-reporter --dev` or `npm install karma-junit-reporter --save-dev`).
> feat(concatjs): enable junit report for karma_web_test

- internal/linker/index.js
- internal/linker/link_node_modules.ts
Depending on whether there are generated files being stored in
`bazel-out/bin/external/npm` or not, the linker might resolve the
workspace node modules incorrectly for Windows. e.g.
consider the manifest being the followed:
```
npm/karma/bin/_karma.module_mappings.json C:/users/paul/<..>/execroot/angular_material/bazel-out/<..>/bin/external/npm/<..>`
npm/node_modules/@angular/core/index.js C:/users/paul/projects/material2/node_modules/@angular/core/index.js
```
The linker currently on Windows will resolve the NPM workspace to the
`bazel-out` directory. This is incorrect as on Windows, the node modules
are not symlinked as with linux/macOS. Hence the node modules are not
symlinked to the execroot properly and tests/builds fail due to NodeJS
imports being "faulty".
The fix is to simply use …
> fix(builtin): linker incorrectly resolves workspace `node_modules` for windows

- packages/concatjs/devserver/concatjs_devserver.bzl
If a devserver target is currently testonly and marked with the
`manual` tag (e.g. if used for e2e testing), then the `manual`
tag is not passed to all targets exposed by the ConcatJS devserver
macro. i.e. the manifest alias is exposed and results in the
manifest to be built -> which inherently means that the actual
devserver target is built even though it has the `manual` tag.
> fix(concatjs): devserver not passing through tags to all targets

- internal/npm_install/generate_build_file.ts
- internal/npm_install/index.js
- internal/npm_install/test/package.spec.json
These are identical to regular dependencies except that a failure to install them is non-fatal.
They should be visible as Bazel dependencies.
Note I didn't include peerDependencies here still. These are an indication that some consumer should install the package, and that results in a bazel-visible dependency, so I think that's working correctly
> fix(builtin): include optionalDependencies in strictly visible packages

- packages/protractor/protractor_web_test.bzl
Follow-up to 4965db6b775d99c370fe0fad7582168d55d520ec. Improves the
naming of the server runfiles depset.
> refactor(protractor): better naming for server runfiles in rule

- packages/esbuild/esbuild.bzl
- packages/esbuild/helpers.bzl
- packages/esbuild/test/entries/BUILD.bazel
- packages/esbuild/test/entries/a.ts
- packages/esbuild/test/entries/b.ts
- packages/esbuild/test/entries/bundle.spec.js
- packages/esbuild/test/entries/index.ts
Very similar to the rollup one, including copying (almost identically) the `_desugar_entry_point_names` util. The main difference is that rollup allows each entry point to have its own output file specified (see "Chunks can be named by adding an = to the provided value:" under https://rollupjs.org/guide/en/#input), where in esbuild it seems that you specify a output filename pattern which all outputted files follow: https://esbuild.github.io/api/#entry-names
In the future we can potentially add support for that `--entry-names` param, but I guess that can always be done manually today with the arbitrary `args`.
Note that the `output_dir` is now defaulted to `True` in the macro if `entry_points` is used. I'm not 100% sure if that is correct or the best way to do it? Are code splitting and …
> feat(esbuild): add support for multiple entry points

- packages/esbuild/esbuild.bzl
- packages/esbuild/test/splitting/BUILD.bazel
esbuild defaults the `--log-level` flag to `info` which includes an output file summary (I think this used to be a separate flag 🤷). This can lead to spammy build logs and redundant output under bazel as output file paths will be duplicated.
Unless overridden by the user with the `args` attribute, default the `--log-level` flag to `warning` which only includes erorrs and warnings about the build, and not the output file summary.
> feat(esbuild): default log-level flag to warning, unless overridden

- packages/esbuild/esbuild.bzl
This seems to be the last internal use of it...
> chore(esbuild): remove use of deprecated NpmPackageInfo

- index.bzl
It makes our CI slower to run all examples against all Bazel versions. Other rulesets don't seem to test backcompat at all, so it's hard to imagine anyone is actually running on Bazel 2 and using recent rules releases
> Reduce ci load

- packages/esbuild/esbuild.bzl
Seems like other rules such as rollup and terser provide this, and it makes sense. I'm not sure of the greatest way to test it though? All 3 could probably use such a test...
> fix(esbuild): provide JSModuleInfo of output bundle

- packages/esbuild/esbuild.bzl
- packages/esbuild/test/js-library/BUILD.bazel
- packages/esbuild/test/js-library/lib.jsx
- packages/esbuild/test/js-library/main.js
- packages/esbuild/test/js-library/out.golden.txt
When using esbuild with `js_library`, the entry_point may be part of the deps, therefore the path will end up in `bazel-out/` inside the sandbox where esbuild is running, however the entrypoint path will be in the sources path, leaving any relative path inputs to no longer be relative to the entrypoint file.
The reordering here forces the `resolve_entry_point` method to prefer the file that resides in the `bazel-out/` path in the sandbox.
A possible future breaking change would be to force users to list the entrypoint file(s) in either srcs or deps for the correct pathing, or remove `srcs` from esbuild, meaning all input files must be in the output tree.
> fix(esbuild): prefer finding entry_point files in deps rather than srcs

- internal/node/launcher.sh
- internal/node/test/nodejs_toolchain_test.bzl
- toolchains/node/BUILD.bazel
Fixes #2699 
Note this doesn't include updating our list of nodejs mirror download locations, so you'll still have to specify that manually in your `node_repositories` call in `WORKSPACE`
> Add darwin_arm64 (Apple Silicon) toolchain

- packages/jasmine/jasmine_runner.js
Currently unhandled promise rejection caused tests suit to pass.
**Example:**
```
yarn bazel test //packages/angular_devkit/core:core_test --test_summary=detailed --test_output=all
INFO: Analyzed target //packages/angular_devkit/core:core_test (2 packages loaded, 148 targets configured).
INFO: Found 1 test target...
Target //packages/angular_devkit/core:core_test up-to-date:
dist/bin/packages/angular_devkit/core/core_test.sh
dist/bin/packages/angular_devkit/core/core_test_loader.js
dist/bin/packages/angular_devkit/core/core_test_require_patch.js
INFO: Elapsed time: 0.357s, Critical Path: 0.02s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
PASSED: //packages/angular_devkit/core:core_test (see /private/var/tmp/_bazel_alanagius/5168427e57f204ca069c602aa7ed193 …
```
> fix(jasmine): unhanded promise rejection causes tests suit to pass

- examples/webapp/differential_loading.bzl
- examples/webapp/sourcemaps.spec.js
- examples/webapp/tsconfig.json
We no longer recommend ts_library, so our examples should reflect that
> refactor: use ts_project for webapp example

- examples/nestjs/src/BUILD.bazel
- examples/nestjs/tsconfig.json
We no longer recommend ts_library so our examples shouldn't use it
> refactor: convert nestjs example to ts_project

- examples/BUILD.bazel
- examples/from_source/BUILD
- examples/from_source/index.bzl
- examples/from_source/tsconfig.json
We no longer recommend ts_library so we shouldn't use it in examples
> refactor: convert from_source example to ts_project

- packages/typescript/internal/worker/index.js
- packages/typescript/internal/worker/worker_adapter.ts
- packages/typescript/test/ts_project/worker/second.ts
Currently, if a `ts_project` with `supports_workers = True` contains more than one file, recompilation will fail with the error `output 'xxx' was not created` for files that have not been modified. This is due to the use of the `ts.createEmitAndSemanticDiagnosticsBuilderProgram` program creation strategy, which only emits modified files, but bazel expects all defined outputs.
Initial build:
```
» bazel build //packages/typescript/test/ts_project/worker/...
INFO: Invocation ID: 3e38759e-f7b4-4f96-9194-ce8fff759c32
INFO: Analyzed 3 targets (0 packages loaded, 0 targets configured).
INFO: Found 3 targets...
INFO: Elapsed time: 0.414s, Critical Path: 0.01s
INFO: 1 process: 1 internal. …
```
> fix(typescript): fixed "output was not created" error for ts_project with supports_workers

- package.bzl
Bumps stardoc to the latest version to resolve https://github.com/bazelbuild/stardoc/issues/96, as  https://github.com/bazelbuild/bazel/issues/12286 has been merged
> build: bump stardoc to latest commit

- examples/web_testing/BUILD.bazel
- examples/web_testing/decrement.spec.ts
- examples/web_testing/decrement.ts
- examples/web_testing/setup_script.spec.ts
- examples/web_testing/setup_script.ts
- examples/web_testing/static_script.spec.ts
- examples/web_testing/tsconfig.json
- packages/typescript/internal/ts_project.bzl
We no longer recommend using ts_library so our examples shouldn't demonstrate it.
Note that for karma_web_test to work, it needs the JSNamedModuleInfo provider, so each ts_project is wrapped with a js_library that exposes the .js files to that provider. Also we add the triple-slash directive so TypeScript produces named umd outputs that work with concatjs
> refactor: convert web_testing example to ts_project

- examples/app/BUILD.bazel
- examples/webapp/differential_loading.bzl
- packages/typescript/internal/ts_project.bzl
- packages/typescript/test/ts_project/a/BUILD.bazel
- packages/typescript/test/ts_project/allow_js/BUILD.bazel
- packages/typescript/test/ts_project/b/BUILD.bazel
- packages/typescript/test/ts_project/c/BUILD.bazel
- packages/typescript/test/ts_project/declarationdir/BUILD.bazel
- packages/typescript/test/ts_project/declarationdir_with_value/BUILD.bazel
- packages/typescript/test/ts_project/js_library/BUILD.bazel
- packages/typescript/test/ts_project/json/BUILD.bazel
- packages/typescript/test/ts_project/jsx/BUILD.bazel
- packages/typescript/test/ts_project/output_group/BUILD.bazel
- packages/typescript/test/ts_project/rootdir_with_value/BUILD.bazel
- packages/typescript/test/ts_project/ts_config/BUILD.bazel
- packages/typescript/test/ts_project/tsbuildinfofile/BUILD.bazel
The previous way was kinda dumb, that targets got named 'tsconfig' just so they could have the right default value.
It also forces users to use a tsconfig attribute in *more* cases than they should, because they don't want to name their target that thing.
ts_project tsconfig attribute now defaults to just 'tsconfig.json' rather than '[name].json'
> refactor(typescript): tsconfig default to tsconfig.json

- packages/jasmine/jasmine_node_test.bzl
Pre-factor to https://github.com/bazelbuild/rules_nodejs/pull/2698 where entry point may now be a dict.
> refactor(jasmine): don't assume entry_point is a label

- .bazelrc
- internal/npm_install/npm_install.bzl
- packages/esbuild/helpers.bzl
- packages/typescript/internal/ts_config.bzl
- packages/typescript/internal/ts_project.bzl
**BREAKING CHANGE**
Switch to using `json.encode` rather than `to_json` on structs.
Can't yet flip `--incompatible_struct_has_no_methods` as other dependencies use the deprecated methods.
As the `json` and `proto` modules are only available in bazel 4.x (LTS) and above, this change removes support for any versions below 4.0.0.
> refactor: switch to using json.encode rather than to_json on structs

- .pre-commit-config.yaml
- CONTRIBUTING.md
Now matches rules_apple https://github.com/bazelbuild/rules_apple/commit/61bc7c01aeee1324dc276e4f09bba88913ab2a62
so we can be consistent for all rulesets
> chore: update pre-commit settings

- examples/cypress/BUILD.bazel
- examples/cypress/tsconfig.json
We no longer recommend ts_library so we shouldn't use it in our examples
> refactor: use ts_project in cypress example

- README.md
Update the root README with the bazel version support choices.
> docs: update supported bazel versions in README

- internal/pkg_npm/pkg_npm.bzl
npm pack writes a bunch of file output to stderr which we do not need
> chore: fix logspam from pkg_npm .tgz actions

- docs/esbuild.md
- packages/esbuild/BUILD.bazel
- packages/esbuild/esbuild.bzl
- packages/esbuild/esbuild_repositories.bzl
- packages/esbuild/helpers.bzl
- packages/esbuild/launcher.js
- packages/esbuild/test/alias-mapping/BUILD.bazel
- packages/esbuild/test/bundle/BUILD.bazel
- packages/esbuild/test/css/BUILD.bazel
- packages/esbuild/test/css/main.ts
- packages/esbuild/test/define/BUILD.bazel
- packages/esbuild/test/define/bundle_test.js
- packages/esbuild/test/define/main.ts
- packages/esbuild/test/define/shim.js
- packages/esbuild/test/external-flag/BUILD.bazel
- packages/esbuild/test/output/BUILD.bazel
- packages/esbuild/test/sourcemap/BUILD.bazel
- packages/esbuild/test/splitting/BUILD.bazel
- packages/esbuild/test/typescript/BUILD.bazel
- packages/esbuild/test/workspace-mapping/BUILD.bazel
- packages/esbuild/toolchain/BUILD.bazel
- packages/esbuild/toolchain/package-lock.json
- packages/esbuild/toolchain/package.json
- scripts/update-esbuild-versions.js
**BREAKING CHANGE**
Refactors the esbuild rule to use esbuild's API, rather than calling the CLI directly. This serves as a prefactor PR for adding plugin support.
`args` now takes a dict (was `string_list`), where the keys are the arg names from the JS API for esbuild.
`define` now takes a dict (was `string_list`), following the format of the `define` esbuild JS API.
> refactor(esbuild): refactor esbuild rule to use the esbuild API

- index.bzl
- internal/common/maybe_directory_file_path.bzl
- internal/node/node.bzl
- packages/jasmine/jasmine_node_test.bzl
This PR adds syntactical sugar to nodejs_binary, nodejs_test & jasmine_node_test entry_point such that you can specify a directory_file_path entry point with
```
entry_point = { "//directory/artifact:target": "file/path/main.js" }
```
Pre-factor to https://github.com/bazelbuild/rules_nodejs/pull/2698
> feat: support dict style directory_file_path entry_point in nodejs_binary, nodejs_test & jasmine_node_test

- internal/npm_install/npm_umd_bundle.bzl
Similar to https://github.com/bazelbuild/rules_nodejs/pull/2749, adds support for directory_file_path entry points to npm_umd_bundle.
Adds syntactical sugar such that you can specify a directory_file_path entry point with
```
entry_point = { "//directory/artifact:target": "file/path/main.js" }
```
Pre-factor to https://github.com/bazelbuild/rules_nodejs/pull/2698
> feat: support directory_file_path entry_point in npm_umd_bundle

- internal/generated_file_test/generated_file_test.bzl
Both generated targets should have the tags so they can be used for build & test filters correctly
Pre-factor from https://github.com/bazelbuild/rules_nodejs/pull/2698'
> fix(builtin): propogate tags to both generated targets in generated_file_test

- internal/node/launcher.sh
- internal/node/loader.js
- internal/node/node.bzl
Pre-factor to https://github.com/bazelbuild/rules_nodejs/pull/2698. Fixes protractor_web_test issue with directory_artifacts.
> fix(builtin): support directory_file_path entry_point in nodejs_binary & nodejs_test when --bazel_patch_module_resolver is set

- internal/node/npm_package_bin.bzl
Technically, only stderr output is valid. I had this configuration briefly https://github.com/bazelbuild/rules_nodejs/pull/2698 but then refactored it out. This bug fix came out of that.
> fix(builtin): allow for only stderr to be set on npm_package_bin

- internal/npm_install/generate_build_file.ts
- internal/npm_install/index.js
- internal/npm_install/npm_install.bzl
- internal/providers/external_npm_package_info.bzl
Small follow up to https://github.com/bazelbuild/rules_nodejs/pull/2698 with some cleanup & house keeping
> refactor: tidy after exports_directories_only change

- packages/typescript/internal/ts_project.bzl
Fixes #2762
Any advice on how to create a test for this appreciated.
- [ n/a] Docs have been added / updated (for bug fixes / features)
- [ x] Bugfix
Coverage reports are not generated when tests are built using ts_project
Issue Number: #2762 
Coverage reports are generated
- [ x] No
> fix(typescript): collect coverage in ts_project

- internal/pkg_npm/packager.js
- internal/pkg_npm/pkg_npm.bzl
- internal/pkg_npm/test/BUILD.bazel
- internal/pkg_npm/test/linking/bar/BUILD.bazel
- internal/pkg_npm/test/linking/feb/BUILD.bazel
- internal/pkg_npm/test/linking/fez/BUILD.bazel
- internal/pkg_npm/test/linking/foo/BUILD.bazel
- internal/pkg_npm/test/linking/fub/BUILD.bazel
- internal/pkg_npm/test/tgz_out/BUILD.bazel
Currently just validates that the package_name attribute matches the name in package.json (if there is one)
Fixes #2782
> feat(builtin): add validate attribute on pkg_npm

- .bazelrc
- docs/Cypress.html
- docs/Cypress.md
- examples/BUILD.bazel
- examples/cypress/.bazelrc
- packages/cypress/index.bzl
- packages/cypress/internal/cypress_repositories.bzl
Rather than using a glob to expose the extract cypress files, we expose a symlink to the directory in which those files live. This has two main benefits:
- Reduces the amount of time to construct a runfiles tree for a cypress test
- Removes the need for --experimental_inprocess_symlink_creation on MacOS
> perf(cypress): export cypress files as a single symlink

- docs/Built-ins.md
- internal/pkg_npm/pkg_npm.bzl
- packages/angular/BUILD.bazel
- packages/concatjs/BUILD.bazel
- packages/create/BUILD.bazel
- packages/cypress/BUILD.bazel
- packages/esbuild/BUILD.bazel
- packages/jasmine/BUILD.bazel
- packages/labs/BUILD.bazel
- packages/protractor/BUILD.bazel
- packages/rollup/BUILD.bazel
- packages/runfiles/BUILD.bazel
- packages/terser/BUILD.bazel
- packages/typescript/BUILD.bazel
- packages/worker/BUILD.bazel
Just follow the printed instructions to either set the right package_name or disable the validation
> chore(builtin): flip default for pkg_npm#validate

- packages/esbuild/esbuild.bzl
Transitive targets which produce only declarations can be skipped,
making the round trip time from editing a .ts(x) file to seeing
that change bundled greately reduced since tsc is not invoked.
Esbuild includes .d.ts files emitted by ts_project which requires tsc be run before esbuild
> feat(esbuild): filter ts declaration files by default

- .bazelci/presubmit.yml
- .pre-commit-config.yaml
- internal/pkg_npm/pkg_npm.bzl
- packages/jasmine/jasmine_node_test.bzl
- packages/typescript/internal/build_defs.bzl
- third_party/github.com/bazelbuild/rules_typescript/internal/common/compilation.bzl
- third_party/github.com/bazelbuild/rules_typescript/internal/common/json_marshal.bzl
- third_party/github.com/bazelbuild/rules_typescript/internal/common/module_mappings.bzl
- third_party/github.com/bazelbuild/rules_typescript/internal/common/tsconfig.bzl
tidy up a couple of warnings at the same time.
This lets us burn them down by removing exclusions.
> chore: switch buildifier lint to blocklist

- docs/Built-ins.md
- docs/Providers.md
- docs/TypeScript.md
- examples/angular/src/lib/shorten/BUILD.bazel
- examples/angular_view_engine/patches/@angular+bazel+9.0.5.patch
- examples/angular_view_engine/src/lib/shorten/BUILD.bazel
- examples/angular_view_engine/src/lib/typography/BUILD.bazel
- internal/js_library/js_library.bzl
- internal/linker/link_node_modules.bzl
- internal/pkg_npm/pkg_npm.bzl
- internal/providers/linkable_package_info.bzl
- packages/esbuild/test/bundle/BUILD.bazel
- packages/esbuild/test/entries/BUILD.bazel
- packages/esbuild/test/typescript/module-one/BUILD.bazel
- packages/esbuild/test/typescript/module-two/BUILD.bazel
- packages/typescript/internal/build_defs.bzl
- packages/typescript/test/some_module/BUILD.bazel
Resolves https://github.com/bazelbuild/rules_nodejs/issues/2450
BREAKING CHANGES:
`module_name` will no longer turn on linking for the `ts_library` target; instead `package_name` must now be specified to enable linking. `package_path` may also be specified to control the link location.
This PR includes a breaking change to simplify `module_mappings_aspect` in `internal/linker/link_node_modules.bzl` now that a `ts_library` special case is no longer needed.
NB: the alternative would be to remove linking support from `ts_library` entirely as a `js_library` or `npm_link` could be used instead, however, given that `ts_library` doesn't expose its `.js` output as the default output this would require users to use a `filegroup` with an output selector to maintain the same functionality as …
> feat: add package_name & package_path to ts_library

- internal/node/node_repositories.bzl
for our 4.0, rules_nodejs requires the current LTS of Bazel. This is a policy restriction to save us time tracking down support issues on older versions of Bazel, not a technical one. You can patch this check out locally if you really need to continue using older Bazel, but this puts you on unsupported track.
> chore: update Bazel minimum version to LTS

- docs/Built-ins.md
- examples/angular/WORKSPACE
- examples/angular_view_engine/WORKSPACE
- internal/node/node_repositories.bzl
This matches 'Recommended for most Users' on nodejs.org/en/download
> chore: update default node.js to current LTS

- internal/linker/index.js
- internal/linker/link_node_modules.ts
- internal/runfiles/index.js
- packages/runfiles/BUILD.bazel
- packages/runfiles/runfiles.ts
- packages/runfiles/test/BUILD.bazel
- packages/runfiles/test/runfile_resolution.spec.js
- packages/runfiles/test/test_fixture.md
Given the following runfile manifest:
```
src/lib/README.md /c/users/paul/projects/test/src/lib/README.md
src/lib/README.md.update <..>/bazel-out/<..>
```
If a developer intends to resolve the `README.md` file using
the `@bazel/runfiles` package, or the patched module resolution,
they will end up with a wrong path (at least on Windows where
runfiles are not symlinked).
This happens because the `Runfiles.resolve` method continues
looking for entries that start similar (even if we have a full-match).
This logic helps with finding directories, but breaks resolution
with exact matches. This commit also corrects the method name
because technically this method is used for more than resolution
of directories.
BREAKING CHANGE: The `@bazel/runfiles` `lookupDirectory` method has been
removed. Use …
> fix(builtin): runfile resolution incorrect if entry starts similarly

- docs/esbuild.md
- packages/esbuild/esbuild.bzl
- packages/esbuild/helpers.bzl
- packages/esbuild/test/entries/BUILD.bazel
- packages/esbuild/test/splitting/BUILD.bazel
Only enable code splitting when user opts into it. Previously
there was no way to produce an output directory without also
enabling code splitting.
Prior to this change, only .js and .jsm entry points could be used by esbuild
Now .ts, .tsx, and .jsx entry points can also be used
Additionally, code splitting used to enabled when output_dir was set to true. This change also introduces a new `splitting` attribute so that user's can have an output directory without also opting into code splitting
> feat(esbuild): allow for .ts, .tsx and .jsx entry points

- README.md
At [Cookies](https://cookies.co) we are very proud to be adopters of `rules_nodejs`. We were recently named one of [America's Hottest Brands of 2021](https://adage.com/HottestBrands2021) and we're excited to brag about how Bazel helped us get there.
> Add Cookies to adopters list

- packages/typescript/internal/ts_config.bzl
Currently this will result in
```
"extends": "my-tsconfig.json"
```
which causes a "module not found" typescript exception when compiling since it must be a relative reference:
```
"extends": "./my-tsconfig.json"
```
> fix(typescript): fix bug in ts_project (write_tsconfig_rule) when extending from a generated tsconfig in same folder

- docs/Built-ins.md
- examples/angular/WORKSPACE
- examples/angular_view_engine/WORKSPACE
- internal/npm_install/npm_install.bzl
- internal/npm_install/test/patches_npm/BUILD.bazel
- internal/npm_install/test/patches_npm/package.json
- internal/npm_install/test/patches_npm/package_json.patch
- internal/npm_install/test/patches_npm/test.js
- internal/npm_install/test/patches_yarn/BUILD.bazel
- internal/npm_install/test/patches_yarn/package.json
- internal/npm_install/test/patches_yarn/package_json.patch
- internal/npm_install/test/patches_yarn/test.js
- npm_deps.bzl
For easier modification of package.json over pre_install_patches.
Targetting 4.x as this uses json.encode & json.decode which is only available in bazel 4.0.0+.
Tests added. Docstrings are:
```
"package_json_remove": attr.string_list(
doc = """List of `package.json` keys to remove before running the package manager.
Keys are '.' separated. For example, a key of `dependencies.my-dep` in the list corresponds to the `package.json`
entry,
{
"dependencies": {
"my-dep": "..."
}
}
This can be used, for example, during a migration to remove first party file: deps that are required
for the non-bazel build but should not be installed via the package manager in the bazel build since
they will be reference as bazel targets instead.
NB: removals specified are performed after preinstall_patches so if …
```
> feat: add package_json_remove and package_json_replace attributes to yarn_install & npm_install

- docs/Built-ins.md
- docs/Cypress.md
- docs/Jasmine.md
- docs/TypeScript.md
- examples/angular_bazel_architect/WORKSPACE
- examples/kotlin/BUILD.bazel
- internal/common/download.bzl
- internal/common/expand_into_runfiles.bzl
- internal/common/expand_variables.bzl
- internal/common/params_file.bzl
- internal/js_library/js_library.bzl
- internal/node/node.bzl
- internal/node/node_repositories.bzl
- internal/node/npm_package_bin.bzl
- internal/node/require_patch.js
- internal/runfiles/index.js
- packages/create/index.js
- packages/cypress/internal/toolchain/cypress_toolchain.bzl
- packages/jasmine/jasmine_node_test.bzl
- packages/jasmine/jasmine_runner.js
- packages/runfiles/runfiles.ts
- packages/typescript/internal/ts_project.bzl
- toolchains/node/node_toolchain.bzl
Updates all bazel.build links to point to `main` rather than `master` URL segment
> docs: link to the 'main' URL for bazel.build docs

- internal/node/node_patches.js
- packages/node-patches/src/fs.ts
Use `null` as the non-error value for the wrapped callbacks instead of `false`.
The convention is to use `null` when calling back with no error, and
this convention is being enforced in `universalify` since
version 2.0.0.
`fs-extras` uses `universalify` to build `Promises` from the callbacks,
and the wrapper in `node_patches.js` breaks this integration.
> Don't use false as a no-error value

- packages/worker/BUILD.bazel
- packages/worker/package.json
This package is meant to be a utility required by code outside our repo, on its own release cadence.
For example, rules_sass has a sass worker program that depends on @bazel/worker.
This means that new major releases of rules_nodejs will likely be used with an older version of @bazel/worker.
We intend for the worker package to be quite stable across releases, so the check for matching major versions just makes upgrades very difficult, with no benefit.
Fixes #2807
> chore: remove version checking from @bazel/worker

- internal/npm_install/generate_build_file.ts
- internal/npm_install/index.js
In a `package.json` we can declare something close to a mapped package like `"x": "npm:x-canary@^2.0.0-canary.14",` which will actually create `node_modules/x` but the node_module pkg name will be `x-canary`. Due to the latter, the current logic will not consider the pkg to be a `direct dependency` and as such will mark its visibility as being restricted when `strict_visibilty = True` is set. 
That PR also marks a given pkg as a `direct dependency` if the `pkg._dir` could be found listed as a dependency in the `package.json`
> fix(builtin): correctly calculate pkg._directDependency when a mapped node_module is used

- docs/TypeScript.md
Runs `bazel run //docs:check_typescript.update` for the Typescript docs
> docs(typescript): update typescript docs

- internal/node/launcher.sh
Fixes a regression where $PWD was included in the MAIN variable when
FROM_EXECROOT is defined.
> fix: remove current directory prefix when running from execroot

- docs/esbuild.md
- package.json
- packages/esbuild/BUILD.bazel
- packages/esbuild/esbuild.bzl
- packages/esbuild/esbuild_config.bzl
- packages/esbuild/index.bzl
- packages/esbuild/index.docs.bzl
- packages/esbuild/launcher.js
- packages/esbuild/test/plugins/BUILD.bazel
- packages/esbuild/test/plugins/esbuild.config.mjs
- packages/esbuild/test/plugins/logo.svg
- packages/esbuild/test/plugins/main.js
- packages/esbuild/test/plugins/out.golden.txt
- packages/esbuild/test/plugins/txt-array-plugin.js
- packages/esbuild/test/plugins/words.txt
- yarn.lock
Adds support for plugins via consuming a (mostly) complete configuration block.
Users can specify a configuration file along with its dependencies on the `esbuild_config` macro, which is then referenced on the `config` attr on the `esbuild` rule.
Mostly all properties are allowed to be set within this config file, except those that matter to output tracking etc.
Plugins can either be loaded from npm or be local sources in the repo.
closes #2832
> feat(esbuild): add support for plugins via supplying a configuration file

- internal/linker/link_node_modules.bzl
- internal/linker/test/default_path/BUILD.bazel
- internal/linker/test/default_path/custom_external_npm_package_info.bzl
- internal/linker/test/default_path/default_path.js
- internal/linker/test/default_path/golden.txt
- internal/node/node.bzl
- internal/providers/external_npm_package_info.bzl
- internal/providers/node_runtime_deps_info.bzl
`ExternalNpmPackageInfo` had a `path` attribute introduced and used in
2c2cc6eec42b0f4f805fb3063920107b78f821fd, but the provider was publicly exported beforehand. Even
though all internal usages were updated to include a path, this change was shipped in `3.2.0` and
introduced an unintentional breaking change for consumers. Most notably, `rules_postcss` manually
implements this provider and does not give a `path` failing in versions `3.2.0` and up.
https://github.com/bazelbuild/rules_postcss/blob/2bd16fda40cd4bf4fbf0b477b968366ec1602103/internal/plugin.bzl#L30-L41
Solution here is to safely retrieve the `path` attribute and default to empty string at all places
it is used. A test is also introduced to ensure that a `nodejs_binary()` can depend on a custom
`ExternalNpmPackageInfo` provider …
> fix: update usages of `ExternalNpmPackageInfo.path` to be safe and default to empty string

- packages/cypress/internal/cypress_web_test.bzl
- packages/cypress/test/BUILD.bazel
- packages/cypress/test/lib_plugin.js
The `cypress_web_test` implementation uses JSNamedModuleInfo to find the plugin source.  This is fine for typescript libraries,  but fails with the following error if a `js_library` is used to package the plugin source:
```
ERROR: /Users/mtl/Development/rules_nodejs.git/packages/cypress/test/BUILD.bazel:50:17: in cypress_web_test rule //packages/cypress/test:lib_test:
Traceback (most recent call last):
File "/Users/mtl/Development/rules_nodejs.git/packages/cypress/internal/cypress_web_test.bzl", line 88, column 45, in _cypress_web_test_impl
plugin_wrapper = _cypress_plugin_wrapper(ctx)
File "/Users/mtl/Development/rules_nodejs.git/packages/cypress/internal/cypress_web_test.bzl", line …
```
> fix(cypress): add js files from JSModuleInfo to plugin wrapper sources if available

- packages/create/index.js
Skylib appears to be using the same hash as `rules_nodejs`, which definitely isn't right. Updated to use the hash referenced in [Skylib's 1.0.3 release notes](https://github.com/bazelbuild/bazel-skylib/releases/tag/1.0.3).
Without this change, Skylib is not usable when creating a new project.
```
dparker@Gryphon (~/Source)
[21-08-21 19:57:06]$ npx @bazel/create@4.0.0-rc.1 skylib_test
npx: installed 2 in 1.448s
Creating Bazel workspace skylib_test...
Successfully created new Bazel workspace at /home/dparker/Source/skylib_test
Next steps:
1. cd skylib_test
2. npm install
3. npm run build
Note that there is nothing to build, so this trivially succeeds.
4. Add contents to the BUILD.bazel file or create a new BUILD.bazel in a subdirectory.
dparker@Gryphon (~/Source)
[21-08-21 20:05:53]$ cd …
```
> fix: update Skylib hash

- package.json
- packages/concatjs/package.json
- packages/typescript/package.json
- third_party/github.com/bazelbuild/rules_typescript/internal/tsc_wrapped/package.json
- third_party/github.com/bazelbuild/rules_typescript/package.json
- yarn.lock
`tsetse` - `check-return-value` rule is returning false positives due because the short-circuit code in https://github.com/bazelbuild/rules_nodejs/blob/9b454e38f7e2bbc64f75ee9a7dcb6ff45f1c7a12/third_party/github.com/bazelbuild/rules_typescript/internal/tsetse/rules/check_return_value_rule.ts#L60-L62 is not working as expected for certain usecases.
Example:
```ts
get content() {
try {
return expect(harness.readFile(path)).withContext(`With file content for '${path}'`);
} catch (e) {
if (e.code !== 'ENOENT') {
throw e;
}
// File does not exist so always fail the expectation
return createFailureExpectation(
expect(''),
`Expected file content but file does not exist: '${path}'`,
);
}
},
```
WIll cause tsetse to fail with the bellow;
```
~~~~~~~~~~ …
```
> fix: update `tsutils` to version `3.21.0`

- scripts/update-esbuild-versions.js
Removes the dependency on `shelljs` when running the esbuild update script. This was causing the GH action to fail as we didn't perform an `npm install` during the action, and for once dependency that's already a built-in, that seems excessive.
Context https://github.com/bazelbuild/rules_nodejs/runs/3479696864?check_suite_focus=true
> fix: remove dependency on shelljs in esbuild-update script

- docs/Built-ins.md
- internal/node/node_repositories.bzl
Add `use_nvmrc` attribute on `node_repositories` to provide a Label pointing to the local .nvmrc file in the repository.
> feat(builtin): add support for using a local .nvmrc file for providing a node version

- internal/common/os_name.bzl
Moves closer to throwing away that helper, as skylib has a built-in to assert on the bazel version
> refactor: os_name.bzl no longer depends on check_version.bzl

- packages/cypress/test/BUILD.bazel
This should avoid the EADDRINUSE: address already in use 127.0.0.1:3000 error on CI
> chore: tag cypress tests exclusive

- internal/pkg_npm/packager.js
- internal/pkg_npm/pkg_npm.bzl
- internal/pkg_npm/test/BUILD.bazel
- internal/pkg_npm/test/diff_pack_dir.sh
- internal/pkg_npm/test/pkg_npm.spec.js
- internal/pkg_npm/test/transition/BUILD.bazel
- internal/pkg_npm/test/transition/index.bzl
The `pkg_npm` rule is currently using some basic computation to
determine output paths from action inputs. This logic is prone to
mistakes and also does not work well with inputs that have been
built as part of transitioned targets. e.g. The devserver binaries
for `@bazel/concatjs` are currently built using a 1:3 transition
where each devserver binary is built in a different Bazel output
directory fragment. e.g.
bazel-out/darwin-fastbuild-ST-05b09dfdd2e5
bazel-out/darwin-fastbuild-ST-b60b0173fed1
bazel-out/darwin-fastbuild-ST-fce3d0422d3b
https://unpkg.com/browse/@bazel/concatjs@4.1.0/bazel-out/
The `pkg_npm` rule needs to be able to properly compute
output paths regardless of the output directory fragment.
The solution to the problem is that the package rule should
pass relevant …
> fix(builtin): pkg_npm unable to copy files from transitioned actions

- internal/linker/link_node_modules.bzl
- internal/node/node.bzl
- packages/esbuild/esbuild.bzl
This commit does two things:
1. It switches the `link_node_modules` aspect from the deprecated
struct provider variant to the provider list return value.
2. The aspect no longer collects aspect results from dependencies
if the target already provides explicit mapping information for the
linker. This allows consumers to stop propagation of the aspect.
This is an API for advanced use-cases as outlined in
https://github.com/bazelbuild/rules_nodejs/issues/2941.
> feat(builtin): add support for stopping propagation of `link_node_modules` aspect

- docs/TypeScript.md
- packages/typescript/internal/ts_project.bzl
This PR excludes `**/package.json` and `**/package-lock.json` from the default value for `srcs`. This seems like a very common case that would make the default unusable when `resolveJsonModule` is on.
An NPM project using TypeScript with the `resolveJsonModule` set to true, not specifying `srcs` to the `ts_project` rule causes errors such as:
```
output 'package-lock.json' was not created
output 'package.json' was not created
```
Files matching the globs `**/package.json` or `**/package-lock.json` are excluded.
This is a breaking change if anyone is relying on the existing behavior of including `package.json` or similarly-named files.
> fix(typescript): exclude package.json and package-lock.json from default ts_project srcs

- docs/debugging.md
In the August 2021 update, legacy debuggers have been dropped from vscode, leaving us with the new `vscode-js-debug` plugin that introduces a number of breaking changes.
In order to properly hit breakpoints with the new `vscode-js-debug` plugin, the option `resolveSourceMapLocations` needs to be set to `null` so it can resolve sourcemaps outside of the workspace location. Otherwise the transpiled js files will be used. 
See question in: https://github.com/microsoft/vscode-js-debug/issues/1105
> New vscode-js-debug plugin

- internal/node/node_patches.js
- packages/node-patches/src/fs.ts
callback methods in the `node_patches.js` use false instead of null for the error parameter. This seems to trip some 3rd party packages that are comparing the first value with null and thus report `false` error ...
e.g https://github.com/RyanZim/universalify/blob/master/index.js#L11
callback methods in the `node_patches.js` should use a null value  for the error parameter
> fix patch callback

- third_party/github.com/bazelbuild/rules_typescript/internal/BUILD.bazel
- third_party/github.com/bazelbuild/rules_typescript/internal/tsc_wrapped/angular_plugin.ts
- third_party/github.com/bazelbuild/rules_typescript/internal/tsc_wrapped/perf_trace.ts
- third_party/github.com/bazelbuild/rules_typescript/internal/tsc_wrapped/tsc_wrapped.ts
As of v13, the `@angular/compiler-cli` package will come as strict ESM
package. This means that the import currently in `tsc_wrapped` does
not work for v13+ of Angular. This commit adds an interop allowing for
both the ESM variant, and CJS variant of the Angular compiler to work.
> feat(typescript): support for ESM variant of the Angular compiler plugin

- docs/Cypress.md
- packages/cypress/internal/cypress_web_test.bzl
Fixes #2976
Could use some test coverage, any cypress_web_test with no `plugin_file` attribute in the repo would be enough
> fix(cypress): use correct label to reference plugins/base.js

- common.bazelrc
- docs/Concatjs.md
- docs/Protractor.md
- examples/angular/WORKSPACE
- examples/angular_view_engine/WORKSPACE
- examples/web_testing/WORKSPACE
- package.bzl
- packages/concatjs/index.docs.bzl
- packages/concatjs/web_test/karma.conf.js
- packages/protractor/index.bzl
- packages/protractor/package.bzl
Updates to the latest version of `rules_webtesting` that comes with
M1 macOS browser support, RBE/exec platform selection fixes and better
caching of the browser (and tool) binaries.
https://github.com/bazelbuild/rules_webtesting/commit/6b2ef24cfe95d6e31d5e61414949ff8f0f184b13
> build: update rules_webtesting to latest version supporting m1 browsers

- packages/esbuild/esbuild.bzl
- packages/esbuild/test/testonly/BUILD.bazel
- packages/esbuild/test/testonly/lib.jsx
- packages/esbuild/test/testonly/main.js
- packages/esbuild/test/testonly/out.golden.txt
- N/A: Docs have been added / updated (for bug fixes / features)
Fix esbuild error when depending on testonly targets.
When an esbuild target with non-empty `args` is marked as `testonly`, it does not mark its `params_file` as testonly. This causes the following error when it depends on another `testonly` target:
```
ERROR: /home/[username]/rules_nodejs/packages/esbuild/test/testonly/BUILD.bazel:16:8: in _params_file rule //packages/esbuild/test/testonly:bundle_args: non-test target '//packages/esbuild/test/testonly:bundle_args' depends on testonly target '//packages/esbuild/test/testonly:main' and doesn't have testonly attribute set
```
No error.
> fix(esbuild): fix depending on testonly targets 

- package.json
- packages/jasmine/package.json
- yarn.lock
N/A
Currently, `@bazel/jasmine` uses a version of `jasmine-reporters` that has a downstream vulnerability in `xmldom`
`jasmine-reporters` has been updated, which uses `@xmldom/xmldom`, which has the vulnerability patched
> fix: update jasmine-reporters to v2.5.0 to fix xmldom vulnerability

- third_party/github.com/bazelbuild/rules_typescript/internal/tsc_wrapped/angular_plugin.ts
- third_party/github.com/bazelbuild/rules_typescript/internal/tsc_wrapped/tsc_wrapped.ts
Unfortunately my initial refactor to allow for the ESM variant of the
compiler-cli did not contain a workaround for an issue that is caused
by TypeScript. Currently the import is rewritten to a dynamic require,
preventing the ESM variant of the compiler-cli to work. This commit
fixes this in a similar way we have made `@angular/cli` compatible with
the ESM-variant of Angular v13 packages.
> fix(typescript): typescript downleveling breaking ESM variant of Angular v13 compiler

- nodejs/BUILD.bazel
- third_party/github.com/bazelbuild/bazel-skylib/BUILD
allows downstream rules to run stardoc
> fix(docs): expose correct bzl_library targets

- e2e/bazel_managed_deps/WORKSPACE
- e2e/concatjs_devserver/WORKSPACE
- e2e/fine_grained_symlinks/WORKSPACE
- e2e/jasmine/WORKSPACE
- e2e/node_loader_no_preserve_symlinks/WORKSPACE
- e2e/node_loader_preserve_symlinks/WORKSPACE
- e2e/nodejs_repository/WORKSPACE
- e2e/packages/WORKSPACE
- e2e/webapp/WORKSPACE
- examples/angular_bazel_architect/WORKSPACE
- examples/closure/WORKSPACE
- examples/cypress/WORKSPACE
- examples/esbuild/WORKSPACE
- examples/jest/WORKSPACE
- examples/parcel/WORKSPACE
- examples/react_webpack/WORKSPACE
- examples/vendored_node/WORKSPACE
- examples/vendored_node_and_yarn/WORKSPACE
- examples/vue/WORKSPACE
- examples/worker/WORKSPACE
- index.bzl
This allows us to always publish regular bzl_library targets. We can also stop carefully vendoring skylib and shipping our own copy.
Eventually we would run into a provider problem, where our vendored copy doesn't have the same provider symbol as the real repo.
build_bazel_rules_nodejs now depends on bazel_skylib.
You can install it in your WORKSPACE directly, or use our helper macro like so:
> refactor: depend on bazel-skylib at runtime

- internal/linker/index.js
- internal/linker/link_node_modules.ts
resolves: https://github.com/bazelbuild/rules_nodejs/issues/3054
This restores the linker behaviour from 4.4.1.
The problem seems to be that after the refactor in 4.4.2, the linker is now creating a node_modules symlink at the root of the bazel-out tree where as before the refactor it wasn't.
In short, in 4.4.2 there is now node_modules symlinked at,
`execroot/<wksp>/bazel-out/darwin-fastbuild/bin/node_modules` -> `execroot/<wksp>/node_modules`
while in 4.4.1 this wasn't created.
The error for the nextjs build AFAICT is that it is resolving react to the two different node_modules trees in the build which is breaks the react build. React requires a single version at a single node_modules location. I've seen the error produced by next.js before due to this problem in another scenario:
``` …
```
> fix: #3054 regression in linker behavior in 4.4.2

- internal/linker/index.js
- internal/linker/link_node_modules.ts
- internal/linker/test/link_node_modules.spec.ts
- internal/node/launcher.sh
- internal/node/test/env.spec.js
This is a follow up to the linker refactor in 4.4.2 meant to solve an issue with ibazel and the linker.
Bazel will delete the root execroot node_modules symlink on rebuild in the ibazel run context so from runfiles we shouldn't link to there.
cc @mrmeku
> fix: don't link runfiles node_modules to execroot node_modules if there is an external workspace node_modules

- internal/js_library/js_library.bzl
- internal/js_library/test/strip_prefix/BUILD.bazel
- internal/js_library/test/strip_prefix/external_test.js
- npm_deps.bzl
Failure without the fix in `js_library.bzl`:
```
ERROR: /private/var/tmp/_bazel_gmagolan/e172f8159a8fef9694f6bd1b99308c59/external/npm/BUILD.bazel:57066:11: in _js_library rule @npm//:testy_copy_js_library: 
Traceback (most recent call last):
File "/Users/gmagolan/oss/rules_nodejs/internal/js_library/js_library.bzl", line 243, column 30, in _impl
path = _link_path(ctx, all_files),
File "/Users/gmagolan/oss/rules_nodejs/internal/js_library/js_library.bzl", line 120, column 17, in _link_path
fail("js_library %s strip_prefix path does not contain any of the provided sources" % ctx.label)
Error in fail: js_library @npm//:testy_copy_js_library strip_prefix path does not contain any of the provided sources
ERROR: Analysis of target '//internal/js_library/test/strip_prefix:external_test' failed; …
```
> fix(builtin): handle external repository file paths in js_library strip_prefix check

- docs/esbuild.md
- packages/esbuild/esbuild.bzl
- packages/esbuild/launcher.js
- packages/esbuild/test/metafile/BUILD.bazel
- packages/esbuild/test/metafile/test.sh
`esbuild` always generates `*._metadata.json` file.
The new option `metafile` can turn of generation of the _metafile_.
This might be useful if one would like to inject the output into html as possible with `@bazel/rollup`.
> feat(esbuild): add option to disable metafile generation

- internal/js_library/js_library.bzl
- packages/typescript/test/ts_project/directory_declarations/BUILD.bazel
- packages/typescript/test/ts_project/directory_declarations/b.ts
- packages/typescript/test/ts_project/directory_declarations/lib/a.d.ts
Error in the test case without the fix:
```
ERROR: /Users/greg/oss/rules_nodejs/packages/typescript/test/ts_project/directory_declarations/BUILD.bazel:25:11: in deps attribute of ts_project rule //packages/typescript/test/ts_project/directory_declarations:b: '//packages/typescript/test/ts_project/directory_declarations:lib_js_library' does not have mandatory providers: 'DeclarationInfo' or '_ValidOptionsInfo'. Since this rule was created by the macro 'ts_project_macro', the error might have been caused by the macro implementation
ERROR: Analysis of target '//packages/typescript/test/ts_project/directory_declarations:b' failed; build aborted: Analysis of target '//packages/typescript/test/ts_project/directory_declarations:b' failed
```
> fix(builtin): provide a DeclarationInfo from js_library is any input files are directories (TreeArtifacts)

- docs/TypeScript.md
- packages/typescript/internal/ts_project.bzl
docstring updated to:
```
resolve_json_module: None | boolean; Specifies whether TypeScript will read .json files. Defaults to None.
If set to True or False and tsconfig is a dict, resolveJsonModule is set in the generated config file.
If set to None and tsconfig is a dict, resolveJsonModule is unset in the generated config and typescript
default or extended tsconfig value will be load bearing.
```
> fix(typescript): don't set resolveJsonModule in generated tsconfig if tsconfig is a dict and resolve_json_module is unset (now defaults to None)

- internal/pkg_web/pkg_web.bzl
This makes the action not cached, so it causes re-runs on CI
We want pkg_web to be hermetic so it should use the sandbox.
> fix(builtin): don't use local:1 spawn

- packages/concatjs/BUILD.bazel
`bazel test //docs:check_concatjs` fails on an M1 mac (Darwin arm64) host, as only the `amd64` platform is scrubbed from the docs.
Issue Number: https://github.com/bazelbuild/rules_nodejs/issues/3085
Both `amd64` and `arm64` will be scrubbed.
> fix: add arm64 as a platform to //packages/concatjs:docs_scrub_platform

- WORKSPACE
- docs/Concatjs.md
- docs/Karma.md
- e2e/concatjs_devserver/WORKSPACE
- e2e/concatjs_devserver_directory_artifacts/WORKSPACE
- examples/angular/WORKSPACE
- examples/app/WORKSPACE
- examples/web_testing/WORKSPACE
- examples/webapp/WORKSPACE
- packages/concatjs/index.docs.bzl
No valid headless browsers or drivers are defined for M1 Mac hosts (Darwin arm64) in `browsers-0.3.2.bzl`, and tests fail.
Issue Number: https://github.com/bazelbuild/rules_nodejs/issues/3085
`browsers-0.3.3.bzl` defines browsers and drivers for M1 Mac hosts, and tests progress.
This does bump the versions of headless browsers being used, so there is possibility for regressions.
> chore: bump versioned browsers for rules_webtesting to 0.3.3

- docs/TypeScript.md
- examples/nestjs/tsconfig.json
- examples/protobufjs/tsconfig.json
- examples/protocol_buffers/tsconfig.json
- packages/esbuild/test/ts_project/tsconfig.json
- packages/rollup/test/ts_project/tsconfig.json
- packages/typescript/internal/ts_project.bzl
- packages/typescript/test/ts_project/empty_intermediate/tsconfig-c.json
- packages/typescript/test/ts_project/js_library/tsconfig.json
- packages/typescript/test/ts_project/tsconfig-base.json
ts output files cannot be found when building test and example code on an M1 Mac (Darwin arm64) host. This is because the `tsconfig.json` files look in specific `bazel-out` directories, and `darwin_arm64-fastbuild` is not on that list.
Issue Number: https://github.com/bazelbuild/rules_nodejs/issues/3085
`darwin_arm64-fastbuild` will be included in typescript's search for output files.
> fix: update tsconfigs to include darwin_arm64-fastbuild in rootDirs

- internal/linker/index.js
- internal/linker/link_node_modules.ts
This regressed at some point between 3.3 and 4.4 releases.
The problem appears specific to binary targets (not build targets) that resolve from the MANIFEST.
Repro here: https://github.com/ssilve1989/bazel-playground on `bug/link_workspace_root` branch
```
❯ bazelisk run //packages/examples/node/helloworld
INFO: Invocation ID: a0fce2a3-518b-438c-a490-7614f1680c76
INFO: Analyzed target //packages/examples/node/helloworld:helloworld (1 packages loaded, 4 targets configured).
INFO: Found 1 target...
Target //packages/examples/node/helloworld:helloworld up-to-date:
dist/bin/packages/examples/node/helloworld/helloworld.sh
dist/bin/packages/examples/node/helloworld/helloworld_loader.js
dist/bin/packages/examples/node/helloworld/helloworld_require_patch.js
INFO: Elapsed time: 3.259s, Critical …
```
> fix: remove trailing forward slash when resolving workspace root link in runfiles MANIFEST

- internal/runfiles/index.js
- packages/runfiles/runfiles.ts
- packages/runfiles/test/runfile_resolution.spec.js
backslashes -> forward slashes
trailing slashes removed
> fix: normalize module path passed to runfiles helper for robustness

- .circleci/bazel.rc
- internal/linker/index.js
- internal/linker/link_node_modules.ts
- internal/node/launcher.sh
- internal/node/node_patches.js
- internal/node/test/env.spec.js
- packages/node-patches/src/fs.ts
- packages/node-patches/test/fs/escape.ts
In the bazel run context there is no sandbox so node_modules not at the root (with a package_path in their `yarn_install` or `npm_install` rules) that as symlinked to a folder such as `execroot/<workspace>/<package_path>/node_modules` will end up in the user's workspace since `execroot/<workspace>/<package_path>` is a symlink into the user's workspace. This can lead to non-determinstic behavior and a corruption of the bazel managed node_modules if a user then runs `yarn install` or `npm install` outside of bazel. Those tools will follow the symlink that bazel left behind and operate in the bazel managed `node_modules` in the external repository created by `yarn_install` or `npm_install`.
With this change, the "primary" `node_modules` (where the linker symlinks 1p deps into and where other …
> fix: don't symlink execroot node_modules with a package_path when under bazel run

- packages/esbuild/esbuild.bzl
Pure annotations are currently always ignored if `esbuild(minify = False)`. There are
cases where a consumer will set fine-grained minification options through `args`, but
currently cannot do this without setting `minify = True` as otherwise pure annotations
would always be preserved.
This magical behavior should be removed and the consumer should be
responsible for enabling this if tree-shaking is undesirable.
> fix(esbuild): do not ignore annotations when the `minify` shorthand attribute is `false`

- packages/esbuild/esbuild.bzl
- packages/esbuild/test/multiple_entries_commonjs/BUILD.bazel
- packages/esbuild/test/multiple_entries_commonjs/a.ts
- packages/esbuild/test/multiple_entries_commonjs/b.ts
- packages/esbuild/test/multiple_entries_commonjs/bundle.spec.js
- packages/esbuild/test/multiple_entries_commonjs/index.ts
Fixes that the `format` attribute does not work if multiple entry points
or the `output_dir` option is used.
> fix(esbuild): format attribute not working with multiple entry points or output_dir

- internal/js_library/js_library.bzl
Allows for the exposal of `mjs` and `cjs` files in `js_library` targets.
Thsse are valid alternatives to the ambiguous `.js` extension that is
reliant on the closest `package.json` and its `type` field.
> fix(builtin): support mjs/cjs files as javascript files in `js_library`

- docs/Built-ins.md
- examples/parcel/WORKSPACE
- nodejs/repositories.bzl
As of 2021-10-26, v16 has entered LTS, so it's the most appropriate default.
Also, it provides darwin_arm releases (apple silicon) which many developers now expect.
The default nodejs version is now 16.12.0. To go back to the previous default, put this in your WORKSPACE:
```starlark
load("@build_bazel_rules_nodejs//:index.bzl", "node_repositories")
node_repositories(
node_version = "14.17.5",
)
```
Fixes #3101
> chore: update default nodejs version to 16

- WORKSPACE
- docs/Cypress.md
- docs/Toolchains.md
- examples/cypress/WORKSPACE
- toolchains/cypress/BUILD.bazel
- toolchains/cypress/cypress_repositories.bzl
Bazel fails to run Cypress tests with an M1 Mac (Darwin arm64) host, as it is unable to find a toolchain that doesn't limit the host to an x86 CPU.
Issue Number: https://github.com/bazelbuild/rules_nodejs/issues/3085
The CPU architecture compatibility restriction is removed in this PR, so Cypress will run using the x86 build under rosetta (note: Cypress' [official take](https://www.cypress.io/blog/2021/01/20/running-cypress-on-the-apple-m1-silicon-arm-architecture-using-rosetta-2/) is: "the way to run Cypress on Apple M1 ARM chip is by using Intel emulation with Rosetta 2, Apple's translation layer."). As of opening this PR, Cypress still does not have a native arm64 build. …
> fix: allow cypress to run on m1 macs

- .github/workflows/stale.yml
It feels to me that issues are getting stale/closed too quickly,
so adjust the timeouts based on the actual pace of the project
> chore: double stale timeouts

- e2e/core/WORKSPACE
- nodejs/repositories.bzl
- scripts/on-release.js
We should fetch the latter repo when users call our dependencies helper
> chore: build_bazel_rules_nodejs depends on rules_nodejs

- .bazelci/presubmit.yml
The "rbe_ubuntu1604" is failing with Bazel@HEAD for a long time, mark it as soft fail to not block the downstream pipeline turning green.
See https://github.com/bazelbuild/rules_nodejs/issues/3121
> Allow soft fail for "rbe_ubuntu1604"

- docs/esbuild.md
- packages/esbuild/BUILD.bazel
- packages/esbuild/esbuild.bzl
- packages/esbuild/test/define/BUILD.bazel
- packages/esbuild/test/define/bundle_test.js
- packages/esbuild/test/define/main.ts
- toolchains/esbuild/esbuild_repositories.bzl
Adds a `define_settings` attribute to the `esbuild` rules that allows using the values of Starlark build settings to globally replace
specified identifiers.
The value of the setting is automatically converted to a JS literal.
**Note:** This currently uses json.encode, which is only available from Bazel 5 on. If this addition is generally viewed favorably, I would look into "polyfilling" this functionality in Starlark.
Issue Number: #3113
The existing `esbuild` rule now has the `define_settings` attribute described in the issue.
> feat(esbuild): make Starlark build settings usable as defines

- .bazelci/presubmit.yml
- .circleci/config.yml
Removes another usage of hardcoded @nodejs repo
> ci: configs use new toolchain

- e2e/BUILD.bazel
- e2e/coverage/WORKSPACE
- e2e/nodejs_image/WORKSPACE
- e2e/typescript/WORKSPACE
- examples/BUILD.bazel
- examples/angular/WORKSPACE
- examples/angular_bazel_architect/WORKSPACE
- examples/app/WORKSPACE
- examples/create-react-app/WORKSPACE
- examples/kotlin/WORKSPACE
- examples/nestjs/WORKSPACE
- examples/protobufjs/WORKSPACE
- examples/vue/WORKSPACE
- examples/web_testing/WORKSPACE
- examples/webapp/WORKSPACE
- internal/bazel_integration_test/bazel_integration_test.bzl
- internal/bazel_integration_test/test_runner.js
User install instructions will change to require this, so our nested example/e2e workspaces need to as well.
> chore: always install rules_nodejs_dependencies

- package.json
- packages/jasmine/package.json
- yarn.lock
`@bazel/jasmine` uses `jasmine-reporters:~2.4.0` which has a vulnerability 
This PR updates `jasmine-reporters:~2.5.0` which fixes the vulnerability path related to xmldom
> fix: bump jasmine-reporters to 2.5.0

- docs/TypeScript.md
- packages/typescript/internal/ts_project.bzl
- packages/typescript/test/ts_project/swc/BUILD.bazel
- packages/typescript/test/ts_project/swc/tests.bzl
This is needed so the .js files produced by the alternate transpiler
are passed down the dependency graph.
> fix(typescript): ts_project transpiler produces js_library

- packages/typescript/package.json
Now that ts_library has moved to @bazel/concatjs, the @bazel/typescript package is free of code that uses TS internals.
Instead, it contains just ts_project which uses the tsc CLI and so there's little reason to be concerned that newer TypeScript causes a problem.
So just relax our peerDep constraint to have no upper bound on the TS version.
> chore(typescript): allow newer TS versions

- docs/Built-ins.md
- internal/npm_install/npm_install.bzl
> fix(builtin): detect yarn 2+ berry and adjust CLI args

- third_party/github.com/bazelbuild/bazel-skylib/rules/private/copy_file_private.bzl
With copy_file#is_directory being a very common code path with exports_directories_only,
more detail in the progress messages makes for a much better DX
> feat: add src patch being copied to progress message of vendored copy_file

- docs/Built-ins.md
- examples/vendored_node_and_yarn/package.json
- internal/npm_install/npm_install.bzl
> chore: code review feedback for #3195

- docs/Built-ins.md
- docs/Cypress.md
- e2e/node_loader_no_preserve_symlinks/.bazelrc
- internal/node/node.bzl
- nodejs/BUILD.bazel
> fix: turn off preserve_symlinks in e2e/node_loader_no_preserve_symlinks test

- examples/angular/src/tsconfig.json
- examples/angular/tools/karma.bzl
- examples/parcel/parcel.bzl
- examples/worker/uses_workers.bzl
- internal/bazel_integration_test/bazel_integration_test.bzl
- internal/linker/test/integration/rule.bzl
- internal/linker/test/no_npm_deps/no_npm_deps.bzl
- internal/node/node.bzl
- internal/node/npm_package_bin.bzl
- internal/npm_install/npm_umd_bundle.bzl
- internal/pkg_web/pkg_web.bzl
- internal/providers/test/run_node_test.bzl
- packages/concatjs/devserver/concatjs_devserver.bzl
- packages/concatjs/internal/build_defs.bzl
- packages/concatjs/test/some_module/run_node_test.bzl
- packages/concatjs/web_test/karma_web_test.bzl
- packages/protractor/protractor_web_test.bzl
- packages/rollup/rollup_bundle.bzl
- packages/terser/index.js
- packages/terser/terser_minified.bzl
- packages/typescript/internal/ts_project.bzl
- packages/typescript/internal/validate_options.bzl
These should have been "exec" all along.
> fix: change all cfg=host and cfg=target executable attributes to cfg=exec

- docs/Providers.md
- examples/from_source/tsconfig.json
- examples/webapp/BUILD.bazel
- examples/webapp/WORKSPACE
- internal/js_library/js_library.bzl
- internal/linker/link_node_modules.bzl
- internal/linker/test/default_path/custom_external_npm_package_info.bzl
- internal/node/test/BUILD.bazel
- internal/npm_install/generate_build_file.ts
- internal/npm_install/index.js
- internal/npm_install/npm_umd_bundle.bzl
- internal/npm_install/test/BUILD.bazel
- internal/npm_install/test/common.spec.js
- internal/npm_install/test/golden_directory_artifacts/@angular/core/BUILD.bazel.golden
- internal/npm_install/test/golden_directory_artifacts/@gregmagolan/BUILD.bazel.golden
- internal/npm_install/test/golden_directory_artifacts/@gregmagolan/test-a/BUILD.bazel.golden
- internal/npm_install/test/golden_directory_artifacts/@gregmagolan/test-a/bin/BUILD.bazel.golden
- internal/npm_install/test/golden_directory_artifacts/@gregmagolan/test-a/index.bzl.golden
- internal/npm_install/test/golden_directory_artifacts/@gregmagolan/test-b/BUILD.bazel.golden
- internal/npm_install/test/golden_directory_artifacts/BUILD.bazel.golden
- internal/npm_install/test/golden_directory_artifacts/ajv/BUILD.bazel.golden
- internal/npm_install/test/golden_directory_artifacts/jasmine/BUILD.bazel.golden
- internal/npm_install/test/golden_directory_artifacts/jasmine/bin/BUILD.bazel.golden
- internal/npm_install/test/golden_directory_artifacts/jasmine/index.bzl.golden
- internal/npm_install/test/golden_directory_artifacts/rxjs/BUILD.bazel.golden
- internal/npm_install/test/golden_directory_artifacts/unidiff/BUILD.bazel.golden
- internal/npm_install/test/golden_directory_artifacts/zone.js/BUILD.bazel.golden
- internal/providers/external_npm_package_info.bzl
Fixes the issue with exports_directories_only on RBE.
Removes `has_directories` from `ExternalNpmPackageInfo` since it is expected that source directories
are no longer used. This simplified `npm_umd_bundle.bzl` impl which was using this to filtering; it can now
just check `File.is_directory` since source directories are no longer passed in.
> fix: use tree artifacts via copy_directory with exports_directories_only

- packages/typescript/internal/ts_project.bzl
- packages/typescript/test/ts_project/swc/BUILD.bazel
- packages/typescript/test/ts_project/swc/tests.bzl
At the moment non-js generating srcs are also passed to transpiler attribute causing transpiler to access out of range indices.
non-js generating sources (`d.ts`) are not passed to transpiler's srcs attribute.
> fix(typescript): filter out .d.ts before passing srcs to transpiler

- examples/angular/WORKSPACE
- examples/angular/angular.json
- examples/angular/io_bazel_rules_sass.patch
- examples/angular/package.json
- examples/angular/yarn.lock
The rules_sass patch needs to bring version 5 of the @bazel/worker package.
Also account for the move of the @bazel/angular package.
> fix: angular example needs bump for 5.0

- internal/npm_install/npm_install.bzl
The default for frozen_lockfile is true so the warning should be if you try to set it false.
This API is really confusing right now though. Maybe we should have separate rules like yarn_install and yarn1_install or sth
> fix: warning logic for yarn berry attrs

- BUILD.bazel
It's confusing to have the bbrnj providers file in this module, since you're meant to use /nodejs/providers.bzl instead
> refactor: remove unneeded file from core package

- renovate.json
We get way too many PRs for rules_sass and rules_docker version bumps that we don't really want
> chore: renovate stop sending PRs for examples

- WORKSPACE
- docs/Toolchains.md
- docs/esbuild.md
- e2e/nodejs_image/BUILD.bazel
- e2e/nodejs_image/WORKSPACE
- e2e/symlinked_node_modules_npm/WORKSPACE
- e2e/symlinked_node_modules_yarn/WORKSPACE
- examples/vendored_node_and_yarn/WORKSPACE
- examples/vendored_node_and_yarn/toolchains/BUILD.bazel
- examples/vue/WORKSPACE
- index.bzl
- internal/node/node_repositories.bzl
- internal/npm_install/npm_install.bzl
- toolchains/esbuild/esbuild_repositories.bzl
Previously we'd create these repositories even if the user already installed node some other way.
Note, this is minor extra breaking change after rc1, but based on testing at one client I think this may be a good idea. This PR demonstrates how it caught some bugs in our e2e/examples where the wrong node (default version) was getting used.
> *_install: only create nodejs or yarn repositories if we need them

- examples/BUILD.bazel
- examples/vendored_node_and_yarn/WORKSPACE
- internal/npm_install/npm_install.bzl
Otherwise we fall through to the system node on the PATH which may not be set, or may be skewed
rebased on #3250
> fix(yarn): when running vendored yarn, prefix command with path to node

- internal/node/npm_package_bin.bzl
- internal/node/test/BUILD.bazel
- internal/node/test/npm_package_bin_test.bzl
Otherwise you can't use a data dep on one of these to gather runtime deps
fixes #3257
> fix(builtin): npm_package_bin include runfiles in DefaultInfo

- packages/typescript/internal/ts_project.bzl
Issue Number: #3259 
Tags are propagated to the validate_options rule
Strictly, the answer here might be yes, particularly if someone was doing something very esoteric with custom tags and relying on the fact that propagation to this rule was not happening, but this seems extremely unlikely.
> fix(typescript): propagate tags to validate_options

- WORKSPACE
- docs/Toolchains.md
- docs/esbuild.md
- examples/angular/WORKSPACE
- examples/esbuild/WORKSPACE
- packages/esbuild/index.docs.bzl
- toolchains/esbuild/esbuild_repositories.bzl
**BREAKING CHANGE**
Removes the default value of `npm` for the `esbuild_repositories` rules `npm_repository` attr. When changing the default npm name, often users trip up on this default, so make it explicit.
> chore(esbuild): remove default value of npm from the npm_repository attr

- packages/create/index.js
This is needed for 5.0.0 breaking change.
> fix(create): add missing workspace dependency call

- docs/BUILD.bazel
- providers.bzl
This makes the 5.0 release less breaking by restoring back-compat with
rulesets that loaded these from the old location.
I manually verified that the same symbol comes through, so even though
a provider creation and usage site load from different places, the
provided symbol still matches and works.
> refactor: bbrnj re-exports rules_nodejs providers

- nodejs/directory_file_path.bzl
These don't work with RBE, and only work accidentally with actions.
> fix(builtin): prevent usage with InputArtifact directories

- e2e/nodejs_host/BUILD.bazel
- e2e/nodejs_host/WORKSPACE
- e2e/nodejs_host/package.json
- internal/node/node_repositories.bzl
We were missing test coverage for attributes like node_version being passed to the new toolchain registration
> fix(builtin): pass kwargs from node_repositories helper

- e2e/BUILD.bazel
- packages/jasmine/jasmine_runner.js
With this change we replace APIs that have been deprecated in version 4 and removed in version 4
```
Jasmine#onComplete is deprecated. Instead of calling onComplete, set the Jasmine instance's exitOnCompletion property to false and use the promise returned from the execute method.
```
Also this addresses the breaking change in version 4 https://github.com/jasmine/jasmine/blob/main/release_notes/4.0.0.md#changes-that-affect-custom-reporters in a backward compatible manner.
> fix(jasmine): replace deprecated Jasmine APIs that have been removed  in version 4

- internal/linker/link_node_modules.bzl
- internal/node/node.bzl
- internal/providers/node_runtime_deps_info.bzl
- packages/esbuild/esbuild.bzl
Issue Number: #3302 
With this commit, the `LinkerPackageMappingInfo` provider is restructured to hold depsets of mapping entries and node_modules root paths. In this way the aspect invocations for the individual targets never traverse the
(partially constructed) mappings.
Instead, `write_node_modules_manifest` flattens the depset only after the aspect has run. If this should ever become a performance bottleneck again, the flattening could be moved into the execution phase by letting a dedicated binary consume the depset wrapped in an Args object.
In an experiment with a single medium-sized package.json and a Node binary depending on all targets in the corresponding npm repository, this commit reduces the analysis wall time spent in the aspect implementation from ~30s to ~70ms. …
> fix(builtin): make linker aspect run in constant time per target

- internal/linker/link_node_modules.bzl
The Node linker performs one string formatting per transitive dependency even if `VERBOSE_LOGS` is not set.
Construct the formatted strings lazily to prevent allocating and formatting a string for every transitive dependency.
@gregmagolan Very small follow-up to #3301
> fix(builtin): reduce linker debug string allocations

- internal/node/node.bzl
- internal/node/test/chdir/BUILD.bazel
- internal/node/test/chdir/multithread.js
- internal/node/test/chdir/worker.js
When the `chdir` attribute is used in `nodejs_test`, the script that changes the directory will run in each worker thread. Node fails when `process.chdir` is called in a worker thread. This is because node is invoked using `--require` on the chdir script: https://github.com/bazelbuild/rules_nodejs/blob/stable/internal/node/node.bzl#L286
Only change directories once in the main node process. Spawned workers won't try to change the directory again.
This is needed for an architect_test rule in angular/aio to work. That project is currently on rules_nodejs 4.6.0, so I suppose we'll want to backport this and cherry-pick it into stable?
> fix(builtin): avoid unnecessary chdir to prevent worker threads from failing

- nodejs/private/os_name.bzl
- nodejs/private/user_build_settings.bzl
- nodejs/repositories.bzl
When setting `node_repositories` attribute on the `node_repositories` rule (well that's kinda confusing), ensure this is taken into account when checking if the requested node version exists for the platform.
This can be useful when trying to trick rnj into downloading a different version of Node for a given OS (eg, a newer version of Node on darwin arm64), or when setting this attr to a version of Node that isn't included in the default list of `NODE_VERSIONS` yet.
> fix(builtin): take custom node_repositories value into account when checking if Node version exists for the platform

- docs/Built-ins.md
- internal/node/npm_package_bin.bzl
- internal/node/test/BUILD.bazel
- internal/node/test/expand_variables.js
- internal/node/test/expand_variables.spec.js
Additional environment variables supplied to `npm_package_bin` do not undergo make variable substitution.
Values of env vars now perform make variable substitution.
> feat(builtin): perform make variable substitution in npm_package_bin env vars

- docs/TypeScript.md
- packages/typescript/index.bzl
This doesn't change behavior; previously it was included in the **kwargs passed to the underlying ts_project rule.
However it makes the documentation less confusing
> docs: add data attribute to ts_project macro

- internal/pkg_npm/pkg_npm.bzl
- internal/pkg_npm/test/tgz_out/BUILD.bazel
- internal/pkg_npm/test/tgz_out/test.sh
As the `.pack` script was part of the `tools` attr, it was built for the host (I think?) therefore stamping etc was lost. Move it to `srcs`.
Closes #3143
> fix(builtin): use srcs on genrule to not build tool for host

- docs/Built-ins.md
- internal/common/is_js_file.bzl
- internal/js_library/js_library.bzl
- internal/npm_install/npm_install.bzl
`yarn_install` allows for a vendored/custom Yarn JavaScript file. To ensure
that Yarn runs with the proper Node version, `yarn_install` calls the JS file
with the host NodeJS version also installed through Bazel. Currently the detection
logic does not account for `.cjs` or `.mjs`. This is a little confusing as the
install continues to work but breaks surprisingly in Windows then, or when a engines
requirement is no longer satisifed (there are more reasons as well)
We should support `cjs` and `mjs` to avoid confusion, and especially `cjs`
since Yarn itself always vendors itself with that extension!
Fixes #3349
> fix(builtin): `yarn_install` with vendored yarn `.cjs` file breaks

- packages/typescript/index.bzl
#3351 introduced a breakage on CI as it only updated the generated docs, not the source.
> fix: update source for generated docs

- docs/Built-ins.md
- docs/Rollup.md
- docs/TypeScript.md
- internal/node/launcher.sh
- internal/node/npm_package_bin.bzl
- internal/node/test/BUILD.bazel
- internal/providers/node_runtime_deps_info.bzl
- packages/rollup/rollup_bundle.bzl
- packages/rollup/test/silent/BUILD.bazel
- packages/rollup/test/silent/input.js
nodejs programs which output on stdout and stderr have no way to be silenced on success
A new flag where we can silence binaries that are loud when they are successful.
I couldn't figure out how to write a test here since `sh_test` can't invoke `bazel build` commands easily to check the stdout, and my flag doesn't change the behavior of the `stdout` nor `stderr` files incase a user wants to still use them.
Without this flag I get:
```
$ bazel build internal/node/test:loud_binary
...
INFO: From Action internal/node/test/loud_binary:
WARN: Dropping unreachable code [internal/node/test/terser_input_with_diagnostics.js:6,4]
class Greeter{greet(name){return name}}
Target …
```
> feat(builtin): add silent_on_success option to npm_package_bin

- docs/TypeScript.md
- internal/node/test/env.spec.js
It looks like the environment spec started failing on Windows. It was
thought that this started happening with 4a025c0d197a181cfcd9556831f69467817d3a40,
but it turnes out that this failed many commits before but a Buildkite status
just did not show up in the commit history (making it look like the PnP commit
caused the failures).
Root-cause seems to be https://github.com/bazelbuild/rules_nodejs/commit/7993296829c5ddaadb04a7d76ecc6b72eacdd01c which changed the `RUNFILES` variable.
> test: update environment spec to work with windows

- e2e/BUILD.bazel
- packages/jasmine/jasmine_runner.js
See: https://github.com/angular/dev-infra/pull/463
> fix: sharded test never fail when using Jasmine < 4

- examples/create-react-app/BUILD.bazel
Create react app //:start target appears to be missing the following 2 type definitions:
- @npm//@types/react
- @npm//@types/react-dom
running the following on the current stable branch yields the following behaviour:
```
$ cd examples/create-react-app
$ bazel run //:start
> 1 | import React from 'react';
|                   ^
2 | import logo from './logo.svg';
3 | import './App.css';
4 |
```
```
$ cd examples/create-react-app
$ bazel run //:start
Compiled successfully!
You can now view create-react-app in the browser.
Local:            http://localhost:3000
```
> Add type definitions to react example

- internal/node/npm_package_bin.bzl
This will allow easier tracking of this particular action being run.
In particular, we found that some npm package binaries take a lot of memory (like 8G), adding mnemonic would allow to find those actions more easily e.g. in execution logs, and perform different actions that bazel allows to do per mnemonic, in particular, enabling or disabling remote execution.
```
$ ~/.cache/vanilla_bazel/bazel-5.0.0-linux-x86_64 test internal/node/test/... --execution_log_json_file=/tmp/exec_log.json
$ grep mnemonic /tmp/exec_log.json | sort | uniq -c
23   "mnemonic": "Action",
2   "mnemonic": "AssembleNpmPackage",
2   "mnemonic": "CopyDirectory",
11   "mnemonic": "CopyFile",
1   "mnemonic": …
```
> Add mnemonic to action run by npm_package_bin

- packages/concatjs/internal/BUILD.bazel
The linker is prone to race conditions in persistent workers, or non-sandbox environments (like
windows). This is because the linker for all workers will operate on a shared `execroot` directory
and the same `node_modules` directory is modified all the time / potentially conflicting with other
linker processes from other concurrently-running workers.
We rely on the patched module resolution anyway, but just need to disable the unused linker to avoid
issues like the following:
```
---8<---8<--- Start of log, file at /private/var/tmp/_bazel_splaktar/280f06d55552a0d01f89f0955b5acd78/bazel-workers/worker-8-TypeScriptCompile.log ---8<---8<---
[link_node_modules.js] An error has been reported: [Error: ENOENT: no such file or directory, unlink 'node_modules'] {
errno: -2,
code: 'ENOENT', …
```
> fix(concatjs): tsc-wrapped compilation workers are subject to linker race-conditions

- docs/Built-ins.md
- internal/pkg_npm/pkg_npm.bzl
The `pkg_npm` builtin exposes a `create_package` helper that is leveraged
by the `ng_package` Angular Bazel rule. The `create_package` helper
currently always determines files from the `ctx`, and it's not possible
to add more files to the package, or to omit files that are already
processed by the `ng_package` wrapping rule implementation.
The static files should be configurable similar to deps and the nested
packages.
> refactor(builtin): allow static files to be specified in `pkg_npm` `create_package` helper

- nodejs/private/toolchains_repo.bzl
- nodejs/repositories.bzl
Issue Number: #3357
nodejs toolchain was conditioned on the exec which led to nodejs_images using toolchain for the host instead of image target. hence images built from macOS were broken due to the wrong toolchain being used in runfiles. 
Related issues;
https://github.com/bazelbuild/rules_docker/issues/2009
https://github.com/bazelbuild/rules_docker/pull/1963
> fix: condition on target instead of exec

- third_party/github.com/bazelbuild/bazel-skylib/tests/unittest.bash
python 2 is dead, https://www.idownloadblog.com/2022/01/28/python-macos-monterey-no-more/
> fix: use python3 instead of python in unittest.bash

- third_party/github.com/bazelbuild/bazel-skylib/rules/private/copy_file_private.bzl
Fixes #3381
For reference, the cp -r option is historic and discouraged on macos. It differs from cp -r on linux.
https://man7.org/linux/man-pages/man1/cp.1.html
https://ss64.com/osx/cp.html
> fix: use -R in copy_file(is_dir=True) so macos & linux behavior are the same

- packages/jasmine/jasmine_node_test.bzl
- packages/jasmine/test/BUILD.bazel
- packages/jasmine/test/foo.spec.cjs
- packages/jasmine/test/foo.spec.mjs
- packages/jasmine/test/foo.test.cjs
- packages/jasmine/test/foo.test.mjs
- packages/jasmine/test/foo_spec.cjs
- packages/jasmine/test/foo_spec.mjs
- packages/jasmine/test/foo_test.cjs
- packages/jasmine/test/foo_test.mjs
When using jasmine_node_test, currently spec/test files ending with the .cjs extension are not recognized.
Issue Number:
#3400
Spec/test files ending in the .cjs extension will be recognized
This PR also adds tests for whether .mjs are recognized in jasmine_node_test
> fix(jasmine): allow cjs specs + add cjs/mjs tests in jasmine_node_test

- docs/Toolchains.md
- toolchains/index.for_docs.bzl
Expand notes on custom toolchains in the toolchains documentation page
@knz wanted some extra clarity on how to configure toolchains in this PR's comments
Issue Number: bazelbuild/rules_nodejs#2991
More notes to expand on why things are the way they are
> Add more info on custom toolchains

- packages/typescript/bin/BUILD.bazel
Currently, there is no way to include `rules_nodejs` as a regular GitHub dependency; it has to be downloaded with `npm` and imported with something like:
```starlark
load("@npm//@bazel/typescript:index.bzl", "ts_project")
```
This means that any `BUILD.bazel` files that use any of these rules have to download and install all of `@npm`, even if the typescript target isn't being built.
This makes queries and builds of non-typescript code significantly slower, since a project may have a large number of `@npm` dependencies.
With this fix, you have the option of importing the rules without `npm`, e.g.
```starlark
load("@build_bazel_rules_nodejs//packages/typescript:index.bzl", "ts_project") …
```
> Allow including rules_nodejs without npm

- internal/node/node.bzl
- internal/node/test/esm/BUILD.bazel
Issue Number: Generally related to https://github.com/bazelbuild/rules_nodejs/issues/3277
Calling `bazel run` on a `nodejs_binary` target that doesn't add its entry_point to `data` will cause node to run with no script.
The script is run properly.
> fix(builtin): fix a bug where mjs entry points were not added to runfiles

- third_party/github.com/bazelbuild/bazel-skylib/rules/private/copy_file_private.bzl
These are always the same as the files in the external repository so it's wasteful to upload them to a cache
> Don't remote-cache npm directory copies

- docs/TypeScript.md
- packages/typescript/index.docs.bzl
- Make the URLs in the TypeScript doc into actual links
- Markdown cannot contain `<example>` because it'll be rendered as HTML tag
- `<example>` is not rendered correctly because the tags are not escaped
- URLs do not show up as hyperlinks
Fixed the issues above
> docs: add hyperlinks and escape `<>`

- internal/node/test/chdir/BUILD.bazel
Somehow we are missing Buildkite triggering on our 4.x branch so the failure went unnoticed.
https://buildkite.com/bazel/rules-nodejs-nodejs/builds/11963#8226877c-c047-4126-bf3a-823151b260ea
> ci: green up 4.x branch by suppressing a test on Windows

- docs/examples.md
Some URLs in https://bazelbuild.github.io/rules_nodejs/examples.html are just texts, not links.
Turn these URLs into links so that users can follow the links.
> Turn some URLs into links

- nodejs/private/BUILD.bazel
- nodejs/private/ts_lib.bzl
- nodejs/private/ts_project.bzl
Noticed when trying to build docs in downstream repo.
Why not fix this by adding stardoc locally so the bzl_library has some test coverage within this repo?
So far these TS APIs are all private here so I don't think we want to document them directly.
> fix: enable stardoc generation for rules that depend on ts in core

- packages/concatjs/internal/tsc_wrapped/compiler_host.ts
In TypeScript 4.7 the first argument of `resolveTypeReferenceDirectives` can be a `FileReference[]`, in addition to a `string[]`. These changes resolve a runtime error that was happening as result.
> fix(concatjs): resolve error with TypeScript 4.7

- docs/Core.md
- nodejs/extensions.bzl
- nodejs/private/node_versions.bzl
- nodejs/repositories.bzl
- scripts/update-nodejs-versions.js
We shouldn't make it the default until rnj 6.0, however we can update our default to latest 16.
Also add the default for bzlmod users
> chore: include node.js 18 which is now LTS

- nodejs/private/ts_config.bzl
- nodejs/private/ts_project.bzl
- nodejs/private/ts_validate_options.bzl
`ts_config` rules allocate way too much memory just for storing duplicate artifacts in a list:
`bazel [..] dump --rules` before this change:
```
RULE                                 COUNT     ACTIONS          BYTES         EACH
filegroup                           12,078           0     17,726,232        1,467
java_library                         4,332      13,025     35,065,464        8,09
ts_project                             136         268     14,161,720      104,130
ts_config                              131           0  1,839,281,704   14,040,318
```
Issue Number: #3430
with this patch `TsConfigInfo` uses depsets and therefore avoids any memory allocation (instead using objects …
> Fix TsConfigInfo to use depset and deduplicate files (#3430)

- packages/concatjs/internal/tsc_wrapped/tsconfig.ts
adds devmode to bazelOpts type definition imported by angular ngc-wrapped for <internal> options migration.
In the future, a better plan should be made to move away from lightly supported legacy corners of this repo.
related to https://github.com/angular/angular/pull/45804
> fix(concatjs): adding devmode to BazelOpts

- .github/workflows/stale.yml
- .github/workflows/update-esbuild-versions.yml
- .github/workflows/update-nodejs-versions.yml
- .github/workflows/update-yarn-versions.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- internal/npm_install/npm_install.bzl
Fixes https://github.com/bazelbuild/rules_nodejs/issues/3323
Verified on repro repository, https://github.com/mhevery/repro-bazel-nested-project
```
gregs-mbp:repro-bazel-nested-project greg$ bazel build @child//packages/core
INFO: Analyzed target @child//packages/core:core (12 packages loaded, 99 targets configured).
INFO: Found 1 target...
Target @child//packages/core:core up-to-date:
bazel-bin/external/child/packages/core/main.js
INFO: Elapsed time: 0.447s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```
```
gregs-mbp:repro-bazel-nested-project greg$ cd child
gregs-mbp:child greg$ bazel build //packages/core
INFO: Analyzed target //packages/core:core (10 packages loaded, 94 targets configured).
INFO: Found 1 target...
Target …
```
> fix: set correct linking location for yarn_install using package.json from external repository

- packages/typescript/internal/worker/index.js
- packages/typescript/internal/worker/worker_adapter.ts
> fix(typescript): correctly process diagnostics in worker mode

- .circleci/config.yml
- examples/angular_bazel_architect/package.json
- examples/angular_bazel_architect/yarn.lock
The angular architect example is broken on m1. The version of webdriver-manager that was being used had a bug that prevented it from finding the correct url to download chrome drivers on an m1 architecture.
Resolved the correct version of webdriver-manager and updated e2e tests to run using an m1-supported version of chrome.
> fix(examples): fix architect example on m1

- docs/Built-ins.md
- internal/npm_install/npm_install.bzl
"symlink_node_modules is True" doesn't make any sense in this position. I think it was a stray copy and paste from the beginning of the paragraph.
> fix(docs): stray text in npm_install docs

- docs/Built-ins.md
- docs/Cypress.md
- internal/node/node.bzl
- internal/node/test/BUILD.bazel
- internal/node/test/env.spec.js
`nodejs_binary`/`nodejs_test` does not perform make variable substitution.
`nodejs_binary`/`nodejs_test` now performs make variable substitution.
The motivating use case is to pass a browser toolchain to an `architect_test` rule. The path to the browser and driver binaries are provided via a make variable which protractor references.
> feat(builtin): expand make vars in nodejs_binary/test env attr

- nodejs/private/os_name.bzl
It is possible to use `rules_nodejs` on operating systems besides
Windows, Linux, and macOS, but they need to be handled in `os_name()`
or else you get a `Unsupported operating system freebsd` error message.
This change allows you to add a FreeBSD toolchain to your project by
declaring a `nodejs_freebsd_amd64` repo with a `bin/node` executable.
cockroachdb/cockroach#82762 is an example of this.
Builds on FreeBSD will fail with an "Unsupported operating system" message.
Alone, this change does not make it possible to build on FreeBSD, but it does allow you to add your own toolchain that supports FreeBSD without any additional patches to `rules_nodejs`.
> Teach os_name() about freebsd-amd64

- internal/common/is_js_file.bzl
closes #3487
Maybe its better to have the option to give which file extensions it accepts? Because jsx is since 2015 problematic in its acceptance and not really more then a React syntax. But the same you already did with allowing CJS => https://github.com/bazelbuild/rules_nodejs/pull/3350
> also have jsx files as part of being a JS file

- packages/typescript/index.bzl
- packages/typescript/package.json
protobufjs is not needed anymore by `@bazel/typescript`
prototbufjs <6.11.3 is also vulnerable according to https://github.com/advisories/GHSA-g954-5hwp-pp24
`@bazel/typescript` depends on `prototbufjs`.
The package does not depend on `protobufjs` anymore.
> fix(typescript): remove protobufjs dependency

- packages/create/index.js
- packages/create/test.js
When running `yarn create @bazel my_test_workspace --typescript --packageManager=npm` the script will create a new workspace with `yarn` as a package manager instead of `npm`.
The flag `--packageManager` now is respected and takes effect. This also improves the script by checking, if 'yarn' or 'npm' is given with that flag.
> fix(create): make `--packageManager` flag work

- .gitattributes
- docs/Built-ins.md
- internal/npm_install/generate_build_file.ts
- internal/npm_install/index.js
- internal/npm_install/npm_install.bzl
- npm_deps.bzl
Fixes https://github.com/bazelbuild/rules_nodejs/issues/3507
I set the default to an arbitrary reasonable value of 64
> fix: limit concurrency when generating BUILD files in npm_install and yarn_install

- packages/concatjs/internal/tsc_wrapped/compiler_host.ts
Tsickle now requires a `generateExtraSuppressions` public property on the TS host. This change has been implemented internally but hasn't been synced upstream, making it difficult to update to the latest `tsickle` externally.
> fix(concatjs): sync with internal change to ensure it works with `tsickle` host

- packages/concatjs/internal/tsc_wrapped/compiler_host.ts
Tsickle now requires a `rootDirsRelative` public property on the TS host. This change
has been implemented internally but hasn't been synced upstream, making it difficult
to update to the latest `tsickle` externally.
This is hopefully the last change in a while we need to sync up externally. It is still planned to
rework the whole rule to be owned by Angular directly, and not relying on the external
sync (might mean we need to diverge `ngc-wrapped` internally and externally)
> refactor(concatjs): sync with internal change that exposes `rootDirsRelative`

- nodejs/private/ts_lib.bzl
- packages/typescript/test/ts_project/rootdir_with_value/BUILD.bazel
- packages/typescript/test/ts_project/rootdir_with_value/subdir/deep/subdir/b.ts
- packages/typescript/test/ts_project/rootdir_with_value/verify.js
- Unsure if necessary 
If `ts_project` is used with the `root_dir` parameter, and has a set of source files where the name of the `root_dir` is repeated within the source tree, then it incorrectly calculates output files (and subsequently breaks, as the filename it calculated was not produced).
For example: using a `root_dir` of `src` with the following tree:
```
- src
- foo
- src
- foo.ts
```
would cause a bazel error of the form:
```
ERROR: BUILD.bazel:1:1: output 'foo/foo.js' was not created
```
The build should create (and expect the output) to be at `foo/src/foo.js` instead.
The fix is small but also somewhat magic-number, so I'm happy to re-evaluate the most …
> fix: `ts_project` fails if `root_dir` used deep in source tree

- docs/Built-ins.md
- internal/npm_install/generate_build_file.ts
- internal/npm_install/index.js
- internal/npm_install/npm_install.bzl
The default target name obfuscates the "node_modules" source directory for use in `manual_build_file_contents` for custom use cases.
> fix: make catch-all node_modules target name configurable in yarn_install and npm_install

- WORKSPACE
- examples/angular/WORKSPACE
- repositories.bzl
- [x ] CI related changes
Currently `rules_nodejs` uses the deprecated `rbe_autoconfig` that still has reference to `@bazeltools_platforms:xxx`. It was also linked with `bazel_toolchains` repo. The flag `--incompatible_use_platforms_repo_for_constraints` is flipped causing failures for `rules_nodejs` in downstream pipelines.
Issue Number: https://github.com/bazelbuild/continuous-integration/issues/1404
https://github.com/bazelbuild/rules_nodejs/issues/3537
This pr updates to use the new `rbe_preconfig` and remove `bazel_toolchains` from rules_nodejs as there are no other usage for `bazel_toolchains`.
- [x ] No
> migrating to rbe_preconfig

- nodejs/private/toolchains_repo.bzl
- packages/concatjs/devserver/BUILD.bazel
- toolchains/esbuild/esbuild_packages.bzl
This is defined as an alias to :arm64:
https://github.com/bazelbuild/platforms/blob/212a486d66569b29c95b00364e2584e80fd08614/cpu/BUILD#L16-L20 but toolchain resolution doesn't understand the two to be equivalent.
Fixes https://github.com/aspect-build/rules_js/issues/469
> fix: canonicalize @platforms//cpu:aarch64

- internal/node/node.bzl
- internal/node/test/BUILD.bazel
- internal/node/test/env.spec.js
Environment variables passed to the launcher script were not escaped.
Properly surrounded in quotes as is done elsewhere.
> fix(builtin): properly quote env vars passed to nodejs_binary

- examples/protobufjs/defs.bzl
- examples/protobufjs/package.json
- examples/protobufjs/yarn.lock
Unchanged.
I ran `scripts/update_nested_lock_files.sh` to create the updates in `examples/protobufjs/yarn.lock`.
> refactor: replace protobufjs with protobufjs-cli in examples/protobufjs

- packages/create/index.js
- packages/create/test.js
users now can set a different name for the directory to create a workspace in
the behaivior also changed, so it is possible to create a workspace e.g. in the current dir
Users cannot set a different directory name when creating a new workspace.
Users can set a different directory name or create a workspace in an existing directory.
> feat(create): introduce `--workspaceDir` flag

- internal/node/launcher.sh
`RUNFILES_MANIFEST_ONLY` is always set to `1` (see https://github.com/angular/angular/pull/47527/files#diff-30590eade0d767af96219fac23a137e7996bff554e9569f1db54ed40be435854R17-R23). This seems like a bug. When runfiles are enabled, during a `bazel test` the environment var `RUNFILES` is not set correctly because of it.
Separately from addressing the above, the slightly modified [launcher logic](https://github.com/aspect-build/rules_js/blob/06d51cddbd62e44303b1a0d62af97b3e22dec9d1/js/private/js_binary.sh.tpl#L172) in `rules_js` already works around the issue by getting the runfiles directory from `TEST_SRCDIR`.
Use rules_js updated launcher logic.
> fix(builtin): use updated rules_js launcher logic to source RUNFILES

- docs/Core.md
- nodejs/repositories.bzl
- nodejs/toolchain.bzl
Downstream rules that use the toolchain can choose to include the npm binary & files specified by the toolchain as inputs for actions.
> feat: add npm binary & files to toolchain provider

- scripts/update-esbuild-versions.js
- toolchains/esbuild/esbuild_packages.bzl
Tensorboard uses rules_nodejs during its build. And it fails on linux ppc64le or linux s390x with following error -
```
ERROR: /opt/conda/conda-bld/tensorboard_1665144934672/work/tensorboard/webapp/widgets/line_chart_v2/lib/worker/BUILD:89:13: While resolving toolchains for target //tensorboard/webapp/widgets/line_chart_v2/lib/worker:chart_worker: no matching toolchains found for types @build_bazel_rules_nodejs//toolchains/esbuild:toolchain_type
ERROR: Analysis of target '//tensorboard/pip_package:build_pip_package' failed; build aborted:
INFO: Elapsed time: 112.999s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (118 packages loaded, 1236 targets configured)
FAILED: …
```
> Added support for linux ppc64le and linux s390x

- packages/typescript/index.bzl
The typescript package `@npm//@bazel/typescript:index.bzl` exports the public typescript rules interface including a rule called `ts_config`. However, `ts_config` returns a provider `TsConfigInfo` that is not publicly exported and is instead found under `@rules_nodejs//nodejs/private:ts_config.bzl`.
`TsConfigInfo` is exported from `@npm//@bazel/typescript:index.bzl` alongside `ts_config`.
> chore: export TsConfigInfo in public interface

- internal/npm_install/npm_install.bzl
Ensure version check is run inside the project workspace, i.e. the directory with package.json
a project with multiple sub projects, but no root package.json/yarn.lock/.yarnrc.yml that uses yarn berry will fail to detect project using yarn berry. E.G.
```
WORKSPACE
proj1/
package.json
yarn.lock
BUILD
proj2/
.yarn/...
package.json
yarn.lock
.yarnrc.yml
BUILD
```
WORKSPACE having the following:
```
yarn_install(
name = "proj1_npm",
package_json = "@//proj1:package.json",
yarn_lock = "@//proj1:yarn.lock",
)
yarn_install(
name = "proj2_npm",
package_json = "@//proj2:package.json",
yarn_lock = "@//proj2:yarn.lock",
data = [
"@//proj2:.yarnrc.yml",
"@//proj2:.yarn/releases/yarn-3.2.4.cjs",
] …
```
> Update yarn version check

- docs/Core.md
- nodejs/repositories.bzl
Fixes #3573
Tested with:
```
% cd e2e/typescript; bazel run --override_repository=rules_nodejs=/Users/alexeagle/Projects/rules_nodejs @nodejs_host//:bin/node -- --version
INFO: Invocation ID: a7e4a810-2c7c-4e9c-aa6d-1351c3c59b7e
v16.18.1
```
> chore: default node should be latest v16

- docs/Built-ins.md
- internal/npm_install/npm_install.bzl
> fix: yarn binary is now run from separate @yarn repo

- internal/runfiles/index.cjs
- packages/runfiles/runfiles.ts
Resolves https://github.com/aspect-build/rules_js/issues/553 and https://github.com/aspect-build/rules_js/issues/612.
> fix: check RUNFILES env variable in @bazel/runfiles helper

- internal/node/node.bzl
Consider a `nodejs_binary` with a definition like the followed:
```bzl
js_library(
name = "lib",
srcs = ["entrypoint.js", "constants.js"],
)
nodejs_binary(
name = "bin",
entry_point = "entrypoint.js",
data = [":lib"],
)
```
This seems very standanrd and also works perfectly when the binary is invoked with `bazel run`. Via Bazel run, the Node Bash launcher resolves the entrypoint via the actual runfiles using `rlocation`.
If this binary is used as a tool, e.g. in `npm_package_bin`- then the entry point is resolved from the execroot, landing ultimately on the *actual source file*. This is wrong and breaks resolution in RBE (where only necessary sources are in the execroot).
This happens because the source entrypoint file. i.e. not the `entrypoint.js` from `bazel-bin` is also ending up being …
> fix(builtin): entry point from sources incorrectly used when binary is leveraged as tool, breaking resolution

- repositories.bzl
Earlier versions have `build_tar` using `python_version=PY2`, which newer
versions of Bazel will no longer support.
Fixes #3619
-   [x] Bugfix
Issue Number: 3619
rules_pkg version 3.0 is used, which doesn't use a Python 2 binary.
-   [ ] Yes
-   [x] No
> Upgrade rules_pkg to 0.3.0 to remove Python 2 dependency.

- .bazelci/presubmit.yml
- packages/concatjs/internal/tsc_wrapped/compiler_host.ts
In the concatjs `CompilerHost.resolveTypeReferenceDirectives` method the `undefined` values are excluded, despite the return value being `(ts.ResolvedTypeReferenceDirective|undefined)[]`. Until now TS was handling this gracefully, but it appears to trigger an error after 5.0.
These changes add some code that should be both backwards and forwards compatible.
> fix(concatjs): resolve error with TypeScript 5.0

- nodejs/repositories.bzl
> Expose node headers as a cc_library

- nodejs/repositories.bzl
We had an in-flight collision between two PRs. #3679 added a cc_library, but Node.js doesn't ship the required headers on Windows, so it wouldn't work there. #3621 disallows empty glob, which breaks because of the missing headers. Just add the allow_empty here to make it green.
> fix(windows): unbreak CI with allow_empty

- packages/jasmine/jasmine_runner.js
Currently, with jasmine core version 5 the old API is being used which causes errors.
> fix(jasmine): update jasmine core version check to support versions older then 4

- docs/Core.md
- e2e/smoke/BUILD.bazel
- e2e/smoke/using_headers.cc
- nodejs/BUILD.bazel
- nodejs/private/current_node_cc_headers.bzl
- nodejs/repositories.bzl
- nodejs/toolchain.bzl
Currently the headers are exposed but they need to be accessed from toolchain-specific repos like `@node_darwin_amd64//:headers`. This is a bit annoying, and I believe these repos are not visible in the main workspace in bzlmod. Copy the rules_python approach to make this more ergonomic.
You can depend on `@rules_nodejs//nodejs:current_node_cc_headers`.
(Unless someone was creating their own toolchains, in which case they will need to pass the extra label)
> Add current_node_cc_headers

- .bazelrc
This will help make sure [Bazel Downstream Pipeline](https://github.com/bazelbuild/continuous-integration/blob/master/docs/downstream-testing.md) is green after enabling Bzlmod at Bazel@HEAD
See https://github.com/bazelbuild/bazel/issues/18958#issuecomment-1749058780
Related https://github.com/bazelbuild/rules_nodejs/issues/3695
> Disable Bzlmod explicitly in .bazelrc

- nodejs/toolchain.bzl
This effectively establishes backward compatibility with users of previous
rules_nodejs that create custom toolchains and do not pass the `headers`
attribute to `node_toolchain` which would otherwise fail with:
```
ERROR: /.../external/rules_haskell_nix_node_toolchain/BUILD:4:15: in node_toolchain rule @rules_haskell_nix_node_toolchain//:node_nixpkgs:
Traceback (most recent call last):
File "/.../external/rules_nodejs/nodejs/toolchain.bzl", line 102, column 43, in _node_toolchain_impl
"CcInfo": ctx.attr.headers[CcInfo],
Error: type \'NoneType\' has no operator [](Provider)
```
See comments in https://github.com/bazelbuild/rules_nodejs/pull/3694 
cc @DavidZbarsky-at
> Use `headers` attribute for toolchains only if it is set

- nodejs/private/os_name.bzl
Work properly on intel CPUs on ox. Normalize x86_64->amd64 naming in `osname()` method
In particular on x86 macbooks, the rctx.os.arch returns x86_64 (and not 'amd64') as expected by the nodejs namings. This behaviour (and difference vs. linux) is documented here: https://mail.openjdk.org/pipermail/macosx-port-dev/2012-February/002860.html
This led to errors like:
```
... depends on @nodejs-macos-x86_64//:node_toolchain in repository @nodejs-macos-x86_64 which failed to fetch. no such package '@nodejs-macos-x86_64//': Unsupported operating system darwin architecture x86_64
```
The reason was the node_repositories role tries to check whether there is node for the host system on the list.
The problem was most likely introduced in #3698. 
Please check if your PR fulfills the following …
> Work properly on intel CPUs on macos. Normalize x86_64->amd64 naming in `osname()` method

- .bazelci/presubmit.yml
- .gitignore
Seeing cc toolchain failures at HEAD that is blocking landing of PRs.
For example,
https://buildkite.com/bazel/rules-nodejs-nodejs/builds/13269#018e9046-54b9-4c20-9202-8e4dbbeae905
https://buildkite.com/bazel/rules-nodejs-nodejs/builds/13267
> chore: disable RBE on CI to work-around cc toolchain failures at HEAD

- nodejs/repositories.bzl
Corner case I hit in rules_js. The current error message if you accidentally set `node_urls = []` is not great. This bit of code restores the default value if the user happens to clear it with an empty list.
> fix: use default node url if the user happens to explicitly set []

- WORKSPACE
- e2e/nodejs_host/BUILD.bazel
- e2e/nodejs_host/MODULE.bazel
- e2e/nodejs_host/WORKSPACE
- e2e/smoke/BUILD.bazel
- e2e/smoke/MODULE.bazel
- e2e/smoke/WORKSPACE.bazel
Node 16 was the first node version that had MacOS arm support so bump usage of Node 14 & 15 to 17 in this PR. We can't go to 18 because Bazel CI runners have an older version of GLIBC that doesn't work with 18.
> chore: support local development on MacOS ARM

- docs/Core.md
- e2e/smoke/BUILD.bazel
- nodejs/index.for_docs.bzl
- nodejs/repositories.bzl
- nodejs/toolchain.bzl
To-date the node toolchain has provided paths (strings) to node and npm. This complicates downstream usage as they need to convert these paths depending on they are used (between execpath and rootpath for example). This change configures the toolchain to also provide File objects for node and the npm entry point script so downsteam uses can choose to get either the `.path` or `.short_path` as needed.
Deprecates `target_tool` and `target_tool_path` parameters. Maintains backward compat by setting both `target_tool_path` and `tool_files` in the provider. 
> feat: update node toolchain to provide File objects

- docs/Core.md
- nodejs/repositories.bzl
- nodejs/toolchain.bzl
This simplifies downstream usage since `npm_srcs` can just be used directly instead of having to construct a depset from `npm_files`
The `to_list()` call is still necessary here in the toolchain creation but once the DEPRECATED fields can be removed then that will be go away.  DEPRECATED fields can be removed in a future likely when support for WORKSPACE is dropped.
> refactor: deprecate npm_files list attribute in favor of npm_srcs depset

- nodejs/toolchain.bzl
The full "sources" is more in line with common provider naming including JsInfo. This is not breaking since the `npm_srcs` naming has not yet made it into a release.
> refactor: rename NodeInfo npm_srcs to npm_sources

- MODULE.bazel
- WORKSPACE
- e2e/nodejs_host/MODULE.bazel
- e2e/nodejs_host/WORKSPACE
- e2e/smoke/MODULE.bazel
- e2e/smoke/WORKSPACE.bazel
- repositories.bzl
Bump is not passed onto users as this is just a dev dep in this repo.
> chore: bump to bazel-lib 2.7.1 (dev dep)

- MODULE.bazel
Fixes https://github.com/aspect-build/rules_js/issues/1530.
Related to https://github.com/bazelbuild/bazel/issues/19645.
Toolchain registration ordering matters since it affects which toolchain Bazel resolves. This PR makes the bzlmod registration match the registration order in WORKSPACE.
In particular, the `:<PLATFORM>_toolchain_target` (which defines `target_compatible_with`) should be registered before `:<PLATFORM>_toolchain` (which defines `exec_compatible_with`) for each platform. In WORKSPACE this is done here: https://github.com/bazelbuild/rules_nodejs/blob/4c373209b058d46f2a5f9ab9f8abf11b161ae459/nodejs/repositories.bzl#L461/. This is important so that Bazel selects the target compatible toolchain before it selects the execution compatible toolchain. The opposite ordering causes …
> fix: register Node.js toolchains in correct order

- .github/workflows/ci.yaml
- WORKSPACE
- docs/Core.md
- repositories.bzl
`main` on GitHub Actions has been red since https://github.com/bazelbuild/rules_nodejs/commit/245a464cba303692d155a78d3dd4e98bfc1ed0b2. Breakage slipped through the PR since GitHub Actions CI is currently only run against the `main` branch. This PR re-enables running it on PRs again and fixes the breakage.
> chore: re-enable GitHub Actions CI for PRs and green up main

- .github/workflows/ci.yaml
- e2e/nodejs_host/version_test.sh
- e2e/smoke/MODULE.bazel
- e2e/smoke/WORKSPACE.bazel
The coverage on Bazel CI doesn't cover all cases. This is a pre-factor for fixing the https://github.com/bazelbuild/rules_nodejs/issues/3720 bug.
> chore: enable and green up e2e/smoke and e2e/nodejs_host tests on GitHub Actions

- MODULE.bazel
No reason to set an explicit name here since it always has to be `DEFAULT_NODE_REPOSITORY` or else the following line in `extensions.bzl` will fail downstream:
```
if toolchain.name != DEFAULT_NODE_REPOSITORY and not mod.is_root:
fail("Only the root module may provide a name for the node toolchain.")
```
> chore: in rules_js MODULE.bazel use default value for name of node.toolchain()

- packages/runfiles/paths.ts
- packages/runfiles/repository.ts
- packages/runfiles/runfiles.ts
Inspired by: https://github.com/bazelbuild/rules_python/commit/96621391e7e8861eb448fb94b49aa1fcb9f45ba7, https://github.com/bazelbuild/rules_go/commit/fd8c0415054c923e62000417121dfd640c3cc14e
It seems like the `packages/runfiles/tests` have not been run for quite some time and can't be run in their current form. I've added those tests rules_js in https://github.com/aspect-build/rules_js/pull/1895 and I've been testing there where tests were failing with bzlmod which this PR fixes.
Issue Number: #3714
> fix(runfiles): support bzlmod repo mappings

- packages/runfiles/index.ts
Non-public internal API is no longer exported.
> refactor(runfiles): do not export private BAZEL_OUT_REGEX

- packages/runfiles/runfiles.ts
When in non-bzlmod and no `_repo_mapping` file exists the logic repo mapping logic should have no side-effects and should take the same code path as before https://github.com/bazel-contrib/rules_nodejs/commit/21b56da9f20c9c5e8b8c1ac19052f1f7cc7b5920
> fix(runfiles): @bazel/runfiles usage with non-bzlmod repos

- nodejs/private/nodejs_toolchains_repo.bzl
As documented at https://bazel.build/rules/lib/globals/bzl.html#rule:
incompatible_use_toolchain_transition
bool; default is False
Deprecated, this is no longer in use and should be removed.
According to https://github.com/bazelbuild/bazel/pull/14049, this feature was enabled by default back in 2021.
`rule()` is called with `incompatible_use_toolchain_transition = True`. This argument is a no-op right now, because Bazel merely provides a placeholder for this option. However, having this argument in place would cause breakages if the Bazel team decides to remove this option altogether.
We call it without this argument. This does not cause any noticeable differences.
> fix: remove use of incompatible_use_toolchain_transition

- .github/workflows/release.yml
- .github/workflows/release_prep.sh
- .github/workflows/tag.yaml
- CONTRIBUTING.md
Downstreams https://github.com/bazel-contrib/rules-template/pull/129 
Addresses https://github.com/bazel-contrib/rules_nodejs/discussions/3821
> chore: add auto-release

- packages/runfiles/runfiles.ts
Issue Number: [3837](https://github.com/bazel-contrib/rules_nodejs/issues/3837)
> feat: lazy initialize runfiles

- e2e/nodejs_host/BUILD.bazel
- e2e/nodejs_host/MODULE.bazel
- e2e/nodejs_host/WORKSPACE.bazel
- nodejs/extensions.bzl
Close #3781
Issue Number: #3781
> feat: add bzlmod node_repositories support

- e2e/smoke/BUILD.bazel
- nodejs/toolchain.bzl
> fix: expose npm binary in toolchain files

- MODULE.bazel
- nodejs/private/node_versions.bzl
- nodejs/private/nodejs_toolchains_repo.bzl
- nodejs/private/os_name.bzl
- scripts/update-nodejs-versions.js
Let me know if this needs any tests or docs. GitHub Actions has native Windows arm64 runners that we could use for tests if desired.
Currently, only `windows_amd64` is supported, but not `windows_arm64`.
This PR introduces support for `windows_arm64`, which has been supported as of NodeJS v20.
> feat: add windows_arm64 support

- scripts/update-nodejs-versions.js
Node.js is currently the latest version of Node.js.
> fix: update update-nodejs-versions.js to include Node.js 24
